use imgui::sys;
use serde::{Deserialize, Deserializer, Serialize};
use serde_with::{DeserializeAs, SerializeAs};

#[derive(Serialize, Deserialize)]
#[serde(remote = "imgui::Key")]
#[repr(u32)]
#[derive(Copy, Clone, Debug, Hash, Eq, PartialEq)]
#[allow(missing_docs)]
#[non_exhaustive]
pub enum ImGuiKeyDef {
    Tab = sys::ImGuiKey_Tab,
    LeftArrow = sys::ImGuiKey_LeftArrow,
    RightArrow = sys::ImGuiKey_RightArrow,
    UpArrow = sys::ImGuiKey_UpArrow,
    DownArrow = sys::ImGuiKey_DownArrow,
    PageUp = sys::ImGuiKey_PageUp,
    PageDown = sys::ImGuiKey_PageDown,
    Home = sys::ImGuiKey_Home,
    End = sys::ImGuiKey_End,
    Insert = sys::ImGuiKey_Insert,
    Delete = sys::ImGuiKey_Delete,
    Backspace = sys::ImGuiKey_Backspace,
    Space = sys::ImGuiKey_Space,
    Enter = sys::ImGuiKey_Enter,
    Escape = sys::ImGuiKey_Escape,
    LeftCtrl = sys::ImGuiKey_LeftCtrl,
    LeftShift = sys::ImGuiKey_LeftShift,
    LeftAlt = sys::ImGuiKey_LeftAlt,
    LeftSuper = sys::ImGuiKey_LeftSuper,
    RightCtrl = sys::ImGuiKey_RightCtrl,
    RightShift = sys::ImGuiKey_RightShift,
    RightAlt = sys::ImGuiKey_RightAlt,
    RightSuper = sys::ImGuiKey_RightSuper,
    Menu = sys::ImGuiKey_Menu,
    Alpha0 = sys::ImGuiKey_0,
    Alpha1 = sys::ImGuiKey_1,
    Alpha2 = sys::ImGuiKey_2,
    Alpha3 = sys::ImGuiKey_3,
    Alpha4 = sys::ImGuiKey_4,
    Alpha5 = sys::ImGuiKey_5,
    Alpha6 = sys::ImGuiKey_6,
    Alpha7 = sys::ImGuiKey_7,
    Alpha8 = sys::ImGuiKey_8,
    Alpha9 = sys::ImGuiKey_9,
    A = sys::ImGuiKey_A,
    B = sys::ImGuiKey_B,
    C = sys::ImGuiKey_C,
    D = sys::ImGuiKey_D,
    E = sys::ImGuiKey_E,
    F = sys::ImGuiKey_F,
    G = sys::ImGuiKey_G,
    H = sys::ImGuiKey_H,
    I = sys::ImGuiKey_I,
    J = sys::ImGuiKey_J,
    K = sys::ImGuiKey_K,
    L = sys::ImGuiKey_L,
    M = sys::ImGuiKey_M,
    N = sys::ImGuiKey_N,
    O = sys::ImGuiKey_O,
    P = sys::ImGuiKey_P,
    Q = sys::ImGuiKey_Q,
    R = sys::ImGuiKey_R,
    S = sys::ImGuiKey_S,
    T = sys::ImGuiKey_T,
    U = sys::ImGuiKey_U,
    V = sys::ImGuiKey_V,
    W = sys::ImGuiKey_W,
    X = sys::ImGuiKey_X,
    Y = sys::ImGuiKey_Y,
    Z = sys::ImGuiKey_Z,
    F1 = sys::ImGuiKey_F1,
    F2 = sys::ImGuiKey_F2,
    F3 = sys::ImGuiKey_F3,
    F4 = sys::ImGuiKey_F4,
    F5 = sys::ImGuiKey_F5,
    F6 = sys::ImGuiKey_F6,
    F7 = sys::ImGuiKey_F7,
    F8 = sys::ImGuiKey_F8,
    F9 = sys::ImGuiKey_F9,
    F10 = sys::ImGuiKey_F10,
    F11 = sys::ImGuiKey_F11,
    F12 = sys::ImGuiKey_F12,
    Apostrophe = sys::ImGuiKey_Apostrophe,
    Comma = sys::ImGuiKey_Comma,
    Minus = sys::ImGuiKey_Minus,
    Period = sys::ImGuiKey_Period,
    Slash = sys::ImGuiKey_Slash,
    Semicolon = sys::ImGuiKey_Semicolon,
    Equal = sys::ImGuiKey_Equal,
    LeftBracket = sys::ImGuiKey_LeftBracket,
    Backslash = sys::ImGuiKey_Backslash,
    RightBracket = sys::ImGuiKey_RightBracket,
    GraveAccent = sys::ImGuiKey_GraveAccent,
    CapsLock = sys::ImGuiKey_CapsLock,
    ScrollLock = sys::ImGuiKey_ScrollLock,
    NumLock = sys::ImGuiKey_NumLock,
    PrintScreen = sys::ImGuiKey_PrintScreen,
    Pause = sys::ImGuiKey_Pause,
    Keypad0 = sys::ImGuiKey_Keypad0,
    Keypad1 = sys::ImGuiKey_Keypad1,
    Keypad2 = sys::ImGuiKey_Keypad2,
    Keypad3 = sys::ImGuiKey_Keypad3,
    Keypad4 = sys::ImGuiKey_Keypad4,
    Keypad5 = sys::ImGuiKey_Keypad5,
    Keypad6 = sys::ImGuiKey_Keypad6,
    Keypad7 = sys::ImGuiKey_Keypad7,
    Keypad8 = sys::ImGuiKey_Keypad8,
    Keypad9 = sys::ImGuiKey_Keypad9,
    KeypadDecimal = sys::ImGuiKey_KeypadDecimal,
    KeypadDivide = sys::ImGuiKey_KeypadDivide,
    KeypadMultiply = sys::ImGuiKey_KeypadMultiply,
    KeypadSubtract = sys::ImGuiKey_KeypadSubtract,
    KeypadAdd = sys::ImGuiKey_KeypadAdd,
    KeypadEnter = sys::ImGuiKey_KeypadEnter,
    KeypadEqual = sys::ImGuiKey_KeypadEqual,
    GamepadStart = sys::ImGuiKey_GamepadStart,
    GamepadBack = sys::ImGuiKey_GamepadBack,
    GamepadFaceLeft = sys::ImGuiKey_GamepadFaceLeft,
    GamepadFaceRight = sys::ImGuiKey_GamepadFaceRight,
    GamepadFaceUp = sys::ImGuiKey_GamepadFaceUp,
    GamepadFaceDown = sys::ImGuiKey_GamepadFaceDown,
    GamepadDpadLeft = sys::ImGuiKey_GamepadDpadLeft,
    GamepadDpadRight = sys::ImGuiKey_GamepadDpadRight,
    GamepadDpadUp = sys::ImGuiKey_GamepadDpadUp,
    GamepadDpadDown = sys::ImGuiKey_GamepadDpadDown,
    GamepadL1 = sys::ImGuiKey_GamepadL1,
    GamepadR1 = sys::ImGuiKey_GamepadR1,
    GamepadL2 = sys::ImGuiKey_GamepadL2,
    GamepadR2 = sys::ImGuiKey_GamepadR2,
    GamepadL3 = sys::ImGuiKey_GamepadL3,
    GamepadR3 = sys::ImGuiKey_GamepadR3,
    GamepadLStickLeft = sys::ImGuiKey_GamepadLStickLeft,
    GamepadLStickRight = sys::ImGuiKey_GamepadLStickRight,
    GamepadLStickUp = sys::ImGuiKey_GamepadLStickUp,
    GamepadLStickDown = sys::ImGuiKey_GamepadLStickDown,
    GamepadRStickLeft = sys::ImGuiKey_GamepadRStickLeft,
    GamepadRStickRight = sys::ImGuiKey_GamepadRStickRight,
    GamepadRStickUp = sys::ImGuiKey_GamepadRStickUp,
    GamepadRStickDown = sys::ImGuiKey_GamepadRStickDown,
    MouseLeft = sys::ImGuiKey_MouseLeft,
    MouseRight = sys::ImGuiKey_MouseRight,
    MouseMiddle = sys::ImGuiKey_MouseMiddle,
    MouseX1 = sys::ImGuiKey_MouseX1,
    MouseX2 = sys::ImGuiKey_MouseX2,
    MouseWheelX = sys::ImGuiKey_MouseWheelX,
    MouseWheelY = sys::ImGuiKey_MouseWheelY,
    ReservedForModCtrl = sys::ImGuiKey_ReservedForModCtrl,
    ReservedForModShift = sys::ImGuiKey_ReservedForModShift,
    ReservedForModAlt = sys::ImGuiKey_ReservedForModAlt,
    ReservedForModSuper = sys::ImGuiKey_ReservedForModSuper,
    ModCtrl = sys::ImGuiMod_Ctrl,
    ModShift = sys::ImGuiMod_Shift,
    ModAlt = sys::ImGuiMod_Alt,
    ModSuper = sys::ImGuiMod_Super,
    ModShortcut = sys::ImGuiMod_Shortcut,
}

impl SerializeAs<imgui::Key> for ImGuiKeyDef {
    fn serialize_as<S>(value: &imgui::Key, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        ImGuiKeyDef::serialize(value, serializer)
    }
}

impl<'de> DeserializeAs<'de, imgui::Key> for ImGuiKeyDef {
    fn deserialize_as<D>(deserializer: D) -> Result<imgui::Key, D::Error>
    where
        D: Deserializer<'de>,
    {
        ImGuiKeyDef::deserialize(deserializer)
    }
}

pub trait ImguiKeyCustomFunctions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result;
}

impl ImguiKeyCustomFunctions for imgui::Key {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            imgui::Key::Tab => f.write_str("Tab"),
            imgui::Key::LeftArrow => f.write_str("Left"),
            imgui::Key::RightArrow => f.write_str("Right"),
            imgui::Key::UpArrow => f.write_str("Up"),
            imgui::Key::DownArrow => f.write_str("Down"),
            imgui::Key::PageUp => f.write_str("Page Up"),
            imgui::Key::PageDown => f.write_str("Page Down"),
            imgui::Key::Home => f.write_str("Home"),
            imgui::Key::End => f.write_str("End"),
            imgui::Key::Insert => f.write_str("Insert"),
            imgui::Key::Delete => f.write_str("Delete"),
            imgui::Key::Backspace => f.write_str("Backspace"),
            imgui::Key::Space => f.write_str("Space"),
            imgui::Key::Enter => f.write_str("Enter"),
            imgui::Key::Escape => f.write_str("Escape"),
            imgui::Key::LeftCtrl => f.write_str("Left Control"),
            imgui::Key::LeftShift => f.write_str("Left Shift"),
            imgui::Key::LeftAlt => f.write_str("Left Alt"),
            imgui::Key::LeftSuper => f.write_str("Left Super"),
            imgui::Key::RightCtrl => f.write_str("Right Control"),
            imgui::Key::RightShift => f.write_str("Right Shift"),
            imgui::Key::RightAlt => f.write_str("Right Alt"),
            imgui::Key::RightSuper => f.write_str("Right Super"),
            imgui::Key::Menu => f.write_str("Menu"),
            imgui::Key::Alpha0 => f.write_str("0"),
            imgui::Key::Alpha1 => f.write_str("1"),
            imgui::Key::Alpha2 => f.write_str("2"),
            imgui::Key::Alpha3 => f.write_str("3"),
            imgui::Key::Alpha4 => f.write_str("4"),
            imgui::Key::Alpha5 => f.write_str("5"),
            imgui::Key::Alpha6 => f.write_str("6"),
            imgui::Key::Alpha7 => f.write_str("7"),
            imgui::Key::Alpha8 => f.write_str("8"),
            imgui::Key::Alpha9 => f.write_str("9"),
            imgui::Key::A => f.write_str("A"),
            imgui::Key::B => f.write_str("B"),
            imgui::Key::C => f.write_str("C"),
            imgui::Key::D => f.write_str("D"),
            imgui::Key::E => f.write_str("E"),
            imgui::Key::F => f.write_str("F"),
            imgui::Key::G => f.write_str("G"),
            imgui::Key::H => f.write_str("H"),
            imgui::Key::I => f.write_str("I"),
            imgui::Key::J => f.write_str("J"),
            imgui::Key::K => f.write_str("K"),
            imgui::Key::L => f.write_str("L"),
            imgui::Key::M => f.write_str("M"),
            imgui::Key::N => f.write_str("N"),
            imgui::Key::O => f.write_str("O"),
            imgui::Key::P => f.write_str("P"),
            imgui::Key::Q => f.write_str("Q"),
            imgui::Key::R => f.write_str("R"),
            imgui::Key::S => f.write_str("S"),
            imgui::Key::T => f.write_str("T"),
            imgui::Key::U => f.write_str("U"),
            imgui::Key::V => f.write_str("V"),
            imgui::Key::W => f.write_str("W"),
            imgui::Key::X => f.write_str("X"),
            imgui::Key::Y => f.write_str("Y"),
            imgui::Key::Z => f.write_str("Z"),
            imgui::Key::F1 => f.write_str("F1"),
            imgui::Key::F2 => f.write_str("F2"),
            imgui::Key::F3 => f.write_str("F3"),
            imgui::Key::F4 => f.write_str("F4"),
            imgui::Key::F5 => f.write_str("F5"),
            imgui::Key::F6 => f.write_str("F6"),
            imgui::Key::F7 => f.write_str("F7"),
            imgui::Key::F8 => f.write_str("F8"),
            imgui::Key::F9 => f.write_str("F9"),
            imgui::Key::F10 => f.write_str("F10"),
            imgui::Key::F11 => f.write_str("F11"),
            imgui::Key::F12 => f.write_str("F12"),
            imgui::Key::Apostrophe => f.write_str("Apostrophe"),
            imgui::Key::Comma => f.write_str("Comma"),
            imgui::Key::Minus => f.write_str("Minus"),
            imgui::Key::Period => f.write_str("Period"),
            imgui::Key::Slash => f.write_str("Slash"),
            imgui::Key::Semicolon => f.write_str("Semicolon"),
            imgui::Key::Equal => f.write_str("Equal"),
            imgui::Key::LeftBracket => f.write_str("Left Bracket"),
            imgui::Key::Backslash => f.write_str("Backslash"),
            imgui::Key::RightBracket => f.write_str("Right Bracket"),
            imgui::Key::GraveAccent => f.write_str("Grave Accent"),
            imgui::Key::CapsLock => f.write_str("Caps Lock"),
            imgui::Key::ScrollLock => f.write_str("Scroll Lock"),
            imgui::Key::NumLock => f.write_str("Num Lock"),
            imgui::Key::PrintScreen => f.write_str("Print Screen"),
            imgui::Key::Pause => f.write_str("Pause"),
            imgui::Key::Keypad0 => f.write_str("Keypad 0"),
            imgui::Key::Keypad1 => f.write_str("Keypad 1"),
            imgui::Key::Keypad2 => f.write_str("Keypad 2"),
            imgui::Key::Keypad3 => f.write_str("Keypad 3"),
            imgui::Key::Keypad4 => f.write_str("Keypad 4"),
            imgui::Key::Keypad5 => f.write_str("Keypad 5"),
            imgui::Key::Keypad6 => f.write_str("Keypad 6"),
            imgui::Key::Keypad7 => f.write_str("Keypad 7"),
            imgui::Key::Keypad8 => f.write_str("Keypad 8"),
            imgui::Key::Keypad9 => f.write_str("Keypad 9"),
            imgui::Key::KeypadDecimal => f.write_str("Keypad Decimal"),
            imgui::Key::KeypadDivide => f.write_str("Keypad Divide"),
            imgui::Key::KeypadMultiply => f.write_str("Keypad Multiply"),
            imgui::Key::KeypadSubtract => f.write_str("Keypad Subtract"),
            imgui::Key::KeypadAdd => f.write_str("Keypad Add"),
            imgui::Key::KeypadEnter => f.write_str("Keypad Enter"),
            imgui::Key::KeypadEqual => f.write_str("Keypad Equal"),
            imgui::Key::GamepadStart => f.write_str("Gamepad Start"),
            imgui::Key::GamepadBack => f.write_str("Gamepad Back"),
            imgui::Key::GamepadFaceLeft => f.write_str("Gamepad Face Left"),
            imgui::Key::GamepadFaceRight => f.write_str("Gamepad Face Right"),
            imgui::Key::GamepadFaceUp => f.write_str("Gamepad Face Up"),
            imgui::Key::GamepadFaceDown => f.write_str("Gamepad Face Down"),
            imgui::Key::GamepadDpadLeft => f.write_str("Gamepad D-Pad Left"),
            imgui::Key::GamepadDpadRight => f.write_str("Gamepad D-Pad Right"),
            imgui::Key::GamepadDpadUp => f.write_str("Gamepad D-Pad Up"),
            imgui::Key::GamepadDpadDown => f.write_str("Gamepad D-Pad Down"),
            imgui::Key::GamepadL1 => f.write_str("Gamepad L1"),
            imgui::Key::GamepadR1 => f.write_str("Gamepad R1"),
            imgui::Key::GamepadL2 => f.write_str("Gamepad L2"),
            imgui::Key::GamepadR2 => f.write_str("Gamepad R2"),
            imgui::Key::GamepadL3 => f.write_str("Gamepad L3"),
            imgui::Key::GamepadR3 => f.write_str("Gamepad R3"),
            imgui::Key::GamepadLStickLeft => f.write_str("Gamepad L-Stick Left"),
            imgui::Key::GamepadLStickRight => f.write_str("Gamepad L-Stick Right"),
            imgui::Key::GamepadLStickUp => f.write_str("Gamepad L-Stick Up"),
            imgui::Key::GamepadLStickDown => f.write_str("Gamepad L-Stick Down"),
            imgui::Key::GamepadRStickLeft => f.write_str("Gamepad R-Stick Left"),
            imgui::Key::GamepadRStickRight => f.write_str("Gamepad R-Stick Right"),
            imgui::Key::GamepadRStickUp => f.write_str("Gamepad R-Stic kUp"),
            imgui::Key::GamepadRStickDown => f.write_str("Gamepad R-Stick Down"),
            imgui::Key::MouseLeft => f.write_str("Mouse Left"),
            imgui::Key::MouseRight => f.write_str("Mouse Right"),
            imgui::Key::MouseMiddle => f.write_str("Mouse Middle"),
            imgui::Key::MouseX1 => f.write_str("Mouse X1"),
            imgui::Key::MouseX2 => f.write_str("Mouse X2"),
            imgui::Key::MouseWheelX => f.write_str("Mousewheel X"),
            imgui::Key::MouseWheelY => f.write_str("Mousewheel Y"),
            imgui::Key::ReservedForModCtrl => f.write_str("ReservedForModCtrl"),
            imgui::Key::ReservedForModShift => f.write_str("ReservedForModShift"),
            imgui::Key::ReservedForModAlt => f.write_str("ReservedForModAlt"),
            imgui::Key::ReservedForModSuper => f.write_str("ReservedForModSuper"),
            imgui::Key::ModCtrl => f.write_str("Control"),
            imgui::Key::ModShift => f.write_str("Shift"),
            imgui::Key::ModAlt => f.write_str("Alt"),
            imgui::Key::ModSuper => f.write_str("Super"),
            imgui::Key::ModShortcut => f.write_str("Shortcut"),
            _ => f.write_str("Unknown Key"),
        }
    }
}
