use crate::gml::{Context, GameVariable, InstanceVariable, Runtime, Value};

/// Default numerical constants for GML
pub const CONSTANTS: [(&str, f64); 317] = [
    ("ANSI_CHARSET", 0.0f64),
    ("ARABIC_CHARSET", 178.0),
    ("BALTIC_CHARSET", 186.0),
    ("CHINESEBIG5_CHARSET", 136.0),
    ("DEFAULT_CHARSET", 1.0),
    ("EASTEUROPE_CHARSET", 238.0),
    ("GB2312_CHARSET", 134.0),
    ("GREEK_CHARSET", 161.0),
    ("HANGEUL_CHARSET", 129.0),
    ("HEBREW_CHARSET", 177.0),
    ("JOHAB_CHARSET", 130.0),
    ("MAC_CHARSET", 77.0),
    ("OEM_CHARSET", 255.0),
    ("RUSSIAN_CHARSET", 204.0),
    ("SHIFTJIS_CHARSET", 128.0),
    ("SYMBOL_CHARSET", 2.0),
    ("THAI_CHARSET", 222.0),
    ("TURKISH_CHARSET", 162.0),
    ("VIETNAMESE_CHARSET", 163.0),
    ("all", -3.0),
    ("bm_add", 1.0),
    ("bm_dest_alpha", 7.0),
    ("bm_dest_color", 9.0),
    ("bm_inv_dest_alpha", 8.0),
    ("bm_inv_dest_color", 10.0),
    ("bm_inv_src_alpha", 6.0),
    ("bm_inv_src_color", 4.0),
    ("bm_max", 2.0),
    ("bm_normal", 0.0),
    ("bm_one", 2.0),
    ("bm_src_alpha", 5.0),
    ("bm_src_alpha_sat", 11.0),
    ("bm_src_color", 3.0),
    ("bm_subtract", 3.0),
    ("bm_zero", 1.0),
    ("button_type", 1.0),
    ("c_aqua", 16776960.0),
    ("c_black", 0.0),
    ("c_blue", 16711680.0),
    ("c_dkgray", 4210752.0),
    ("c_fuchsia", 16711935.0),
    ("c_gray", 8421504.0),
    ("c_green", 32768.0),
    ("c_lime", 65280.0),
    ("c_ltgray", 12632256.0),
    ("c_maroon", 128.0),
    ("c_navy", 8388608.0),
    ("c_olive", 32896.0),
    ("c_orange", 4235519.0),
    ("c_purple", 8388736.0),
    ("c_red", 255.0),
    ("c_silver", 12632256.0),
    ("c_teal", 8421376.0),
    ("c_white", 16777215.0),
    ("c_yellow", 65535.0),
    ("cr_appstart", -19.0),
    ("cr_arrow", -2.0),
    ("cr_beam", -4.0),
    ("cr_cross", -3.0),
    ("cr_default", 0.0),
    ("cr_drag", -12.0),
    ("cr_handpoint", -21.0),
    ("cr_help", -20.0),
    ("cr_hourglass", -11.0),
    ("cr_hsplit", -14.0),
    ("cr_multidrag", -16.0),
    ("cr_no", -18.0),
    ("cr_nodrop", -13.0),
    ("cr_none", -1.0),
    ("cr_size_all", -22.0),
    ("cr_size_nesw", -6.0),
    ("cr_size_ns", -7.0),
    ("cr_size_nwse", -8.0),
    ("cr_size_we", -9.0),
    ("cr_sqlwait", -17.0),
    ("cr_uparrow", -10.0),
    ("cr_vsplit", -15.0),
    ("device_ios_ipad", 2.0),
    ("device_ios_iphone", 0.0),
    ("device_ios_iphone_retina", 1.0),
    ("dll_cdecl", 0.0),
    ("dll_stdcall", 1.0),
    ("ef_cloud", 9.0),
    ("ef_ellipse", 2.0),
    ("ef_explosion", 0.0),
    ("ef_firework", 3.0),
    ("ef_flare", 8.0),
    ("ef_rain", 10.0),
    ("ef_ring", 1.0),
    ("ef_smoke", 4.0),
    ("ef_smokeup", 5.0),
    ("ef_snow", 11.0),
    ("ef_spark", 7.0),
    ("ef_star", 6.0),
    ("ev_alarm", 2.0),
    ("ev_animation_end", 7.0),
    ("ev_boundary", 1.0),
    ("ev_close_button", 30.0),
    ("ev_collision", 4.0),
    ("ev_create", 0.0),
    ("ev_destroy", 1.0),
    ("ev_draw", 8.0),
    ("ev_end_of_path", 8.0),
    ("ev_game_end", 3.0),
    ("ev_game_start", 2.0),
    ("ev_global_left_button", 50.0),
    ("ev_global_left_press", 53.0),
    ("ev_global_left_release", 56.0),
    ("ev_global_middle_button", 52.0),
    ("ev_global_middle_press", 55.0),
    ("ev_global_middle_release", 58.0),
    ("ev_global_press", 12.0),
    ("ev_global_release", 13.0),
    ("ev_global_right_button", 51.0),
    ("ev_global_right_press", 54.0),
    ("ev_global_right_release", 57.0),
    ("ev_joystick1_button1", 21.0),
    ("ev_joystick1_button2", 22.0),
    ("ev_joystick1_button3", 23.0),
    ("ev_joystick1_button4", 24.0),
    ("ev_joystick1_button5", 25.0),
    ("ev_joystick1_button6", 26.0),
    ("ev_joystick1_button7", 27.0),
    ("ev_joystick1_button8", 28.0),
    ("ev_joystick1_down", 19.0),
    ("ev_joystick1_left", 16.0),
    ("ev_joystick1_right", 17.0),
    ("ev_joystick1_up", 18.0),
    ("ev_joystick2_button1", 36.0),
    ("ev_joystick2_button2", 37.0),
    ("ev_joystick2_button3", 38.0),
    ("ev_joystick2_button4", 39.0),
    ("ev_joystick2_button5", 40.0),
    ("ev_joystick2_button6", 41.0),
    ("ev_joystick2_button7", 42.0),
    ("ev_joystick2_button8", 43.0),
    ("ev_joystick2_down", 34.0),
    ("ev_joystick2_left", 31.0),
    ("ev_joystick2_right", 32.0),
    ("ev_joystick2_up", 33.0),
    ("ev_keyboard", 5.0),
    ("ev_keypress", 9.0),
    ("ev_keyrelease", 10.0),
    ("ev_left_button", 0.0),
    ("ev_left_press", 4.0),
    ("ev_left_release", 7.0),
    ("ev_middle_button", 2.0),
    ("ev_middle_press", 6.0),
    ("ev_middle_release", 9.0),
    ("ev_mouse", 6.0),
    ("ev_mouse_enter", 10.0),
    ("ev_mouse_leave", 11.0),
    ("ev_mouse_wheel_down", 61.0),
    ("ev_mouse_wheel_up", 60.0),
    ("ev_no_button", 3.0),
    ("ev_no_more_health", 9.0),
    ("ev_no_more_lives", 6.0),
    ("ev_other", 7.0),
    ("ev_outside", 0.0),
    ("ev_right_button", 1.0),
    ("ev_right_press", 5.0),
    ("ev_right_release", 8.0),
    ("ev_room_end", 5.0),
    ("ev_room_start", 4.0),
    ("ev_step", 3.0),
    ("ev_step_begin", 1.0),
    ("ev_step_end", 2.0),
    ("ev_step_normal", 0.0),
    ("ev_trigger", 11.0),
    ("ev_user0", 10.0),
    ("ev_user1", 11.0),
    ("ev_user10", 20.0),
    ("ev_user11", 21.0),
    ("ev_user12", 22.0),
    ("ev_user13", 23.0),
    ("ev_user14", 24.0),
    ("ev_user15", 25.0),
    ("ev_user2", 12.0),
    ("ev_user3", 13.0),
    ("ev_user4", 14.0),
    ("ev_user5", 15.0),
    ("ev_user6", 16.0),
    ("ev_user7", 17.0),
    ("ev_user8", 18.0),
    ("ev_user9", 19.0),
    ("fa_archive", 32.0),
    ("fa_bottom", 2.0),
    ("fa_center", 1.0),
    ("fa_directory", 16.0),
    ("fa_hidden", 2.0),
    ("fa_left", 0.0),
    ("fa_middle", 1.0),
    ("fa_readonly", 1.0),
    ("fa_right", 2.0),
    ("fa_sysfile", 4.0),
    ("fa_top", 0.0),
    ("fa_volumeid", 8.0),
    ("false", 0.0),
    ("global", -5.0),
    ("local", -7.0),
    ("mb_any", -1.0),
    ("mb_left", 1.0),
    ("mb_middle", 3.0),
    ("mb_none", 0.0),
    ("mb_right", 2.0),
    ("noone", -4.0),
    ("os_android", 5.0),
    ("os_ios", 4.0),
    ("os_macosx", 2.0),
    ("os_psp", 3.0),
    ("os_win32", 0.0),
    ("other", -2.0),
    ("pi", 3.141592654),
    ("pr_linelist", 2.0),
    ("pr_linestrip", 3.0),
    ("pr_pointlist", 1.0),
    ("pr_trianglefan", 6.0),
    ("pr_trianglelist", 4.0),
    ("pr_trianglestrip", 5.0),
    ("ps_change_all", 0.0),
    ("ps_change_motion", 2.0),
    ("ps_change_shape", 1.0),
    ("ps_deflect_horizontal", 1.0),
    ("ps_deflect_vertical", 0.0),
    ("ps_distr_gaussian", 1.0),
    ("ps_distr_invgaussian", 2.0),
    ("ps_distr_linear", 0.0),
    ("ps_force_constant", 0.0),
    ("ps_force_linear", 1.0),
    ("ps_force_quadratic", 2.0),
    ("ps_shape_diamond", 2.0),
    ("ps_shape_ellipse", 1.0),
    ("ps_shape_line", 3.0),
    ("ps_shape_rectangle", 0.0),
    ("pt_shape_circle", 5.0),
    ("pt_shape_cloud", 11.0),
    ("pt_shape_disk", 1.0),
    ("pt_shape_explosion", 10.0),
    ("pt_shape_flare", 8.0),
    ("pt_shape_line", 3.0),
    ("pt_shape_pixel", 0.0),
    ("pt_shape_ring", 6.0),
    ("pt_shape_smoke", 12.0),
    ("pt_shape_snow", 13.0),
    ("pt_shape_spark", 9.0),
    ("pt_shape_sphere", 7.0),
    ("pt_shape_square", 2.0),
    ("pt_shape_star", 4.0),
    ("se_chorus", 1.0),
    ("se_compressor", 32.0),
    ("se_echo", 2.0),
    ("se_equalizer", 64.0),
    ("se_flanger", 4.0),
    ("se_gargle", 8.0),
    ("se_none", 0.0),
    ("se_reverb", 16.0),
    ("self", -1.0),
    ("text_type", 0.0),
    ("true", 1.0),
    ("ty_real", 0.0),
    ("ty_string", 1.0),
    ("vk_add", 107.0),
    ("vk_alt", 18.0),
    ("vk_anykey", 1.0),
    ("vk_backspace", 8.0),
    ("vk_control", 17.0),
    ("vk_decimal", 110.0),
    ("vk_delete", 46.0),
    ("vk_divide", 111.0),
    ("vk_down", 40.0),
    ("vk_end", 35.0),
    ("vk_enter", 13.0),
    ("vk_escape", 27.0),
    ("vk_f1", 112.0),
    ("vk_f10", 121.0),
    ("vk_f11", 122.0),
    ("vk_f12", 123.0),
    ("vk_f2", 113.0),
    ("vk_f3", 114.0),
    ("vk_f4", 115.0),
    ("vk_f5", 116.0),
    ("vk_f6", 117.0),
    ("vk_f7", 118.0),
    ("vk_f8", 119.0),
    ("vk_f9", 120.0),
    ("vk_home", 36.0),
    ("vk_insert", 45.0),
    ("vk_lalt", 164.0),
    ("vk_lcontrol", 162.0),
    ("vk_left", 37.0),
    ("vk_lshift", 160.0),
    ("vk_multiply", 106.0),
    ("vk_nokey", 0.0),
    ("vk_numpad0", 96.0),
    ("vk_numpad1", 97.0),
    ("vk_numpad2", 98.0),
    ("vk_numpad3", 99.0),
    ("vk_numpad4", 100.0),
    ("vk_numpad5", 101.0),
    ("vk_numpad6", 102.0),
    ("vk_numpad7", 103.0),
    ("vk_numpad8", 104.0),
    ("vk_numpad9", 105.0),
    ("vk_pagedown", 34.0),
    ("vk_pageup", 33.0),
    ("vk_pause", 19.0),
    ("vk_printscreen", 44.0),
    ("vk_ralt", 165.0),
    ("vk_rcontrol", 163.0),
    ("vk_return", 13.0),
    ("vk_right", 39.0),
    ("vk_rshift", 161.0),
    ("vk_shift", 16.0),
    ("vk_space", 32.0),
    ("vk_subtract", 109.0),
    ("vk_tab", 9.0),
    ("vk_up", 38.0),
];

/// Mappings of instance variable names to their enum identifiers
pub const INSTANCE_VARIABLES: [(&str, InstanceVariable); 47] = [
    ("id", InstanceVariable::Id),
    ("object_index", InstanceVariable::ObjectIndex),
    ("solid", InstanceVariable::Solid),
    ("visible", InstanceVariable::Visible),
    ("persistent", InstanceVariable::Persistent),
    ("depth", InstanceVariable::Depth),
    ("alarm", InstanceVariable::Alarm),
    ("sprite_index", InstanceVariable::SpriteIndex),
    ("image_alpha", InstanceVariable::ImageAlpha),
    ("image_blend", InstanceVariable::ImageBlend),
    ("image_index", InstanceVariable::ImageIndex),
    ("ImageSpeed", InstanceVariable::ImageSpeed),
    ("image_xscale", InstanceVariable::ImageXscale),
    ("image_yscale", InstanceVariable::ImageYscale),
    ("image_angle", InstanceVariable::ImageAngle),
    ("mask_index", InstanceVariable::MaskIndex),
    ("direction", InstanceVariable::Direction),
    ("friction", InstanceVariable::Friction),
    ("gravity", InstanceVariable::Gravity),
    ("gravity_direction", InstanceVariable::GravityDirection),
    ("hspeed", InstanceVariable::Hspeed),
    ("vspeed", InstanceVariable::Vspeed),
    ("speed", InstanceVariable::Speed),
    ("x", InstanceVariable::X),
    ("y", InstanceVariable::Y),
    ("xprevious", InstanceVariable::Xprevious),
    ("yprevious", InstanceVariable::Yprevious),
    ("xstart", InstanceVariable::Xstart),
    ("ystart", InstanceVariable::Ystart),
    ("path_index", InstanceVariable::PathIndex),
    ("path_position", InstanceVariable::PathPosition),
    ("path_positionprevious", InstanceVariable::PathPositionprevious),
    ("path_speed", InstanceVariable::PathSpeed),
    ("path_scale", InstanceVariable::PathScale),
    ("path_orientation", InstanceVariable::PathOrientation),
    ("path_endaction", InstanceVariable::PathEndaction),
    ("timeline_index", InstanceVariable::TimelineIndex),
    ("timeline_running", InstanceVariable::TimelineRunning),
    ("timeline_speed", InstanceVariable::TimelineSpeed),
    ("timeline_position", InstanceVariable::TimelinePosition),
    ("timeline_loop", InstanceVariable::TimelineLoop),
    ("sprite_width", InstanceVariable::SpriteWidth),
    ("sprite_height", InstanceVariable::SpriteHeight),
    ("bbox_left", InstanceVariable::BboxLeft),
    ("bbox_right", InstanceVariable::BboxRight),
    ("bbox_bottom", InstanceVariable::BboxBottom),
    ("bbox_top", InstanceVariable::BboxTop),
];

/// Mappings of game variable names to their enum identifiers
pub const GAME_VARIABLES: [(&str, GameVariable); 44] = [
    ("argument", GameVariable::Argument),
    ("argument0", GameVariable::Argument0),
    ("argument1", GameVariable::Argument1),
    ("argument2", GameVariable::Argument2),
    ("argument3", GameVariable::Argument3),
    ("argument4", GameVariable::Argument4),
    ("argument5", GameVariable::Argument5),
    ("argument6", GameVariable::Argument6),
    ("argument7", GameVariable::Argument7),
    ("argument8", GameVariable::Argument8),
    ("argument9", GameVariable::Argument9),
    ("argument10", GameVariable::Argument10),
    ("argument11", GameVariable::Argument11),
    ("argument12", GameVariable::Argument12),
    ("argument13", GameVariable::Argument13),
    ("argument14", GameVariable::Argument14),
    ("argument15", GameVariable::Argument15),
    ("current_time", GameVariable::CurrentTime),
    ("health", GameVariable::Health),
    ("instance_count", GameVariable::InstanceCount),
    ("lives", GameVariable::Lives),
    ("mouse_x", GameVariable::MouseX),
    ("mouse_y", GameVariable::MouseY),
    ("room", GameVariable::Room),
    ("room_speed", GameVariable::RoomSpeed),
    ("room_height", GameVariable::RoomHeight),
    ("room_width", GameVariable::RoomWidth),
    ("room_caption", GameVariable::RoomCaption),
    ("view_enabled", GameVariable::ViewEnabled),
    ("view_visible", GameVariable::ViewVisible),
    ("view_xview", GameVariable::ViewXview),
    ("view_yview", GameVariable::ViewYview),
    ("view_wview", GameVariable::ViewWview),
    ("view_hview", GameVariable::ViewHview),
    ("view_xport", GameVariable::ViewXport),
    ("view_yport", GameVariable::ViewYport),
    ("view_wport", GameVariable::ViewWport),
    ("view_hport", GameVariable::ViewHport),
    ("view_angle", GameVariable::ViewAngle),
    ("view_hborder", GameVariable::ViewHborder),
    ("view_vborder", GameVariable::ViewVborder),
    ("view_hspeed", GameVariable::ViewHspeed),
    ("view_vspeed", GameVariable::ViewVspeed),
    ("view_object", GameVariable::ViewObject),
];

/// Mappings of function names to fn pointers
/// The bool indicates whether the function is constant, ie. it doesn't read or write any internal state.
pub const FUNCTIONS: [(&str, fn(&mut Runtime, &mut Context, &[Value]) -> Value, bool); 1281] = [
    ("display_get_width", Runtime::display_get_width, false),
    ("display_get_height", Runtime::display_get_height, false),
    ("display_get_colordepth", Runtime::display_get_colordepth, false),
    ("display_get_frequency", Runtime::display_get_frequency, false),
    ("display_set_size", Runtime::display_set_size, false),
    ("display_set_colordepth", Runtime::display_set_colordepth, false),
    ("display_set_frequency", Runtime::display_set_frequency, false),
    ("display_set_all", Runtime::display_set_all, false),
    ("display_test_all", Runtime::display_test_all, false),
    ("display_reset", Runtime::display_reset, false),
    ("display_mouse_get_x", Runtime::display_mouse_get_x, false),
    ("display_mouse_get_y", Runtime::display_mouse_get_y, false),
    ("display_mouse_set", Runtime::display_mouse_set, false),
    ("window_set_visible", Runtime::window_set_visible, false),
    ("window_get_visible", Runtime::window_get_visible, false),
    ("window_set_fullscreen", Runtime::window_set_fullscreen, false),
    ("window_get_fullscreen", Runtime::window_get_fullscreen, false),
    ("window_set_showborder", Runtime::window_set_showborder, false),
    ("window_get_showborder", Runtime::window_get_showborder, false),
    ("window_set_showicons", Runtime::window_set_showicons, false),
    ("window_get_showicons", Runtime::window_get_showicons, false),
    ("window_set_stayontop", Runtime::window_set_stayontop, false),
    ("window_get_stayontop", Runtime::window_get_stayontop, false),
    ("window_set_sizeable", Runtime::window_set_sizeable, false),
    ("window_get_sizeable", Runtime::window_get_sizeable, false),
    ("window_set_caption", Runtime::window_set_caption, false),
    ("window_get_caption", Runtime::window_get_caption, false),
    ("window_set_cursor", Runtime::window_set_cursor, false),
    ("window_get_cursor", Runtime::window_get_cursor, false),
    ("window_set_color", Runtime::window_set_color, false),
    ("window_get_color", Runtime::window_get_color, false),
    ("window_set_position", Runtime::window_set_position, false),
    ("window_set_size", Runtime::window_set_size, false),
    ("window_set_rectangle", Runtime::window_set_rectangle, false),
    ("window_center", Runtime::window_center, false),
    ("window_default", Runtime::window_default, false),
    ("window_get_x", Runtime::window_get_x, false),
    ("window_get_y", Runtime::window_get_y, false),
    ("window_get_width", Runtime::window_get_width, false),
    ("window_get_height", Runtime::window_get_height, false),
    ("window_set_region_size", Runtime::window_set_region_size, false),
    ("window_get_region_width", Runtime::window_get_region_width, false),
    ("window_get_region_height", Runtime::window_get_region_height, false),
    ("window_set_region_scale", Runtime::window_set_region_scale, false),
    ("window_get_region_scale", Runtime::window_get_region_scale, false),
    ("window_mouse_get_x", Runtime::window_mouse_get_x, false),
    ("window_mouse_get_y", Runtime::window_mouse_get_y, false),
    ("window_mouse_set", Runtime::window_mouse_set, false),
    ("window_view_mouse_get_x", Runtime::window_view_mouse_get_x, false),
    ("window_view_mouse_get_y", Runtime::window_view_mouse_get_y, false),
    ("window_view_mouse_set", Runtime::window_view_mouse_set, false),
    ("window_views_mouse_get_x", Runtime::window_views_mouse_get_x, false),
    ("window_views_mouse_get_y", Runtime::window_views_mouse_get_y, false),
    ("window_views_mouse_set", Runtime::window_views_mouse_set, false),
    ("set_synchronization", Runtime::set_synchronization, false),
    ("set_automatic_draw", Runtime::set_automatic_draw, false),
    ("screen_redraw", Runtime::screen_redraw, false),
    ("screen_refresh", Runtime::screen_refresh, false),
    ("screen_wait_vsync", Runtime::screen_wait_vsync, false),
    ("screen_save", Runtime::screen_save, false),
    ("screen_save_part", Runtime::screen_save_part, false),
    ("draw_getpixel", Runtime::draw_getpixel, false),
    ("draw_set_color", Runtime::draw_set_color, false),
    ("draw_set_alpha", Runtime::draw_set_alpha, false),
    ("draw_get_color", Runtime::draw_get_color, false),
    ("draw_get_alpha", Runtime::draw_get_alpha, false),
    ("make_color", Runtime::make_color, true),
    ("make_color_rgb", Runtime::make_color_rgb, true),
    ("make_color_hsv", Runtime::make_color_hsv, true),
    ("color_get_red", Runtime::color_get_red, true),
    ("color_get_green", Runtime::color_get_green, true),
    ("color_get_blue", Runtime::color_get_blue, true),
    ("color_get_hue", Runtime::color_get_hue, true),
    ("color_get_saturation", Runtime::color_get_saturation, true),
    ("color_get_value", Runtime::color_get_value, true),
    ("merge_color", Runtime::merge_color, true),
    ("draw_set_blend_mode", Runtime::draw_set_blend_mode, false),
    ("draw_set_blend_mode_ext", Runtime::draw_set_blend_mode_ext, false),
    ("draw_clear", Runtime::draw_clear, false),
    ("draw_clear_alpha", Runtime::draw_clear_alpha, false),
    ("draw_point", Runtime::draw_point, false),
    ("draw_line", Runtime::draw_line, false),
    ("draw_line_width", Runtime::draw_line_width, false),
    ("draw_rectangle", Runtime::draw_rectangle, false),
    ("draw_roundrect", Runtime::draw_roundrect, false),
    ("draw_triangle", Runtime::draw_triangle, false),
    ("draw_circle", Runtime::draw_circle, false),
    ("draw_ellipse", Runtime::draw_ellipse, false),
    ("draw_arrow", Runtime::draw_arrow, false),
    ("draw_button", Runtime::draw_button, false),
    ("draw_healthbar", Runtime::draw_healthbar, false),
    ("draw_path", Runtime::draw_path, false),
    ("draw_point_color", Runtime::draw_point_color, false),
    ("draw_line_color", Runtime::draw_line_color, false),
    ("draw_line_width_color", Runtime::draw_line_width_color, false),
    ("draw_rectangle_color", Runtime::draw_rectangle_color, false),
    ("draw_roundrect_color", Runtime::draw_roundrect_color, false),
    ("draw_triangle_color", Runtime::draw_triangle_color, false),
    ("draw_circle_color", Runtime::draw_circle_color, false),
    ("draw_ellipse_color", Runtime::draw_ellipse_color, false),
    ("draw_set_circle_precision", Runtime::draw_set_circle_precision, false),
    ("draw_primitive_begin", Runtime::draw_primitive_begin, false),
    ("draw_primitive_begin_texture", Runtime::draw_primitive_begin_texture, false),
    ("draw_primitive_end", Runtime::draw_primitive_end, false),
    ("draw_vertex", Runtime::draw_vertex, false),
    ("draw_vertex_color", Runtime::draw_vertex_color, false),
    ("draw_vertex_texture", Runtime::draw_vertex_texture, false),
    ("draw_vertex_texture_color", Runtime::draw_vertex_texture_color, false),
    ("sprite_get_texture", Runtime::sprite_get_texture, false),
    ("background_get_texture", Runtime::background_get_texture, false),
    ("texture_exists", Runtime::texture_exists, false),
    ("texture_set_interpolation", Runtime::texture_set_interpolation, false),
    ("texture_set_blending", Runtime::texture_set_blending, false),
    ("texture_set_repeat", Runtime::texture_set_repeat, false),
    ("texture_get_width", Runtime::texture_get_width, false),
    ("texture_get_height", Runtime::texture_get_height, false),
    ("texture_preload", Runtime::texture_preload, false),
    ("texture_set_priority", Runtime::texture_set_priority, false),
    ("draw_set_font", Runtime::draw_set_font, false),
    ("draw_set_halign", Runtime::draw_set_halign, false),
    ("draw_set_valign", Runtime::draw_set_valign, false),
    ("string_width", Runtime::string_width, true),
    ("string_height", Runtime::string_height, true),
    ("string_width_ext", Runtime::string_width_ext, true),
    ("string_height_ext", Runtime::string_height_ext, true),
    ("draw_text", Runtime::draw_text, false),
    ("draw_text_ext", Runtime::draw_text_ext, false),
    ("draw_text_transformed", Runtime::draw_text_transformed, false),
    ("draw_text_ext_transformed", Runtime::draw_text_ext_transformed, false),
    ("draw_text_color", Runtime::draw_text_color, false),
    ("draw_text_transformed_color", Runtime::draw_text_transformed_color, false),
    ("draw_text_ext_color", Runtime::draw_text_ext_color, false),
    ("draw_text_ext_transformed_color", Runtime::draw_text_ext_transformed_color, false),
    ("draw_self", Runtime::draw_self, false),
    ("draw_sprite", Runtime::draw_sprite, false),
    ("draw_sprite_pos", Runtime::draw_sprite_pos, false),
    ("draw_sprite_ext", Runtime::draw_sprite_ext, false),
    ("draw_sprite_stretched", Runtime::draw_sprite_stretched, false),
    ("draw_sprite_stretched_ext", Runtime::draw_sprite_stretched_ext, false),
    ("draw_sprite_part", Runtime::draw_sprite_part, false),
    ("draw_sprite_part_ext", Runtime::draw_sprite_part_ext, false),
    ("draw_sprite_general", Runtime::draw_sprite_general, false),
    ("draw_sprite_tiled", Runtime::draw_sprite_tiled, false),
    ("draw_sprite_tiled_ext", Runtime::draw_sprite_tiled_ext, false),
    ("draw_background", Runtime::draw_background, false),
    ("draw_background_ext", Runtime::draw_background_ext, false),
    ("draw_background_stretched", Runtime::draw_background_stretched, false),
    ("draw_background_stretched_ext", Runtime::draw_background_stretched_ext, false),
    ("draw_background_part", Runtime::draw_background_part, false),
    ("draw_background_part_ext", Runtime::draw_background_part_ext, false),
    ("draw_background_general", Runtime::draw_background_general, false),
    ("draw_background_tiled", Runtime::draw_background_tiled, false),
    ("draw_background_tiled_ext", Runtime::draw_background_tiled_ext, false),
    ("tile_get_x", Runtime::tile_get_x, false),
    ("tile_get_y", Runtime::tile_get_y, false),
    ("tile_get_left", Runtime::tile_get_left, false),
    ("tile_get_top", Runtime::tile_get_top, false),
    ("tile_get_width", Runtime::tile_get_width, false),
    ("tile_get_height", Runtime::tile_get_height, false),
    ("tile_get_depth", Runtime::tile_get_depth, false),
    ("tile_get_visible", Runtime::tile_get_visible, false),
    ("tile_get_xscale", Runtime::tile_get_xscale, false),
    ("tile_get_yscale", Runtime::tile_get_yscale, false),
    ("tile_get_blend", Runtime::tile_get_blend, false),
    ("tile_get_alpha", Runtime::tile_get_alpha, false),
    ("tile_get_background", Runtime::tile_get_background, false),
    ("tile_set_visible", Runtime::tile_set_visible, false),
    ("tile_set_background", Runtime::tile_set_background, false),
    ("tile_set_region", Runtime::tile_set_region, false),
    ("tile_set_position", Runtime::tile_set_position, false),
    ("tile_set_depth", Runtime::tile_set_depth, false),
    ("tile_set_scale", Runtime::tile_set_scale, false),
    ("tile_set_blend", Runtime::tile_set_blend, false),
    ("tile_set_alpha", Runtime::tile_set_alpha, false),
    ("tile_add", Runtime::tile_add, false),
    ("tile_find", Runtime::tile_find, false),
    ("tile_exists", Runtime::tile_exists, false),
    ("tile_delete", Runtime::tile_delete, false),
    ("tile_delete_at", Runtime::tile_delete_at, false),
    ("tile_layer_hide", Runtime::tile_layer_hide, false),
    ("tile_layer_show", Runtime::tile_layer_show, false),
    ("tile_layer_delete", Runtime::tile_layer_delete, false),
    ("tile_layer_shift", Runtime::tile_layer_shift, false),
    ("tile_layer_find", Runtime::tile_layer_find, false),
    ("tile_layer_delete_at", Runtime::tile_layer_delete_at, false),
    ("tile_layer_depth", Runtime::tile_layer_depth, false),
    ("surface_create", Runtime::surface_create, false),
    ("surface_create_ext", Runtime::surface_create_ext, false),
    ("surface_free", Runtime::surface_free, false),
    ("surface_exists", Runtime::surface_exists, false),
    ("surface_get_width", Runtime::surface_get_width, false),
    ("surface_get_height", Runtime::surface_get_height, false),
    ("surface_get_texture", Runtime::surface_get_texture, false),
    ("surface_set_target", Runtime::surface_set_target, false),
    ("surface_reset_target", Runtime::surface_reset_target, false),
    ("draw_surface", Runtime::draw_surface, false),
    ("draw_surface_ext", Runtime::draw_surface_ext, false),
    ("draw_surface_stretched", Runtime::draw_surface_stretched, false),
    ("draw_surface_stretched_ext", Runtime::draw_surface_stretched_ext, false),
    ("draw_surface_part", Runtime::draw_surface_part, false),
    ("draw_surface_part_ext", Runtime::draw_surface_part_ext, false),
    ("draw_surface_general", Runtime::draw_surface_general, false),
    ("draw_surface_tiled", Runtime::draw_surface_tiled, false),
    ("draw_surface_tiled_ext", Runtime::draw_surface_tiled_ext, false),
    ("surface_save", Runtime::surface_save, false),
    ("surface_save_part", Runtime::surface_save_part, false),
    ("surface_getpixel", Runtime::surface_getpixel, false),
    ("surface_copy", Runtime::surface_copy, false),
    ("surface_copy_part", Runtime::surface_copy_part, false),
    ("action_path_old", Runtime::action_path_old, false),
    ("action_set_sprite", Runtime::action_set_sprite, false),
    ("action_draw_font", Runtime::action_draw_font, false),
    ("action_draw_font_old", Runtime::action_draw_font_old, false),
    ("action_fill_color", Runtime::action_fill_color, false),
    ("action_line_color", Runtime::action_line_color, false),
    ("action_highscore", Runtime::action_highscore, false),
    ("action_move", Runtime::action_move, false),
    ("action_set_motion", Runtime::action_set_motion, false),
    ("action_set_hspeed", Runtime::action_set_hspeed, false),
    ("action_set_vspeed", Runtime::action_set_vspeed, false),
    ("action_set_gravity", Runtime::action_set_gravity, false),
    ("action_set_friction", Runtime::action_set_friction, false),
    ("action_move_point", Runtime::action_move_point, false),
    ("action_move_to", Runtime::action_move_to, false),
    ("action_move_start", Runtime::action_move_start, false),
    ("action_move_random", Runtime::action_move_random, false),
    ("action_snap", Runtime::action_snap, false),
    ("action_wrap", Runtime::action_wrap, false),
    ("action_reverse_xdir", Runtime::action_reverse_xdir, false),
    ("action_reverse_ydir", Runtime::action_reverse_ydir, false),
    ("action_move_contact", Runtime::action_move_contact, false),
    ("action_bounce", Runtime::action_bounce, false),
    ("action_path", Runtime::action_path, false),
    ("action_path_end", Runtime::action_path_end, false),
    ("action_path_position", Runtime::action_path_position, false),
    ("action_path_speed", Runtime::action_path_speed, false),
    ("action_linear_step", Runtime::action_linear_step, false),
    ("action_potential_step", Runtime::action_potential_step, false),
    ("action_kill_object", Runtime::action_kill_object, false),
    ("action_create_object", Runtime::action_create_object, false),
    ("action_create_object_motion", Runtime::action_create_object_motion, false),
    ("action_create_object_random", Runtime::action_create_object_random, false),
    ("action_change_object", Runtime::action_change_object, false),
    ("action_kill_position", Runtime::action_kill_position, false),
    ("action_sprite_set", Runtime::action_sprite_set, false),
    ("action_sprite_transform", Runtime::action_sprite_transform, false),
    ("action_sprite_color", Runtime::action_sprite_color, false),
    ("action_sound", Runtime::action_sound, false),
    ("action_end_sound", Runtime::action_end_sound, false),
    ("action_if_sound", Runtime::action_if_sound, false),
    ("action_another_room", Runtime::action_another_room, false),
    ("action_current_room", Runtime::action_current_room, false),
    ("action_previous_room", Runtime::action_previous_room, false),
    ("action_next_room", Runtime::action_next_room, false),
    ("action_if_previous_room", Runtime::action_if_previous_room, false),
    ("action_if_next_room", Runtime::action_if_next_room, false),
    ("action_set_alarm", Runtime::action_set_alarm, false),
    ("action_sleep", Runtime::action_sleep, false),
    ("action_set_timeline", Runtime::action_set_timeline, false),
    ("action_timeline_set", Runtime::action_timeline_set, false),
    ("action_timeline_start", Runtime::action_timeline_start, false),
    ("action_timeline_pause", Runtime::action_timeline_pause, false),
    ("action_timeline_stop", Runtime::action_timeline_stop, false),
    ("action_set_timeline_position", Runtime::action_set_timeline_position, false),
    ("action_set_timeline_speed", Runtime::action_set_timeline_speed, false),
    ("action_message", Runtime::action_message, false),
    ("action_show_info", Runtime::action_show_info, false),
    ("action_show_video", Runtime::action_show_video, false),
    ("action_splash_video", Runtime::action_splash_video, false),
    ("action_splash_text", Runtime::action_splash_text, false),
    ("action_splash_image", Runtime::action_splash_image, false),
    ("action_splash_web", Runtime::action_splash_web, false),
    ("action_splash_settings", Runtime::action_splash_settings, false),
    ("action_end_game", Runtime::action_end_game, false),
    ("action_restart_game", Runtime::action_restart_game, false),
    ("action_save_game", Runtime::action_save_game, false),
    ("action_load_game", Runtime::action_load_game, false),
    ("action_replace_sprite", Runtime::action_replace_sprite, false),
    ("action_replace_sound", Runtime::action_replace_sound, false),
    ("action_replace_background", Runtime::action_replace_background, false),
    ("action_if_empty", Runtime::action_if_empty, false),
    ("action_if_collision", Runtime::action_if_collision, false),
    ("action_if", Runtime::action_if, false),
    ("action_if_number", Runtime::action_if_number, false),
    ("action_if_object", Runtime::action_if_object, false),
    ("action_if_question", Runtime::action_if_question, false),
    ("action_if_dice", Runtime::action_if_dice, false),
    ("action_if_mouse", Runtime::action_if_mouse, false),
    ("action_if_aligned", Runtime::action_if_aligned, false),
    ("action_execute_script", Runtime::action_execute_script, false),
    ("action_inherited", Runtime::action_inherited, false),
    ("action_if_variable", Runtime::action_if_variable, false),
    ("action_draw_variable", Runtime::action_draw_variable, false),
    ("action_set_score", Runtime::action_set_score, false),
    ("action_if_score", Runtime::action_if_score, false),
    ("action_draw_score", Runtime::action_draw_score, false),
    ("action_highscore_show", Runtime::action_highscore_show, false),
    ("action_highscore_clear", Runtime::action_highscore_clear, false),
    ("action_set_life", Runtime::action_set_life, false),
    ("action_if_life", Runtime::action_if_life, false),
    ("action_draw_life", Runtime::action_draw_life, false),
    ("action_draw_life_images", Runtime::action_draw_life_images, false),
    ("action_set_health", Runtime::action_set_health, false),
    ("action_if_health", Runtime::action_if_health, false),
    ("action_draw_health", Runtime::action_draw_health, false),
    ("action_set_caption", Runtime::action_set_caption, false),
    ("action_partsyst_create", Runtime::action_partsyst_create, false),
    ("action_partsyst_destroy", Runtime::action_partsyst_destroy, false),
    ("action_partsyst_clear", Runtime::action_partsyst_clear, false),
    ("action_parttype_create_old", Runtime::action_parttype_create_old, false),
    ("action_parttype_create", Runtime::action_parttype_create, false),
    ("action_parttype_color", Runtime::action_parttype_color, false),
    ("action_parttype_life", Runtime::action_parttype_life, false),
    ("action_parttype_speed", Runtime::action_parttype_speed, false),
    ("action_parttype_gravity", Runtime::action_parttype_gravity, false),
    ("action_parttype_secondary", Runtime::action_parttype_secondary, false),
    ("action_partemit_create", Runtime::action_partemit_create, false),
    ("action_partemit_destroy", Runtime::action_partemit_destroy, false),
    ("action_partemit_burst", Runtime::action_partemit_burst, false),
    ("action_partemit_stream", Runtime::action_partemit_stream, false),
    ("action_cd_play", Runtime::action_cd_play, false),
    ("action_cd_stop", Runtime::action_cd_stop, false),
    ("action_cd_pause", Runtime::action_cd_pause, false),
    ("action_cd_resume", Runtime::action_cd_resume, false),
    ("action_cd_present", Runtime::action_cd_present, false),
    ("action_cd_playing", Runtime::action_cd_playing, false),
    ("action_set_cursor", Runtime::action_set_cursor, false),
    ("action_webpage", Runtime::action_webpage, false),
    ("action_draw_sprite", Runtime::action_draw_sprite, false),
    ("action_draw_background", Runtime::action_draw_background, false),
    ("action_draw_text", Runtime::action_draw_text, false),
    ("action_draw_text_transformed", Runtime::action_draw_text_transformed, false),
    ("action_draw_rectangle", Runtime::action_draw_rectangle, false),
    ("action_draw_gradient_hor", Runtime::action_draw_gradient_hor, false),
    ("action_draw_gradient_vert", Runtime::action_draw_gradient_vert, false),
    ("action_draw_ellipse", Runtime::action_draw_ellipse, false),
    ("action_draw_ellipse_gradient", Runtime::action_draw_ellipse_gradient, false),
    ("action_draw_line", Runtime::action_draw_line, false),
    ("action_draw_arrow", Runtime::action_draw_arrow, false),
    ("action_color", Runtime::action_color, false),
    ("action_font", Runtime::action_font, false),
    ("action_fullscreen", Runtime::action_fullscreen, false),
    ("action_snapshot", Runtime::action_snapshot, false),
    ("action_effect", Runtime::action_effect, false),
    ("is_real", Runtime::is_real, true),
    ("is_string", Runtime::is_string, true),
    ("random", Runtime::random, false),
    ("random_range", Runtime::random_range, false),
    ("irandom", Runtime::irandom, false),
    ("irandom_range", Runtime::irandom_range, false),
    ("random_set_seed", Runtime::random_set_seed, false),
    ("random_get_seed", Runtime::random_get_seed, false),
    ("randomize", Runtime::randomize, false),
    ("abs", Runtime::abs, true),
    ("round", Runtime::round, true),
    ("floor", Runtime::floor, true),
    ("ceil", Runtime::ceil, true),
    ("sign", Runtime::sign, true),
    ("frac", Runtime::frac, true),
    ("sqrt", Runtime::sqrt, true),
    ("sqr", Runtime::sqr, true),
    ("exp", Runtime::exp, true),
    ("ln", Runtime::ln, true),
    ("log2", Runtime::log2, true),
    ("log10", Runtime::log10, true),
    ("sin", Runtime::sin, true),
    ("cos", Runtime::cos, true),
    ("tan", Runtime::tan, true),
    ("arcsin", Runtime::arcsin, true),
    ("arccos", Runtime::arccos, true),
    ("arctan", Runtime::arctan, true),
    ("arctan2", Runtime::arctan2, true),
    ("degtorad", Runtime::degtorad, true),
    ("radtodeg", Runtime::radtodeg, true),
    ("power", Runtime::power, true),
    ("logn", Runtime::logn, true),
    ("min", Runtime::min, true),
    ("max", Runtime::max, true),
    ("min3", Runtime::min3, true),
    ("max3", Runtime::max3, true),
    ("mean", Runtime::mean, true),
    ("median", Runtime::median, true),
    ("choose", Runtime::choose, false),
    ("clamp", Runtime::clamp, true),
    ("lerp", Runtime::lerp, true),
    ("real", Runtime::real, true),
    ("string", Runtime::string, true),
    ("string_format", Runtime::string_format, true),
    ("chr", Runtime::chr, true),
    ("ansi_char", Runtime::ansi_char, true),
    ("ord", Runtime::ord, true),
    ("string_length", Runtime::string_length, true),
    ("string_byte_length", Runtime::string_byte_length, true),
    ("string_byte_at", Runtime::string_byte_at, true),
    ("string_pos", Runtime::string_pos, true),
    ("string_copy", Runtime::string_copy, true),
    ("string_char_at", Runtime::string_char_at, true),
    ("string_delete", Runtime::string_delete, true),
    ("string_insert", Runtime::string_insert, true),
    ("string_lower", Runtime::string_lower, true),
    ("string_upper", Runtime::string_upper, true),
    ("string_repeat", Runtime::string_repeat, true),
    ("string_letters", Runtime::string_letters, true),
    ("string_digits", Runtime::string_digits, true),
    ("string_lettersdigits", Runtime::string_lettersdigits, true),
    ("string_replace", Runtime::string_replace, true),
    ("string_replace_all", Runtime::string_replace_all, true),
    ("string_count", Runtime::string_count, true),
    ("dot_product", Runtime::dot_product, true),
    ("dot_product_3d", Runtime::dot_product_3d, true),
    ("point_distance_3d", Runtime::point_distance_3d, true),
    ("point_distance", Runtime::point_distance, true),
    ("point_direction", Runtime::point_direction, true),
    ("lengthdir_x", Runtime::lengthdir_x, true),
    ("lengthdir_y", Runtime::lengthdir_y, true),
    ("move_random", Runtime::move_random, false),
    ("place_free", Runtime::place_free, false),
    ("place_empty", Runtime::place_empty, false),
    ("place_meeting", Runtime::place_meeting, false),
    ("place_snapped", Runtime::place_snapped, false),
    ("move_snap", Runtime::move_snap, false),
    ("move_towards_point", Runtime::move_towards_point, false),
    ("move_contact", Runtime::move_contact, false),
    ("move_contact_solid", Runtime::move_contact_solid, false),
    ("move_contact_all", Runtime::move_contact_all, false),
    ("move_outside_solid", Runtime::move_outside_solid, false),
    ("move_outside_all", Runtime::move_outside_all, false),
    ("move_bounce", Runtime::move_bounce, false),
    ("move_bounce_solid", Runtime::move_bounce_solid, false),
    ("move_bounce_all", Runtime::move_bounce_all, false),
    ("move_wrap", Runtime::move_wrap, false),
    ("motion_set", Runtime::motion_set, false),
    ("motion_add", Runtime::motion_add, false),
    ("distance_to_point", Runtime::distance_to_point, false),
    ("distance_to_object", Runtime::distance_to_object, false),
    ("path_start", Runtime::path_start, false),
    ("path_end", Runtime::path_end, false),
    ("mp_linear_step", Runtime::mp_linear_step, false),
    ("mp_linear_path", Runtime::mp_linear_path, false),
    ("mp_linear_step_object", Runtime::mp_linear_step_object, false),
    ("mp_linear_path_object", Runtime::mp_linear_path_object, false),
    ("mp_potential_settings", Runtime::mp_potential_settings, false),
    ("mp_potential_step", Runtime::mp_potential_step, false),
    ("mp_potential_path", Runtime::mp_potential_path, false),
    ("mp_potential_step_object", Runtime::mp_potential_step_object, false),
    ("mp_potential_path_object", Runtime::mp_potential_path_object, false),
    ("mp_grid_create", Runtime::mp_grid_create, false),
    ("mp_grid_destroy", Runtime::mp_grid_destroy, false),
    ("mp_grid_clear_all", Runtime::mp_grid_clear_all, false),
    ("mp_grid_clear_cell", Runtime::mp_grid_clear_cell, false),
    ("mp_grid_clear_rectangle", Runtime::mp_grid_clear_rectangle, false),
    ("mp_grid_add_cell", Runtime::mp_grid_add_cell, false),
    ("mp_grid_add_rectangle", Runtime::mp_grid_add_rectangle, false),
    ("mp_grid_add_instances", Runtime::mp_grid_add_instances, false),
    ("mp_grid_path", Runtime::mp_grid_path, false),
    ("mp_grid_draw", Runtime::mp_grid_draw, false),
    ("collision_point", Runtime::collision_point, false),
    ("collision_rectangle", Runtime::collision_rectangle, false),
    ("collision_circle", Runtime::collision_circle, false),
    ("collision_ellipse", Runtime::collision_ellipse, false),
    ("collision_line", Runtime::collision_line, false),
    ("instance_find", Runtime::instance_find, false),
    ("instance_exists", Runtime::instance_exists, false),
    ("instance_number", Runtime::instance_number, false),
    ("instance_position", Runtime::instance_position, false),
    ("instance_nearest", Runtime::instance_nearest, false),
    ("instance_furthest", Runtime::instance_furthest, false),
    ("instance_place", Runtime::instance_place, false),
    ("instance_create", Runtime::instance_create, false),
    ("instance_copy", Runtime::instance_copy, false),
    ("instance_change", Runtime::instance_change, false),
    ("instance_destroy", Runtime::instance_destroy, false),
    ("instance_sprite", Runtime::instance_sprite, false),
    ("position_empty", Runtime::position_empty, false),
    ("position_meeting", Runtime::position_meeting, false),
    ("position_destroy", Runtime::position_destroy, false),
    ("position_change", Runtime::position_change, false),
    ("instance_deactivate_all", Runtime::instance_deactivate_all, false),
    ("instance_deactivate_object", Runtime::instance_deactivate_object, false),
    ("instance_deactivate_region", Runtime::instance_deactivate_region, false),
    ("instance_activate_all", Runtime::instance_activate_all, false),
    ("instance_activate_object", Runtime::instance_activate_object, false),
    ("instance_activate_region", Runtime::instance_activate_region, false),
    ("room_goto", Runtime::room_goto, false),
    ("room_goto_previous", Runtime::room_goto_previous, false),
    ("room_goto_next", Runtime::room_goto_next, false),
    ("room_previous", Runtime::room_previous, false),
    ("room_next", Runtime::room_next, false),
    ("room_restart", Runtime::room_restart, false),
    ("game_end", Runtime::game_end, false),
    ("game_restart", Runtime::game_restart, false),
    ("game_load", Runtime::game_load, false),
    ("game_save", Runtime::game_save, false),
    ("transition_define", Runtime::transition_define, false),
    ("transition_exists", Runtime::transition_exists, false),
    ("sleep", Runtime::sleep, false),
    ("YoYo_GetPlatform", Runtime::yoyo_getplatform, false),
    ("YoYo_GetDevice", Runtime::yoyo_getdevice, false),
    ("YoYo_OpenURL", Runtime::yoyo_openurl, false),
    ("YoYo_OpenURL_ext", Runtime::yoyo_openurl_ext, false),
    ("YoYo_OpenURL_full", Runtime::yoyo_openurl_full, false),
    ("YoYo_GetDomain", Runtime::yoyo_getdomain, false),
    ("YoYo_GetTimer", Runtime::yoyo_gettimer, false),
    ("YoYo_AddVirtualKey", Runtime::yoyo_addvirtualkey, false),
    ("YoYo_DeleteVirtualKey", Runtime::yoyo_deletevirtualkey, false),
    ("YoYo_ShowVirtualKey", Runtime::yoyo_showvirtualkey, false),
    ("YoYo_HideVirtualKey", Runtime::yoyo_hidevirtualkey, false),
    ("YoYo_EnableAlphaBlend", Runtime::yoyo_enablealphablend, false),
    ("file_bin_open", Runtime::file_bin_open, false),
    ("file_bin_rewrite", Runtime::file_bin_rewrite, false),
    ("file_bin_close", Runtime::file_bin_close, false),
    ("file_bin_position", Runtime::file_bin_position, false),
    ("file_bin_size", Runtime::file_bin_size, false),
    ("file_bin_seek", Runtime::file_bin_seek, false),
    ("file_bin_read_byte", Runtime::file_bin_read_byte, false),
    ("file_bin_write_byte", Runtime::file_bin_write_byte, false),
    ("file_text_open_read", Runtime::file_text_open_read, false),
    ("file_text_open_write", Runtime::file_text_open_write, false),
    ("file_text_open_append", Runtime::file_text_open_append, false),
    ("file_text_close", Runtime::file_text_close, false),
    ("file_text_read_string", Runtime::file_text_read_string, false),
    ("file_text_read_real", Runtime::file_text_read_real, false),
    ("file_text_readln", Runtime::file_text_readln, false),
    ("file_text_eof", Runtime::file_text_eof, false),
    ("file_text_eoln", Runtime::file_text_eoln, false),
    ("file_text_write_string", Runtime::file_text_write_string, false),
    ("file_text_write_real", Runtime::file_text_write_real, false),
    ("file_text_writeln", Runtime::file_text_writeln, false),
    ("file_open_read", Runtime::file_open_read, false),
    ("file_open_write", Runtime::file_open_write, false),
    ("file_open_append", Runtime::file_open_append, false),
    ("file_close", Runtime::file_close, false),
    ("file_read_string", Runtime::file_read_string, false),
    ("file_read_real", Runtime::file_read_real, false),
    ("file_readln", Runtime::file_readln, false),
    ("file_eof", Runtime::file_eof, false),
    ("file_eoln", Runtime::file_eoln, false),
    ("file_write_string", Runtime::file_write_string, false),
    ("file_write_real", Runtime::file_write_real, false),
    ("file_writeln", Runtime::file_writeln, false),
    ("file_exists", Runtime::file_exists, false),
    ("file_delete", Runtime::file_delete, false),
    ("file_rename", Runtime::file_rename, false),
    ("file_copy", Runtime::file_copy, false),
    ("directory_exists", Runtime::directory_exists, false),
    ("directory_create", Runtime::directory_create, false),
    ("file_find_first", Runtime::file_find_first, false),
    ("file_find_next", Runtime::file_find_next, false),
    ("file_find_close", Runtime::file_find_close, false),
    ("file_attributes", Runtime::file_attributes, false),
    ("filename_name", Runtime::filename_name, false),
    ("filename_path", Runtime::filename_path, false),
    ("filename_dir", Runtime::filename_dir, false),
    ("filename_drive", Runtime::filename_drive, false),
    ("filename_ext", Runtime::filename_ext, false),
    ("filename_change_ext", Runtime::filename_change_ext, false),
    ("export_include_file", Runtime::export_include_file, false),
    ("export_include_file_location", Runtime::export_include_file_location, false),
    ("discard_include_file", Runtime::discard_include_file, false),
    ("execute_program", Runtime::execute_program, false),
    ("execute_shell", Runtime::execute_shell, false),
    ("parameter_count", Runtime::parameter_count, false),
    ("parameter_string", Runtime::parameter_string, false),
    ("environment_get_variable", Runtime::environment_get_variable, false),
    ("registry_write_string", Runtime::registry_write_string, false),
    ("registry_write_real", Runtime::registry_write_real, false),
    ("registry_read_string", Runtime::registry_read_string, false),
    ("registry_read_real", Runtime::registry_read_real, false),
    ("registry_exists", Runtime::registry_exists, false),
    ("registry_write_string_ext", Runtime::registry_write_string_ext, false),
    ("registry_write_real_ext", Runtime::registry_write_real_ext, false),
    ("registry_read_string_ext", Runtime::registry_read_string_ext, false),
    ("registry_read_real_ext", Runtime::registry_read_real_ext, false),
    ("registry_exists_ext", Runtime::registry_exists_ext, false),
    ("registry_set_root", Runtime::registry_set_root, false),
    ("ini_open", Runtime::ini_open, false),
    ("ini_close", Runtime::ini_close, false),
    ("ini_read_string", Runtime::ini_read_string, false),
    ("ini_read_real", Runtime::ini_read_real, false),
    ("ini_write_string", Runtime::ini_write_string, false),
    ("ini_write_real", Runtime::ini_write_real, false),
    ("ini_key_exists", Runtime::ini_key_exists, false),
    ("ini_section_exists", Runtime::ini_section_exists, false),
    ("ini_key_delete", Runtime::ini_key_delete, false),
    ("ini_section_delete", Runtime::ini_section_delete, false),
    ("disk_free", Runtime::disk_free, false),
    ("disk_size", Runtime::disk_size, false),
    ("splash_set_caption", Runtime::splash_set_caption, false),
    ("splash_set_fullscreen", Runtime::splash_set_fullscreen, false),
    ("splash_set_border", Runtime::splash_set_border, false),
    ("splash_set_size", Runtime::splash_set_size, false),
    ("splash_set_position", Runtime::splash_set_position, false),
    ("splash_set_adapt", Runtime::splash_set_adapt, false),
    ("splash_set_top", Runtime::splash_set_top, false),
    ("splash_set_color", Runtime::splash_set_color, false),
    ("splash_set_main", Runtime::splash_set_main, false),
    ("splash_set_scale", Runtime::splash_set_scale, false),
    ("splash_set_cursor", Runtime::splash_set_cursor, false),
    ("splash_set_interrupt", Runtime::splash_set_interrupt, false),
    ("splash_set_stop_key", Runtime::splash_set_stop_key, false),
    ("splash_set_close_button", Runtime::splash_set_close_button, false),
    ("splash_set_stop_mouse", Runtime::splash_set_stop_mouse, false),
    ("splash_show_video", Runtime::splash_show_video, false),
    ("splash_show_image", Runtime::splash_show_image, false),
    ("splash_show_text", Runtime::splash_show_text, false),
    ("splash_show_web", Runtime::splash_show_web, false),
    ("show_image", Runtime::show_image, false),
    ("show_video", Runtime::show_video, false),
    ("show_text", Runtime::show_text, false),
    ("show_message", Runtime::show_message, false),
    ("show_question", Runtime::show_question, false),
    ("show_error", Runtime::show_error, false),
    ("show_info", Runtime::show_info, false),
    ("load_info", Runtime::load_info, false),
    ("highscore_show", Runtime::highscore_show, false),
    ("highscore_set_background", Runtime::highscore_set_background, false),
    ("highscore_set_border", Runtime::highscore_set_border, false),
    ("highscore_set_font", Runtime::highscore_set_font, false),
    ("highscore_set_strings", Runtime::highscore_set_strings, false),
    ("highscore_set_colors", Runtime::highscore_set_colors, false),
    ("highscore_show_ext", Runtime::highscore_show_ext, false),
    ("highscore_clear", Runtime::highscore_clear, false),
    ("highscore_add", Runtime::highscore_add, false),
    ("highscore_add_current", Runtime::highscore_add_current, false),
    ("highscore_value", Runtime::highscore_value, false),
    ("highscore_name", Runtime::highscore_name, false),
    ("draw_highscore", Runtime::draw_highscore, false),
    ("show_message_ext", Runtime::show_message_ext, false),
    ("message_background", Runtime::message_background, false),
    ("message_button", Runtime::message_button, false),
    ("message_alpha", Runtime::message_alpha, false),
    ("message_text_font", Runtime::message_text_font, false),
    ("message_button_font", Runtime::message_button_font, false),
    ("message_input_font", Runtime::message_input_font, false),
    ("message_text_charset", Runtime::message_text_charset, false),
    ("message_mouse_color", Runtime::message_mouse_color, false),
    ("message_input_color", Runtime::message_input_color, false),
    ("message_position", Runtime::message_position, false),
    ("message_size", Runtime::message_size, false),
    ("message_caption", Runtime::message_caption, false),
    ("show_menu", Runtime::show_menu, false),
    ("show_menu_pos", Runtime::show_menu_pos, false),
    ("get_integer", Runtime::get_integer, false),
    ("get_string", Runtime::get_string, false),
    ("get_color", Runtime::get_color, false),
    ("get_open_filename", Runtime::get_open_filename, false),
    ("get_save_filename", Runtime::get_save_filename, false),
    ("get_directory", Runtime::get_directory, false),
    ("get_directory_alt", Runtime::get_directory_alt, false),
    ("keyboard_get_numlock", Runtime::keyboard_get_numlock, false),
    ("keyboard_set_numlock", Runtime::keyboard_set_numlock, false),
    ("keyboard_key_press", Runtime::keyboard_key_press, false),
    ("keyboard_key_release", Runtime::keyboard_key_release, false),
    ("keyboard_set_map", Runtime::keyboard_set_map, false),
    ("keyboard_get_map", Runtime::keyboard_get_map, false),
    ("keyboard_unset_map", Runtime::keyboard_unset_map, false),
    ("keyboard_check", Runtime::keyboard_check, false),
    ("keyboard_check_pressed", Runtime::keyboard_check_pressed, false),
    ("keyboard_check_released", Runtime::keyboard_check_released, false),
    ("keyboard_check_direct", Runtime::keyboard_check_direct, false),
    ("mouse_check_button", Runtime::mouse_check_button, false),
    ("mouse_check_button_pressed", Runtime::mouse_check_button_pressed, false),
    ("mouse_check_button_released", Runtime::mouse_check_button_released, false),
    ("mouse_wheel_up", Runtime::mouse_wheel_up, false),
    ("mouse_wheel_down", Runtime::mouse_wheel_down, false),
    ("joystick_exists", Runtime::joystick_exists, false),
    ("joystick_direction", Runtime::joystick_direction, false),
    ("joystick_name", Runtime::joystick_name, false),
    ("joystick_axes", Runtime::joystick_axes, false),
    ("joystick_buttons", Runtime::joystick_buttons, false),
    ("joystick_has_pov", Runtime::joystick_has_pov, false),
    ("joystick_check_button", Runtime::joystick_check_button, false),
    ("joystick_xpos", Runtime::joystick_xpos, false),
    ("joystick_ypos", Runtime::joystick_ypos, false),
    ("joystick_zpos", Runtime::joystick_zpos, false),
    ("joystick_rpos", Runtime::joystick_rpos, false),
    ("joystick_upos", Runtime::joystick_upos, false),
    ("joystick_vpos", Runtime::joystick_vpos, false),
    ("joystick_pov", Runtime::joystick_pov, false),
    ("keyboard_clear", Runtime::keyboard_clear, false),
    ("mouse_clear", Runtime::mouse_clear, false),
    ("io_clear", Runtime::io_clear, false),
    ("io_handle", Runtime::io_handle, false),
    ("keyboard_wait", Runtime::keyboard_wait, false),
    ("mouse_wait", Runtime::mouse_wait, false),
    ("mplay_init_ipx", Runtime::mplay_init_ipx, false),
    ("mplay_init_tcpip", Runtime::mplay_init_tcpip, false),
    ("mplay_init_modem", Runtime::mplay_init_modem, false),
    ("mplay_init_serial", Runtime::mplay_init_serial, false),
    ("mplay_connect_status", Runtime::mplay_connect_status, false),
    ("mplay_end", Runtime::mplay_end, false),
    ("mplay_session_mode", Runtime::mplay_session_mode, false),
    ("mplay_session_create", Runtime::mplay_session_create, false),
    ("mplay_session_find", Runtime::mplay_session_find, false),
    ("mplay_session_name", Runtime::mplay_session_name, false),
    ("mplay_session_join", Runtime::mplay_session_join, false),
    ("mplay_session_status", Runtime::mplay_session_status, false),
    ("mplay_session_end", Runtime::mplay_session_end, false),
    ("mplay_player_find", Runtime::mplay_player_find, false),
    ("mplay_player_name", Runtime::mplay_player_name, false),
    ("mplay_player_id", Runtime::mplay_player_id, false),
    ("mplay_data_write", Runtime::mplay_data_write, false),
    ("mplay_data_read", Runtime::mplay_data_read, false),
    ("mplay_data_mode", Runtime::mplay_data_mode, false),
    ("mplay_message_send", Runtime::mplay_message_send, false),
    ("mplay_message_send_guaranteed", Runtime::mplay_message_send_guaranteed, false),
    ("mplay_message_receive", Runtime::mplay_message_receive, false),
    ("mplay_message_id", Runtime::mplay_message_id, false),
    ("mplay_message_value", Runtime::mplay_message_value, false),
    ("mplay_message_player", Runtime::mplay_message_player, false),
    ("mplay_message_name", Runtime::mplay_message_name, false),
    ("mplay_message_count", Runtime::mplay_message_count, false),
    ("mplay_message_clear", Runtime::mplay_message_clear, false),
    ("mplay_ipaddress", Runtime::mplay_ipaddress, false),
    ("event_inherited", Runtime::event_inherited, false),
    ("event_perform", Runtime::event_perform, false),
    ("event_user", Runtime::event_user, false),
    ("event_perform_object", Runtime::event_perform_object, false),
    ("external_define", Runtime::external_define, false),
    ("external_call", Runtime::external_call, false),
    ("external_free", Runtime::external_free, false),
    ("get_function_address", Runtime::get_function_address, true),
    ("external_define0", Runtime::external_define0, false),
    ("external_call0", Runtime::external_call0, false),
    ("external_define1", Runtime::external_define1, false),
    ("external_call1", Runtime::external_call1, false),
    ("external_define2", Runtime::external_define2, false),
    ("external_call2", Runtime::external_call2, false),
    ("external_define3", Runtime::external_define3, false),
    ("external_call3", Runtime::external_call3, false),
    ("external_define4", Runtime::external_define4, false),
    ("external_call4", Runtime::external_call4, false),
    ("external_define5", Runtime::external_define5, false),
    ("external_call5", Runtime::external_call5, false),
    ("external_define6", Runtime::external_define6, false),
    ("external_call6", Runtime::external_call6, false),
    ("external_define7", Runtime::external_define7, false),
    ("external_call7", Runtime::external_call7, false),
    ("external_define8", Runtime::external_define8, false),
    ("external_call8", Runtime::external_call8, false),
    ("execute_string", Runtime::execute_string, false),
    ("execute_file", Runtime::execute_file, false),
    ("window_handle", Runtime::window_handle, false),
    ("show_debug_message", Runtime::show_debug_message, false),
    ("set_program_priority", Runtime::set_program_priority, false),
    ("set_application_title", Runtime::set_application_title, false),
    ("variable_global_exists", Runtime::variable_global_exists, false),
    ("variable_global_get", Runtime::variable_global_get, false),
    ("variable_global_array_get", Runtime::variable_global_array_get, false),
    ("variable_global_array2_get", Runtime::variable_global_array2_get, false),
    ("variable_global_set", Runtime::variable_global_set, false),
    ("variable_global_array_set", Runtime::variable_global_array_set, false),
    ("variable_global_array2_set", Runtime::variable_global_array2_set, false),
    ("variable_local_exists", Runtime::variable_local_exists, false),
    ("variable_local_get", Runtime::variable_local_get, false),
    ("variable_local_array_get", Runtime::variable_local_array_get, false),
    ("variable_local_array2_get", Runtime::variable_local_array2_get, false),
    ("variable_local_set", Runtime::variable_local_set, false),
    ("variable_local_array_set", Runtime::variable_local_array_set, false),
    ("variable_local_array2_set", Runtime::variable_local_array2_set, false),
    ("clipboard_has_text", Runtime::clipboard_has_text, false),
    ("clipboard_set_text", Runtime::clipboard_set_text, false),
    ("clipboard_get_text", Runtime::clipboard_get_text, false),
    ("date_current_datetime", Runtime::date_current_datetime, false),
    ("date_current_date", Runtime::date_current_date, false),
    ("date_current_time", Runtime::date_current_time, false),
    ("date_create_datetime", Runtime::date_create_datetime, false),
    ("date_create_date", Runtime::date_create_date, false),
    ("date_create_time", Runtime::date_create_time, false),
    ("date_valid_datetime", Runtime::date_valid_datetime, false),
    ("date_valid_date", Runtime::date_valid_date, false),
    ("date_valid_time", Runtime::date_valid_time, false),
    ("date_inc_year", Runtime::date_inc_year, false),
    ("date_inc_month", Runtime::date_inc_month, false),
    ("date_inc_week", Runtime::date_inc_week, false),
    ("date_inc_day", Runtime::date_inc_day, false),
    ("date_inc_hour", Runtime::date_inc_hour, false),
    ("date_inc_minute", Runtime::date_inc_minute, false),
    ("date_inc_second", Runtime::date_inc_second, false),
    ("date_get_year", Runtime::date_get_year, false),
    ("date_get_month", Runtime::date_get_month, false),
    ("date_get_week", Runtime::date_get_week, false),
    ("date_get_day", Runtime::date_get_day, false),
    ("date_get_hour", Runtime::date_get_hour, false),
    ("date_get_minute", Runtime::date_get_minute, false),
    ("date_get_second", Runtime::date_get_second, false),
    ("date_get_weekday", Runtime::date_get_weekday, false),
    ("date_get_day_of_year", Runtime::date_get_day_of_year, false),
    ("date_get_hour_of_year", Runtime::date_get_hour_of_year, false),
    ("date_get_minute_of_year", Runtime::date_get_minute_of_year, false),
    ("date_get_second_of_year", Runtime::date_get_second_of_year, false),
    ("date_year_span", Runtime::date_year_span, false),
    ("date_month_span", Runtime::date_month_span, false),
    ("date_week_span", Runtime::date_week_span, false),
    ("date_day_span", Runtime::date_day_span, false),
    ("date_hour_span", Runtime::date_hour_span, false),
    ("date_minute_span", Runtime::date_minute_span, false),
    ("date_second_span", Runtime::date_second_span, false),
    ("date_compare_datetime", Runtime::date_compare_datetime, false),
    ("date_compare_date", Runtime::date_compare_date, false),
    ("date_compare_time", Runtime::date_compare_time, false),
    ("date_date_of", Runtime::date_date_of, false),
    ("date_time_of", Runtime::date_time_of, false),
    ("date_datetime_string", Runtime::date_datetime_string, false),
    ("date_date_string", Runtime::date_date_string, false),
    ("date_time_string", Runtime::date_time_string, false),
    ("date_days_in_month", Runtime::date_days_in_month, false),
    ("date_days_in_year", Runtime::date_days_in_year, false),
    ("date_leap_year", Runtime::date_leap_year, false),
    ("date_is_today", Runtime::date_is_today, false),
    ("sprite_name", Runtime::sprite_name, false),
    ("sprite_exists", Runtime::sprite_exists, false),
    ("sprite_get_name", Runtime::sprite_get_name, false),
    ("sprite_get_number", Runtime::sprite_get_number, false),
    ("sprite_get_width", Runtime::sprite_get_width, false),
    ("sprite_get_height", Runtime::sprite_get_height, false),
    ("sprite_get_xoffset", Runtime::sprite_get_xoffset, false),
    ("sprite_get_yoffset", Runtime::sprite_get_yoffset, false),
    ("sprite_get_bbox_left", Runtime::sprite_get_bbox_left, false),
    ("sprite_get_bbox_right", Runtime::sprite_get_bbox_right, false),
    ("sprite_get_bbox_top", Runtime::sprite_get_bbox_top, false),
    ("sprite_get_bbox_bottom", Runtime::sprite_get_bbox_bottom, false),
    ("sprite_set_offset", Runtime::sprite_set_offset, false),
    ("sprite_set_alpha_from_sprite", Runtime::sprite_set_alpha_from_sprite, false),
    ("sprite_create_from_screen", Runtime::sprite_create_from_screen, false),
    ("sprite_add_from_screen", Runtime::sprite_add_from_screen, false),
    ("sprite_create_from_surface", Runtime::sprite_create_from_surface, false),
    ("sprite_add_from_surface", Runtime::sprite_add_from_surface, false),
    ("sprite_add", Runtime::sprite_add, false),
    ("sprite_replace", Runtime::sprite_replace, false),
    ("sprite_add_sprite", Runtime::sprite_add_sprite, false),
    ("sprite_replace_sprite", Runtime::sprite_replace_sprite, false),
    ("sprite_delete", Runtime::sprite_delete, false),
    ("sprite_duplicate", Runtime::sprite_duplicate, false),
    ("sprite_assign", Runtime::sprite_assign, false),
    ("sprite_merge", Runtime::sprite_merge, false),
    ("sprite_save", Runtime::sprite_save, false),
    ("sprite_save_strip", Runtime::sprite_save_strip, false),
    ("sprite_collision_mask", Runtime::sprite_collision_mask, false),
    ("sprite_set_cache_size", Runtime::sprite_set_cache_size, false),
    ("sprite_set_cache_size_ext", Runtime::sprite_set_cache_size_ext, false),
    ("background_name", Runtime::background_name, false),
    ("background_exists", Runtime::background_exists, false),
    ("background_get_name", Runtime::background_get_name, false),
    ("background_get_width", Runtime::background_get_width, false),
    ("background_get_height", Runtime::background_get_height, false),
    ("background_set_alpha_from_background", Runtime::background_set_alpha_from_background, false),
    ("background_create_from_screen", Runtime::background_create_from_screen, false),
    ("background_create_from_surface", Runtime::background_create_from_surface, false),
    ("background_create_color", Runtime::background_create_color, false),
    ("background_create_gradient", Runtime::background_create_gradient, false),
    ("background_add", Runtime::background_add, false),
    ("background_replace", Runtime::background_replace, false),
    ("background_add_background", Runtime::background_add_background, false),
    ("background_replace_background", Runtime::background_replace_background, false),
    ("background_delete", Runtime::background_delete, false),
    ("background_duplicate", Runtime::background_duplicate, false),
    ("background_assign", Runtime::background_assign, false),
    ("background_save", Runtime::background_save, false),
    ("sound_name", Runtime::sound_name, false),
    ("sound_exists", Runtime::sound_exists, false),
    ("sound_get_name", Runtime::sound_get_name, false),
    ("sound_get_kind", Runtime::sound_get_kind, false),
    ("sound_get_preload", Runtime::sound_get_preload, false),
    ("sound_discard", Runtime::sound_discard, false),
    ("sound_restore", Runtime::sound_restore, false),
    ("sound_add", Runtime::sound_add, false),
    ("sound_replace", Runtime::sound_replace, false),
    ("sound_delete", Runtime::sound_delete, false),
    ("font_name", Runtime::font_name, false),
    ("font_exists", Runtime::font_exists, false),
    ("font_get_name", Runtime::font_get_name, false),
    ("font_get_fontname", Runtime::font_get_fontname, false),
    ("font_get_size", Runtime::font_get_size, false),
    ("font_get_bold", Runtime::font_get_bold, false),
    ("font_get_italic", Runtime::font_get_italic, false),
    ("font_get_first", Runtime::font_get_first, false),
    ("font_get_last", Runtime::font_get_last, false),
    ("font_add", Runtime::font_add, false),
    ("font_replace", Runtime::font_replace, false),
    ("font_add_sprite", Runtime::font_add_sprite, false),
    ("font_replace_sprite", Runtime::font_replace_sprite, false),
    ("font_delete", Runtime::font_delete, false),
    ("script_name", Runtime::script_name, false),
    ("script_exists", Runtime::script_exists, false),
    ("script_get_name", Runtime::script_get_name, false),
    ("script_get_text", Runtime::script_get_text, false),
    ("script_execute", Runtime::script_execute, false),
    ("path_name", Runtime::path_name, false),
    ("path_exists", Runtime::path_exists, false),
    ("path_get_name", Runtime::path_get_name, false),
    ("path_get_length", Runtime::path_get_length, false),
    ("path_get_kind", Runtime::path_get_kind, false),
    ("path_get_closed", Runtime::path_get_closed, false),
    ("path_get_precision", Runtime::path_get_precision, false),
    ("path_get_number", Runtime::path_get_number, false),
    ("path_get_point_x", Runtime::path_get_point_x, false),
    ("path_get_point_y", Runtime::path_get_point_y, false),
    ("path_get_point_speed", Runtime::path_get_point_speed, false),
    ("path_get_x", Runtime::path_get_x, false),
    ("path_get_y", Runtime::path_get_y, false),
    ("path_get_speed", Runtime::path_get_speed, false),
    ("path_set_kind", Runtime::path_set_kind, false),
    ("path_set_closed", Runtime::path_set_closed, false),
    ("path_set_precision", Runtime::path_set_precision, false),
    ("path_add", Runtime::path_add, false),
    ("path_duplicate", Runtime::path_duplicate, false),
    ("path_assign", Runtime::path_assign, false),
    ("path_append", Runtime::path_append, false),
    ("path_delete", Runtime::path_delete, false),
    ("path_add_point", Runtime::path_add_point, false),
    ("path_insert_point", Runtime::path_insert_point, false),
    ("path_change_point", Runtime::path_change_point, false),
    ("path_delete_point", Runtime::path_delete_point, false),
    ("path_clear_points", Runtime::path_clear_points, false),
    ("path_reverse", Runtime::path_reverse, false),
    ("path_mirror", Runtime::path_mirror, false),
    ("path_flip", Runtime::path_flip, false),
    ("path_rotate", Runtime::path_rotate, false),
    ("path_scale", Runtime::path_scale, false),
    ("path_shift", Runtime::path_shift, false),
    ("timeline_name", Runtime::timeline_name, false),
    ("timeline_exists", Runtime::timeline_exists, false),
    ("timeline_get_name", Runtime::timeline_get_name, false),
    ("timeline_add", Runtime::timeline_add, false),
    ("timeline_delete", Runtime::timeline_delete, false),
    ("timeline_clear", Runtime::timeline_clear, false),
    ("timeline_moment_clear", Runtime::timeline_moment_clear, false),
    ("timeline_moment_add", Runtime::timeline_moment_add, false),
    ("object_name", Runtime::object_name, false),
    ("object_exists", Runtime::object_exists, false),
    ("object_get_name", Runtime::object_get_name, false),
    ("object_get_sprite", Runtime::object_get_sprite, false),
    ("object_get_solid", Runtime::object_get_solid, false),
    ("object_get_visible", Runtime::object_get_visible, false),
    ("object_get_depth", Runtime::object_get_depth, false),
    ("object_get_persistent", Runtime::object_get_persistent, false),
    ("object_get_mask", Runtime::object_get_mask, false),
    ("object_get_parent", Runtime::object_get_parent, false),
    ("object_is_ancestor", Runtime::object_is_ancestor, false),
    ("object_set_sprite", Runtime::object_set_sprite, false),
    ("object_set_solid", Runtime::object_set_solid, false),
    ("object_set_visible", Runtime::object_set_visible, false),
    ("object_set_depth", Runtime::object_set_depth, false),
    ("object_set_persistent", Runtime::object_set_persistent, false),
    ("object_set_mask", Runtime::object_set_mask, false),
    ("object_set_parent", Runtime::object_set_parent, false),
    ("object_add", Runtime::object_add, false),
    ("object_delete", Runtime::object_delete, false),
    ("object_event_clear", Runtime::object_event_clear, false),
    ("object_event_add", Runtime::object_event_add, false),
    ("room_name", Runtime::room_name, false),
    ("room_exists", Runtime::room_exists, false),
    ("room_get_name", Runtime::room_get_name, false),
    ("room_set_width", Runtime::room_set_width, false),
    ("room_set_height", Runtime::room_set_height, false),
    ("room_set_caption", Runtime::room_set_caption, false),
    ("room_set_persistent", Runtime::room_set_persistent, false),
    ("room_set_code", Runtime::room_set_code, false),
    ("room_set_background_color", Runtime::room_set_background_color, false),
    ("room_set_background", Runtime::room_set_background, false),
    ("room_set_view", Runtime::room_set_view, false),
    ("room_set_view_enabled", Runtime::room_set_view_enabled, false),
    ("room_add", Runtime::room_add, false),
    ("room_duplicate", Runtime::room_duplicate, false),
    ("room_assign", Runtime::room_assign, false),
    ("room_instance_add", Runtime::room_instance_add, false),
    ("room_instance_clear", Runtime::room_instance_clear, false),
    ("room_tile_add", Runtime::room_tile_add, false),
    ("room_tile_add_ext", Runtime::room_tile_add_ext, false),
    ("room_tile_clear", Runtime::room_tile_clear, false),
    ("part_type_create", Runtime::part_type_create, false),
    ("part_type_destroy", Runtime::part_type_destroy, false),
    ("part_type_exists", Runtime::part_type_exists, false),
    ("part_type_clear", Runtime::part_type_clear, false),
    ("part_type_shape", Runtime::part_type_shape, false),
    ("part_type_sprite", Runtime::part_type_sprite, false),
    ("part_type_size", Runtime::part_type_size, false),
    ("part_type_scale", Runtime::part_type_scale, false),
    ("part_type_life", Runtime::part_type_life, false),
    ("part_type_step", Runtime::part_type_step, false),
    ("part_type_death", Runtime::part_type_death, false),
    ("part_type_speed", Runtime::part_type_speed, false),
    ("part_type_direction", Runtime::part_type_direction, false),
    ("part_type_orientation", Runtime::part_type_orientation, false),
    ("part_type_gravity", Runtime::part_type_gravity, false),
    ("part_type_color_mix", Runtime::part_type_color_mix, false),
    ("part_type_color_rgb", Runtime::part_type_color_rgb, false),
    ("part_type_color_hsv", Runtime::part_type_color_hsv, false),
    ("part_type_color1", Runtime::part_type_color1, false),
    ("part_type_color2", Runtime::part_type_color2, false),
    ("part_type_color3", Runtime::part_type_color3, false),
    ("part_type_color", Runtime::part_type_color, false),
    ("part_type_alpha1", Runtime::part_type_alpha1, false),
    ("part_type_alpha2", Runtime::part_type_alpha2, false),
    ("part_type_alpha3", Runtime::part_type_alpha3, false),
    ("part_type_alpha", Runtime::part_type_alpha, false),
    ("part_type_blend", Runtime::part_type_blend, false),
    ("part_system_create", Runtime::part_system_create, false),
    ("part_system_destroy", Runtime::part_system_destroy, false),
    ("part_system_exists", Runtime::part_system_exists, false),
    ("part_system_clear", Runtime::part_system_clear, false),
    ("part_system_draw_order", Runtime::part_system_draw_order, false),
    ("part_system_depth", Runtime::part_system_depth, false),
    ("part_system_position", Runtime::part_system_position, false),
    ("part_system_automatic_update", Runtime::part_system_automatic_update, false),
    ("part_system_automatic_draw", Runtime::part_system_automatic_draw, false),
    ("part_system_update", Runtime::part_system_update, false),
    ("part_system_drawit", Runtime::part_system_drawit, false),
    ("part_particles_create", Runtime::part_particles_create, false),
    ("part_particles_create_color", Runtime::part_particles_create_color, false),
    ("part_particles_clear", Runtime::part_particles_clear, false),
    ("part_particles_count", Runtime::part_particles_count, false),
    ("part_emitter_create", Runtime::part_emitter_create, false),
    ("part_emitter_destroy", Runtime::part_emitter_destroy, false),
    ("part_emitter_destroy_all", Runtime::part_emitter_destroy_all, false),
    ("part_emitter_exists", Runtime::part_emitter_exists, false),
    ("part_emitter_clear", Runtime::part_emitter_clear, false),
    ("part_emitter_region", Runtime::part_emitter_region, false),
    ("part_emitter_burst", Runtime::part_emitter_burst, false),
    ("part_emitter_stream", Runtime::part_emitter_stream, false),
    ("part_attractor_create", Runtime::part_attractor_create, false),
    ("part_attractor_destroy", Runtime::part_attractor_destroy, false),
    ("part_attractor_destroy_all", Runtime::part_attractor_destroy_all, false),
    ("part_attractor_exists", Runtime::part_attractor_exists, false),
    ("part_attractor_clear", Runtime::part_attractor_clear, false),
    ("part_attractor_position", Runtime::part_attractor_position, false),
    ("part_attractor_force", Runtime::part_attractor_force, false),
    ("part_destroyer_create", Runtime::part_destroyer_create, false),
    ("part_destroyer_destroy", Runtime::part_destroyer_destroy, false),
    ("part_destroyer_destroy_all", Runtime::part_destroyer_destroy_all, false),
    ("part_destroyer_exists", Runtime::part_destroyer_exists, false),
    ("part_destroyer_clear", Runtime::part_destroyer_clear, false),
    ("part_destroyer_region", Runtime::part_destroyer_region, false),
    ("part_deflector_create", Runtime::part_deflector_create, false),
    ("part_deflector_destroy", Runtime::part_deflector_destroy, false),
    ("part_deflector_destroy_all", Runtime::part_deflector_destroy_all, false),
    ("part_deflector_exists", Runtime::part_deflector_exists, false),
    ("part_deflector_clear", Runtime::part_deflector_clear, false),
    ("part_deflector_region", Runtime::part_deflector_region, false),
    ("part_deflector_kind", Runtime::part_deflector_kind, false),
    ("part_deflector_friction", Runtime::part_deflector_friction, false),
    ("part_changer_create", Runtime::part_changer_create, false),
    ("part_changer_destroy", Runtime::part_changer_destroy, false),
    ("part_changer_destroy_all", Runtime::part_changer_destroy_all, false),
    ("part_changer_exists", Runtime::part_changer_exists, false),
    ("part_changer_clear", Runtime::part_changer_clear, false),
    ("part_changer_region", Runtime::part_changer_region, false),
    ("part_changer_kind", Runtime::part_changer_kind, false),
    ("part_changer_types", Runtime::part_changer_types, false),
    ("effect_create_below", Runtime::effect_create_below, false),
    ("effect_create_above", Runtime::effect_create_above, false),
    ("effect_clear", Runtime::effect_clear, false),
    ("ds_set_precision", Runtime::ds_set_precision, false),
    ("ds_stack_create", Runtime::ds_stack_create, false),
    ("ds_stack_destroy", Runtime::ds_stack_destroy, false),
    ("ds_stack_clear", Runtime::ds_stack_clear, false),
    ("ds_stack_copy", Runtime::ds_stack_copy, false),
    ("ds_stack_size", Runtime::ds_stack_size, false),
    ("ds_stack_empty", Runtime::ds_stack_empty, false),
    ("ds_stack_push", Runtime::ds_stack_push, false),
    ("ds_stack_pop", Runtime::ds_stack_pop, false),
    ("ds_stack_top", Runtime::ds_stack_top, false),
    ("ds_stack_write", Runtime::ds_stack_write, false),
    ("ds_stack_read", Runtime::ds_stack_read, false),
    ("ds_queue_create", Runtime::ds_queue_create, false),
    ("ds_queue_destroy", Runtime::ds_queue_destroy, false),
    ("ds_queue_clear", Runtime::ds_queue_clear, false),
    ("ds_queue_copy", Runtime::ds_queue_copy, false),
    ("ds_queue_size", Runtime::ds_queue_size, false),
    ("ds_queue_empty", Runtime::ds_queue_empty, false),
    ("ds_queue_enqueue", Runtime::ds_queue_enqueue, false),
    ("ds_queue_dequeue", Runtime::ds_queue_dequeue, false),
    ("ds_queue_head", Runtime::ds_queue_head, false),
    ("ds_queue_tail", Runtime::ds_queue_tail, false),
    ("ds_queue_write", Runtime::ds_queue_write, false),
    ("ds_queue_read", Runtime::ds_queue_read, false),
    ("ds_list_create", Runtime::ds_list_create, false),
    ("ds_list_destroy", Runtime::ds_list_destroy, false),
    ("ds_list_clear", Runtime::ds_list_clear, false),
    ("ds_list_copy", Runtime::ds_list_copy, false),
    ("ds_list_size", Runtime::ds_list_size, false),
    ("ds_list_empty", Runtime::ds_list_empty, false),
    ("ds_list_add", Runtime::ds_list_add, false),
    ("ds_list_insert", Runtime::ds_list_insert, false),
    ("ds_list_replace", Runtime::ds_list_replace, false),
    ("ds_list_delete", Runtime::ds_list_delete, false),
    ("ds_list_find_index", Runtime::ds_list_find_index, false),
    ("ds_list_find_value", Runtime::ds_list_find_value, false),
    ("ds_list_sort", Runtime::ds_list_sort, false),
    ("ds_list_shuffle", Runtime::ds_list_shuffle, false),
    ("ds_list_write", Runtime::ds_list_write, false),
    ("ds_list_read", Runtime::ds_list_read, false),
    ("ds_map_create", Runtime::ds_map_create, false),
    ("ds_map_destroy", Runtime::ds_map_destroy, false),
    ("ds_map_clear", Runtime::ds_map_clear, false),
    ("ds_map_copy", Runtime::ds_map_copy, false),
    ("ds_map_size", Runtime::ds_map_size, false),
    ("ds_map_empty", Runtime::ds_map_empty, false),
    ("ds_map_add", Runtime::ds_map_add, false),
    ("ds_map_replace", Runtime::ds_map_replace, false),
    ("ds_map_delete", Runtime::ds_map_delete, false),
    ("ds_map_exists", Runtime::ds_map_exists, false),
    ("ds_map_find_value", Runtime::ds_map_find_value, false),
    ("ds_map_find_previous", Runtime::ds_map_find_previous, false),
    ("ds_map_find_next", Runtime::ds_map_find_next, false),
    ("ds_map_find_first", Runtime::ds_map_find_first, false),
    ("ds_map_find_last", Runtime::ds_map_find_last, false),
    ("ds_map_write", Runtime::ds_map_write, false),
    ("ds_map_read", Runtime::ds_map_read, false),
    ("ds_priority_create", Runtime::ds_priority_create, false),
    ("ds_priority_destroy", Runtime::ds_priority_destroy, false),
    ("ds_priority_clear", Runtime::ds_priority_clear, false),
    ("ds_priority_copy", Runtime::ds_priority_copy, false),
    ("ds_priority_size", Runtime::ds_priority_size, false),
    ("ds_priority_empty", Runtime::ds_priority_empty, false),
    ("ds_priority_add", Runtime::ds_priority_add, false),
    ("ds_priority_change_priority", Runtime::ds_priority_change_priority, false),
    ("ds_priority_find_priority", Runtime::ds_priority_find_priority, false),
    ("ds_priority_delete_value", Runtime::ds_priority_delete_value, false),
    ("ds_priority_delete_min", Runtime::ds_priority_delete_min, false),
    ("ds_priority_find_min", Runtime::ds_priority_find_min, false),
    ("ds_priority_delete_max", Runtime::ds_priority_delete_max, false),
    ("ds_priority_find_max", Runtime::ds_priority_find_max, false),
    ("ds_priority_write", Runtime::ds_priority_write, false),
    ("ds_priority_read", Runtime::ds_priority_read, false),
    ("ds_grid_create", Runtime::ds_grid_create, false),
    ("ds_grid_destroy", Runtime::ds_grid_destroy, false),
    ("ds_grid_copy", Runtime::ds_grid_copy, false),
    ("ds_grid_resize", Runtime::ds_grid_resize, false),
    ("ds_grid_width", Runtime::ds_grid_width, false),
    ("ds_grid_height", Runtime::ds_grid_height, false),
    ("ds_grid_clear", Runtime::ds_grid_clear, false),
    ("ds_grid_set", Runtime::ds_grid_set, false),
    ("ds_grid_add", Runtime::ds_grid_add, false),
    ("ds_grid_multiply", Runtime::ds_grid_multiply, false),
    ("ds_grid_set_region", Runtime::ds_grid_set_region, false),
    ("ds_grid_add_region", Runtime::ds_grid_add_region, false),
    ("ds_grid_multiply_region", Runtime::ds_grid_multiply_region, false),
    ("ds_grid_set_disk", Runtime::ds_grid_set_disk, false),
    ("ds_grid_add_disk", Runtime::ds_grid_add_disk, false),
    ("ds_grid_multiply_disk", Runtime::ds_grid_multiply_disk, false),
    ("ds_grid_set_grid_region", Runtime::ds_grid_set_grid_region, false),
    ("ds_grid_add_grid_region", Runtime::ds_grid_add_grid_region, false),
    ("ds_grid_multiply_grid_region", Runtime::ds_grid_multiply_grid_region, false),
    ("ds_grid_get", Runtime::ds_grid_get, false),
    ("ds_grid_get_sum", Runtime::ds_grid_get_sum, false),
    ("ds_grid_get_max", Runtime::ds_grid_get_max, false),
    ("ds_grid_get_min", Runtime::ds_grid_get_min, false),
    ("ds_grid_get_mean", Runtime::ds_grid_get_mean, false),
    ("ds_grid_get_disk_sum", Runtime::ds_grid_get_disk_sum, false),
    ("ds_grid_get_disk_max", Runtime::ds_grid_get_disk_max, false),
    ("ds_grid_get_disk_min", Runtime::ds_grid_get_disk_min, false),
    ("ds_grid_get_disk_mean", Runtime::ds_grid_get_disk_mean, false),
    ("ds_grid_value_exists", Runtime::ds_grid_value_exists, false),
    ("ds_grid_value_x", Runtime::ds_grid_value_x, false),
    ("ds_grid_value_y", Runtime::ds_grid_value_y, false),
    ("ds_grid_value_disk_exists", Runtime::ds_grid_value_disk_exists, false),
    ("ds_grid_value_disk_x", Runtime::ds_grid_value_disk_x, false),
    ("ds_grid_value_disk_y", Runtime::ds_grid_value_disk_y, false),
    ("ds_grid_shuffle", Runtime::ds_grid_shuffle, false),
    ("ds_grid_write", Runtime::ds_grid_write, false),
    ("ds_grid_read", Runtime::ds_grid_read, false),
    ("sound_play", Runtime::sound_play, false),
    ("sound_loop", Runtime::sound_loop, false),
    ("sound_stop", Runtime::sound_stop, false),
    ("sound_stop_all", Runtime::sound_stop_all, false),
    ("sound_isplaying", Runtime::sound_isplaying, false),
    ("sound_volume", Runtime::sound_volume, false),
    ("sound_fade", Runtime::sound_fade, false),
    ("sound_pan", Runtime::sound_pan, false),
    ("sound_background_tempo", Runtime::sound_background_tempo, false),
    ("sound_global_volume", Runtime::sound_global_volume, false),
    ("sound_set_search_directory", Runtime::sound_set_search_directory, false),
    ("sound_effect_set", Runtime::sound_effect_set, false),
    ("sound_effect_chorus", Runtime::sound_effect_chorus, false),
    ("sound_effect_compressor", Runtime::sound_effect_compressor, false),
    ("sound_effect_echo", Runtime::sound_effect_echo, false),
    ("sound_effect_flanger", Runtime::sound_effect_flanger, false),
    ("sound_effect_gargle", Runtime::sound_effect_gargle, false),
    ("sound_effect_equalizer", Runtime::sound_effect_equalizer, false),
    ("sound_effect_reverb", Runtime::sound_effect_reverb, false),
    ("sound_3d_set_sound_position", Runtime::sound_3d_set_sound_position, false),
    ("sound_3d_set_sound_velocity", Runtime::sound_3d_set_sound_velocity, false),
    ("sound_3d_set_sound_distance", Runtime::sound_3d_set_sound_distance, false),
    ("sound_3d_set_sound_cone", Runtime::sound_3d_set_sound_cone, false),
    ("cd_init", Runtime::cd_init, false),
    ("cd_present", Runtime::cd_present, false),
    ("cd_number", Runtime::cd_number, false),
    ("cd_playing", Runtime::cd_playing, false),
    ("cd_paused", Runtime::cd_paused, false),
    ("cd_track", Runtime::cd_track, false),
    ("cd_length", Runtime::cd_length, false),
    ("cd_track_length", Runtime::cd_track_length, false),
    ("cd_position", Runtime::cd_position, false),
    ("cd_track_position", Runtime::cd_track_position, false),
    ("cd_play", Runtime::cd_play, false),
    ("cd_stop", Runtime::cd_stop, false),
    ("cd_pause", Runtime::cd_pause, false),
    ("cd_resume", Runtime::cd_resume, false),
    ("cd_set_position", Runtime::cd_set_position, false),
    ("cd_set_track_position", Runtime::cd_set_track_position, false),
    ("cd_open_door", Runtime::cd_open_door, false),
    ("cd_close_door", Runtime::cd_close_door, false),
    ("MCI_command", Runtime::mci_command, false),
    ("d3d_start", Runtime::d3d_start, false),
    ("d3d_end", Runtime::d3d_end, false),
    ("d3d_set_perspective", Runtime::d3d_set_perspective, false),
    ("d3d_set_hidden", Runtime::d3d_set_hidden, false),
    ("d3d_set_depth", Runtime::d3d_set_depth, false),
    ("d3d_set_zwriteenable", Runtime::d3d_set_zwriteenable, false),
    ("d3d_set_lighting", Runtime::d3d_set_lighting, false),
    ("d3d_set_shading", Runtime::d3d_set_shading, false),
    ("d3d_set_fog", Runtime::d3d_set_fog, false),
    ("d3d_set_culling", Runtime::d3d_set_culling, false),
    ("d3d_primitive_begin", Runtime::d3d_primitive_begin, false),
    ("d3d_primitive_begin_texture", Runtime::d3d_primitive_begin_texture, false),
    ("d3d_primitive_end", Runtime::d3d_primitive_end, false),
    ("d3d_vertex", Runtime::d3d_vertex, false),
    ("d3d_vertex_color", Runtime::d3d_vertex_color, false),
    ("d3d_vertex_texture", Runtime::d3d_vertex_texture, false),
    ("d3d_vertex_texture_color", Runtime::d3d_vertex_texture_color, false),
    ("d3d_vertex_normal", Runtime::d3d_vertex_normal, false),
    ("d3d_vertex_normal_color", Runtime::d3d_vertex_normal_color, false),
    ("d3d_vertex_normal_texture", Runtime::d3d_vertex_normal_texture, false),
    ("d3d_vertex_normal_texture_color", Runtime::d3d_vertex_normal_texture_color, false),
    ("d3d_draw_block", Runtime::d3d_draw_block, false),
    ("d3d_draw_cylinder", Runtime::d3d_draw_cylinder, false),
    ("d3d_draw_cone", Runtime::d3d_draw_cone, false),
    ("d3d_draw_ellipsoid", Runtime::d3d_draw_ellipsoid, false),
    ("d3d_draw_wall", Runtime::d3d_draw_wall, false),
    ("d3d_draw_floor", Runtime::d3d_draw_floor, false),
    ("d3d_set_projection", Runtime::d3d_set_projection, false),
    ("d3d_set_projection_ext", Runtime::d3d_set_projection_ext, false),
    ("d3d_set_projection_ortho", Runtime::d3d_set_projection_ortho, false),
    ("d3d_set_projection_perspective", Runtime::d3d_set_projection_perspective, false),
    ("d3d_transform_set_identity", Runtime::d3d_transform_set_identity, false),
    ("d3d_transform_set_translation", Runtime::d3d_transform_set_translation, false),
    ("d3d_transform_set_scaling", Runtime::d3d_transform_set_scaling, false),
    ("d3d_transform_set_rotation_x", Runtime::d3d_transform_set_rotation_x, false),
    ("d3d_transform_set_rotation_y", Runtime::d3d_transform_set_rotation_y, false),
    ("d3d_transform_set_rotation_z", Runtime::d3d_transform_set_rotation_z, false),
    ("d3d_transform_set_rotation_axis", Runtime::d3d_transform_set_rotation_axis, false),
    ("d3d_transform_add_translation", Runtime::d3d_transform_add_translation, false),
    ("d3d_transform_add_scaling", Runtime::d3d_transform_add_scaling, false),
    ("d3d_transform_add_rotation_x", Runtime::d3d_transform_add_rotation_x, false),
    ("d3d_transform_add_rotation_y", Runtime::d3d_transform_add_rotation_y, false),
    ("d3d_transform_add_rotation_z", Runtime::d3d_transform_add_rotation_z, false),
    ("d3d_transform_add_rotation_axis", Runtime::d3d_transform_add_rotation_axis, false),
    ("d3d_transform_stack_clear", Runtime::d3d_transform_stack_clear, false),
    ("d3d_transform_stack_empty", Runtime::d3d_transform_stack_empty, false),
    ("d3d_transform_stack_push", Runtime::d3d_transform_stack_push, false),
    ("d3d_transform_stack_pop", Runtime::d3d_transform_stack_pop, false),
    ("d3d_transform_stack_top", Runtime::d3d_transform_stack_top, false),
    ("d3d_transform_stack_discard", Runtime::d3d_transform_stack_discard, false),
    ("d3d_light_define_ambient", Runtime::d3d_light_define_ambient, false),
    ("d3d_light_define_direction", Runtime::d3d_light_define_direction, false),
    ("d3d_light_define_point", Runtime::d3d_light_define_point, false),
    ("d3d_light_enable", Runtime::d3d_light_enable, false),
    ("d3d_model_create", Runtime::d3d_model_create, false),
    ("d3d_model_destroy", Runtime::d3d_model_destroy, false),
    ("d3d_model_clear", Runtime::d3d_model_clear, false),
    ("d3d_model_load", Runtime::d3d_model_load, false),
    ("d3d_model_save", Runtime::d3d_model_save, false),
    ("d3d_model_draw", Runtime::d3d_model_draw, false),
    ("d3d_model_primitive_begin", Runtime::d3d_model_primitive_begin, false),
    ("d3d_model_primitive_end", Runtime::d3d_model_primitive_end, false),
    ("d3d_model_vertex", Runtime::d3d_model_vertex, false),
    ("d3d_model_vertex_color", Runtime::d3d_model_vertex_color, false),
    ("d3d_model_vertex_texture", Runtime::d3d_model_vertex_texture, false),
    ("d3d_model_vertex_texture_color", Runtime::d3d_model_vertex_texture_color, false),
    ("d3d_model_vertex_normal", Runtime::d3d_model_vertex_normal, false),
    ("d3d_model_vertex_normal_color", Runtime::d3d_model_vertex_normal_color, false),
    ("d3d_model_vertex_normal_texture", Runtime::d3d_model_vertex_normal_texture, false),
    ("d3d_model_vertex_normal_texture_color", Runtime::d3d_model_vertex_normal_texture_color, false),
    ("d3d_model_block", Runtime::d3d_model_block, false),
    ("d3d_model_cylinder", Runtime::d3d_model_cylinder, false),
    ("d3d_model_cone", Runtime::d3d_model_cone, false),
    ("d3d_model_ellipsoid", Runtime::d3d_model_ellipsoid, false),
    ("d3d_model_wall", Runtime::d3d_model_wall, false),
    ("d3d_model_floor", Runtime::d3d_model_floor, false),
];
