use crate::{
    game::Game,
    gml::{self, Context, InstanceVariable, Value},
};

/// Default numerical constants for GML
pub const CONSTANTS: [(&str, f64); 317] = [
    ("ANSI_CHARSET", 0.0f64),
    ("ARABIC_CHARSET", 178.0),
    ("BALTIC_CHARSET", 186.0),
    ("CHINESEBIG5_CHARSET", 136.0),
    ("DEFAULT_CHARSET", 1.0),
    ("EASTEUROPE_CHARSET", 238.0),
    ("GB2312_CHARSET", 134.0),
    ("GREEK_CHARSET", 161.0),
    ("HANGEUL_CHARSET", 129.0),
    ("HEBREW_CHARSET", 177.0),
    ("JOHAB_CHARSET", 130.0),
    ("MAC_CHARSET", 77.0),
    ("OEM_CHARSET", 255.0),
    ("RUSSIAN_CHARSET", 204.0),
    ("SHIFTJIS_CHARSET", 128.0),
    ("SYMBOL_CHARSET", 2.0),
    ("THAI_CHARSET", 222.0),
    ("TURKISH_CHARSET", 162.0),
    ("VIETNAMESE_CHARSET", 163.0),
    ("all", -3.0),
    ("bm_add", 1.0),
    ("bm_dest_alpha", 7.0),
    ("bm_dest_color", 9.0),
    ("bm_inv_dest_alpha", 8.0),
    ("bm_inv_dest_color", 10.0),
    ("bm_inv_src_alpha", 6.0),
    ("bm_inv_src_color", 4.0),
    ("bm_max", 2.0),
    ("bm_normal", 0.0),
    ("bm_one", 2.0),
    ("bm_src_alpha", 5.0),
    ("bm_src_alpha_sat", 11.0),
    ("bm_src_color", 3.0),
    ("bm_subtract", 3.0),
    ("bm_zero", 1.0),
    ("button_type", 1.0),
    ("c_aqua", 16776960.0),
    ("c_black", 0.0),
    ("c_blue", 16711680.0),
    ("c_dkgray", 4210752.0),
    ("c_fuchsia", 16711935.0),
    ("c_gray", 8421504.0),
    ("c_green", 32768.0),
    ("c_lime", 65280.0),
    ("c_ltgray", 12632256.0),
    ("c_maroon", 128.0),
    ("c_navy", 8388608.0),
    ("c_olive", 32896.0),
    ("c_orange", 4235519.0),
    ("c_purple", 8388736.0),
    ("c_red", 255.0),
    ("c_silver", 12632256.0),
    ("c_teal", 8421376.0),
    ("c_white", 16777215.0),
    ("c_yellow", 65535.0),
    ("cr_appstart", -19.0),
    ("cr_arrow", -2.0),
    ("cr_beam", -4.0),
    ("cr_cross", -3.0),
    ("cr_default", 0.0),
    ("cr_drag", -12.0),
    ("cr_handpoint", -21.0),
    ("cr_help", -20.0),
    ("cr_hourglass", -11.0),
    ("cr_hsplit", -14.0),
    ("cr_multidrag", -16.0),
    ("cr_no", -18.0),
    ("cr_nodrop", -13.0),
    ("cr_none", -1.0),
    ("cr_size_all", -22.0),
    ("cr_size_nesw", -6.0),
    ("cr_size_ns", -7.0),
    ("cr_size_nwse", -8.0),
    ("cr_size_we", -9.0),
    ("cr_sqlwait", -17.0),
    ("cr_uparrow", -10.0),
    ("cr_vsplit", -15.0),
    ("device_ios_ipad", 2.0),
    ("device_ios_iphone", 0.0),
    ("device_ios_iphone_retina", 1.0),
    ("dll_cdecl", 0.0),
    ("dll_stdcall", 1.0),
    ("ef_cloud", 9.0),
    ("ef_ellipse", 2.0),
    ("ef_explosion", 0.0),
    ("ef_firework", 3.0),
    ("ef_flare", 8.0),
    ("ef_rain", 10.0),
    ("ef_ring", 1.0),
    ("ef_smoke", 4.0),
    ("ef_smokeup", 5.0),
    ("ef_snow", 11.0),
    ("ef_spark", 7.0),
    ("ef_star", 6.0),
    ("ev_alarm", 2.0),
    ("ev_animation_end", 7.0),
    ("ev_boundary", 1.0),
    ("ev_close_button", 30.0),
    ("ev_collision", 4.0),
    ("ev_create", 0.0),
    ("ev_destroy", 1.0),
    ("ev_draw", 8.0),
    ("ev_end_of_path", 8.0),
    ("ev_game_end", 3.0),
    ("ev_game_start", 2.0),
    ("ev_global_left_button", 50.0),
    ("ev_global_left_press", 53.0),
    ("ev_global_left_release", 56.0),
    ("ev_global_middle_button", 52.0),
    ("ev_global_middle_press", 55.0),
    ("ev_global_middle_release", 58.0),
    ("ev_global_press", 12.0),
    ("ev_global_release", 13.0),
    ("ev_global_right_button", 51.0),
    ("ev_global_right_press", 54.0),
    ("ev_global_right_release", 57.0),
    ("ev_joystick1_button1", 21.0),
    ("ev_joystick1_button2", 22.0),
    ("ev_joystick1_button3", 23.0),
    ("ev_joystick1_button4", 24.0),
    ("ev_joystick1_button5", 25.0),
    ("ev_joystick1_button6", 26.0),
    ("ev_joystick1_button7", 27.0),
    ("ev_joystick1_button8", 28.0),
    ("ev_joystick1_down", 19.0),
    ("ev_joystick1_left", 16.0),
    ("ev_joystick1_right", 17.0),
    ("ev_joystick1_up", 18.0),
    ("ev_joystick2_button1", 36.0),
    ("ev_joystick2_button2", 37.0),
    ("ev_joystick2_button3", 38.0),
    ("ev_joystick2_button4", 39.0),
    ("ev_joystick2_button5", 40.0),
    ("ev_joystick2_button6", 41.0),
    ("ev_joystick2_button7", 42.0),
    ("ev_joystick2_button8", 43.0),
    ("ev_joystick2_down", 34.0),
    ("ev_joystick2_left", 31.0),
    ("ev_joystick2_right", 32.0),
    ("ev_joystick2_up", 33.0),
    ("ev_keyboard", 5.0),
    ("ev_keypress", 9.0),
    ("ev_keyrelease", 10.0),
    ("ev_left_button", 0.0),
    ("ev_left_press", 4.0),
    ("ev_left_release", 7.0),
    ("ev_middle_button", 2.0),
    ("ev_middle_press", 6.0),
    ("ev_middle_release", 9.0),
    ("ev_mouse", 6.0),
    ("ev_mouse_enter", 10.0),
    ("ev_mouse_leave", 11.0),
    ("ev_mouse_wheel_down", 61.0),
    ("ev_mouse_wheel_up", 60.0),
    ("ev_no_button", 3.0),
    ("ev_no_more_health", 9.0),
    ("ev_no_more_lives", 6.0),
    ("ev_other", 7.0),
    ("ev_outside", 0.0),
    ("ev_right_button", 1.0),
    ("ev_right_press", 5.0),
    ("ev_right_release", 8.0),
    ("ev_room_end", 5.0),
    ("ev_room_start", 4.0),
    ("ev_step", 3.0),
    ("ev_step_begin", 1.0),
    ("ev_step_end", 2.0),
    ("ev_step_normal", 0.0),
    ("ev_trigger", 11.0),
    ("ev_user0", 10.0),
    ("ev_user1", 11.0),
    ("ev_user10", 20.0),
    ("ev_user11", 21.0),
    ("ev_user12", 22.0),
    ("ev_user13", 23.0),
    ("ev_user14", 24.0),
    ("ev_user15", 25.0),
    ("ev_user2", 12.0),
    ("ev_user3", 13.0),
    ("ev_user4", 14.0),
    ("ev_user5", 15.0),
    ("ev_user6", 16.0),
    ("ev_user7", 17.0),
    ("ev_user8", 18.0),
    ("ev_user9", 19.0),
    ("fa_archive", 32.0),
    ("fa_bottom", 2.0),
    ("fa_center", 1.0),
    ("fa_directory", 16.0),
    ("fa_hidden", 2.0),
    ("fa_left", 0.0),
    ("fa_middle", 1.0),
    ("fa_readonly", 1.0),
    ("fa_right", 2.0),
    ("fa_sysfile", 4.0),
    ("fa_top", 0.0),
    ("fa_volumeid", 8.0),
    ("false", 0.0),
    ("global", -5.0),
    ("local", -7.0),
    ("mb_any", -1.0),
    ("mb_left", 1.0),
    ("mb_middle", 3.0),
    ("mb_none", 0.0),
    ("mb_right", 2.0),
    ("noone", -4.0),
    ("os_android", 5.0),
    ("os_ios", 4.0),
    ("os_macosx", 2.0),
    ("os_psp", 3.0),
    ("os_win32", 0.0),
    ("other", -2.0),
    ("pi", 3.141592654),
    ("pr_linelist", 2.0),
    ("pr_linestrip", 3.0),
    ("pr_pointlist", 1.0),
    ("pr_trianglefan", 6.0),
    ("pr_trianglelist", 4.0),
    ("pr_trianglestrip", 5.0),
    ("ps_change_all", 0.0),
    ("ps_change_motion", 2.0),
    ("ps_change_shape", 1.0),
    ("ps_deflect_horizontal", 1.0),
    ("ps_deflect_vertical", 0.0),
    ("ps_distr_gaussian", 1.0),
    ("ps_distr_invgaussian", 2.0),
    ("ps_distr_linear", 0.0),
    ("ps_force_constant", 0.0),
    ("ps_force_linear", 1.0),
    ("ps_force_quadratic", 2.0),
    ("ps_shape_diamond", 2.0),
    ("ps_shape_ellipse", 1.0),
    ("ps_shape_line", 3.0),
    ("ps_shape_rectangle", 0.0),
    ("pt_shape_circle", 5.0),
    ("pt_shape_cloud", 11.0),
    ("pt_shape_disk", 1.0),
    ("pt_shape_explosion", 10.0),
    ("pt_shape_flare", 8.0),
    ("pt_shape_line", 3.0),
    ("pt_shape_pixel", 0.0),
    ("pt_shape_ring", 6.0),
    ("pt_shape_smoke", 12.0),
    ("pt_shape_snow", 13.0),
    ("pt_shape_spark", 9.0),
    ("pt_shape_sphere", 7.0),
    ("pt_shape_square", 2.0),
    ("pt_shape_star", 4.0),
    ("se_chorus", 1.0),
    ("se_compressor", 32.0),
    ("se_echo", 2.0),
    ("se_equalizer", 64.0),
    ("se_flanger", 4.0),
    ("se_gargle", 8.0),
    ("se_none", 0.0),
    ("se_reverb", 16.0),
    ("self", -1.0),
    ("text_type", 0.0),
    ("true", 1.0),
    ("ty_real", 0.0),
    ("ty_string", 1.0),
    ("vk_add", 107.0),
    ("vk_alt", 18.0),
    ("vk_anykey", 1.0),
    ("vk_backspace", 8.0),
    ("vk_control", 17.0),
    ("vk_decimal", 110.0),
    ("vk_delete", 46.0),
    ("vk_divide", 111.0),
    ("vk_down", 40.0),
    ("vk_end", 35.0),
    ("vk_enter", 13.0),
    ("vk_escape", 27.0),
    ("vk_f1", 112.0),
    ("vk_f10", 121.0),
    ("vk_f11", 122.0),
    ("vk_f12", 123.0),
    ("vk_f2", 113.0),
    ("vk_f3", 114.0),
    ("vk_f4", 115.0),
    ("vk_f5", 116.0),
    ("vk_f6", 117.0),
    ("vk_f7", 118.0),
    ("vk_f8", 119.0),
    ("vk_f9", 120.0),
    ("vk_home", 36.0),
    ("vk_insert", 45.0),
    ("vk_lalt", 164.0),
    ("vk_lcontrol", 162.0),
    ("vk_left", 37.0),
    ("vk_lshift", 160.0),
    ("vk_multiply", 106.0),
    ("vk_nokey", 0.0),
    ("vk_numpad0", 96.0),
    ("vk_numpad1", 97.0),
    ("vk_numpad2", 98.0),
    ("vk_numpad3", 99.0),
    ("vk_numpad4", 100.0),
    ("vk_numpad5", 101.0),
    ("vk_numpad6", 102.0),
    ("vk_numpad7", 103.0),
    ("vk_numpad8", 104.0),
    ("vk_numpad9", 105.0),
    ("vk_pagedown", 34.0),
    ("vk_pageup", 33.0),
    ("vk_pause", 19.0),
    ("vk_printscreen", 44.0),
    ("vk_ralt", 165.0),
    ("vk_rcontrol", 163.0),
    ("vk_return", 13.0),
    ("vk_right", 39.0),
    ("vk_rshift", 161.0),
    ("vk_shift", 16.0),
    ("vk_space", 32.0),
    ("vk_subtract", 109.0),
    ("vk_tab", 9.0),
    ("vk_up", 38.0),
];

/// Mappings of instance variable names to their enum identifiers
pub const INSTANCE_VARIABLES: [(&str, InstanceVariable); 166] = [
    ("x", InstanceVariable::X),
    ("y", InstanceVariable::Y),
    ("xprevious", InstanceVariable::Xprevious),
    ("yprevious", InstanceVariable::Yprevious),
    ("xstart", InstanceVariable::Xstart),
    ("ystart", InstanceVariable::Ystart),
    ("hspeed", InstanceVariable::Hspeed),
    ("vspeed", InstanceVariable::Vspeed),
    ("direction", InstanceVariable::Direction),
    ("speed", InstanceVariable::Speed),
    ("friction", InstanceVariable::Friction),
    ("gravity", InstanceVariable::Gravity),
    ("gravity_direction", InstanceVariable::GravityDirection),
    ("object_index", InstanceVariable::ObjectIndex),
    ("id", InstanceVariable::Id),
    ("alarm", InstanceVariable::Alarm),
    ("solid", InstanceVariable::Solid),
    ("visible", InstanceVariable::Visible),
    ("persistent", InstanceVariable::Persistent),
    ("depth", InstanceVariable::Depth),
    ("bbox_left", InstanceVariable::BboxLeft),
    ("bbox_right", InstanceVariable::BboxRight),
    ("bbox_top", InstanceVariable::BboxTop),
    ("bbox_bottom", InstanceVariable::BboxBottom),
    ("sprite_index", InstanceVariable::SpriteIndex),
    ("image_index", InstanceVariable::ImageIndex),
    ("image_single", InstanceVariable::ImageSingle),
    ("image_number", InstanceVariable::ImageNumber),
    ("sprite_width", InstanceVariable::SpriteWidth),
    ("sprite_height", InstanceVariable::SpriteHeight),
    ("sprite_xoffset", InstanceVariable::SpriteXoffset),
    ("sprite_yoffset", InstanceVariable::SpriteYoffset),
    ("image_xscale", InstanceVariable::ImageXscale),
    ("image_yscale", InstanceVariable::ImageYscale),
    ("image_angle", InstanceVariable::ImageAngle),
    ("image_alpha", InstanceVariable::ImageAlpha),
    ("image_blend", InstanceVariable::ImageBlend),
    ("image_speed", InstanceVariable::ImageSpeed),
    ("mask_index", InstanceVariable::MaskIndex),
    ("path_index", InstanceVariable::PathIndex),
    ("path_position", InstanceVariable::PathPosition),
    ("path_positionprevious", InstanceVariable::PathPositionprevious),
    ("path_speed", InstanceVariable::PathSpeed),
    ("path_scale", InstanceVariable::PathScale),
    ("path_orientation", InstanceVariable::PathOrientation),
    ("path_endaction", InstanceVariable::PathEndaction),
    ("timeline_index", InstanceVariable::TimelineIndex),
    ("timeline_position", InstanceVariable::TimelinePosition),
    ("timeline_speed", InstanceVariable::TimelineSpeed),
    ("timeline_running", InstanceVariable::TimelineRunning),
    ("timeline_loop", InstanceVariable::TimelineLoop),
    ("argument_relative", InstanceVariable::ArgumentRelative),
    ("argument0", InstanceVariable::Argument0),
    ("argument1", InstanceVariable::Argument1),
    ("argument2", InstanceVariable::Argument2),
    ("argument3", InstanceVariable::Argument3),
    ("argument4", InstanceVariable::Argument4),
    ("argument5", InstanceVariable::Argument5),
    ("argument6", InstanceVariable::Argument6),
    ("argument7", InstanceVariable::Argument7),
    ("argument8", InstanceVariable::Argument8),
    ("argument9", InstanceVariable::Argument9),
    ("argument10", InstanceVariable::Argument10),
    ("argument11", InstanceVariable::Argument11),
    ("argument12", InstanceVariable::Argument12),
    ("argument13", InstanceVariable::Argument13),
    ("argument14", InstanceVariable::Argument14),
    ("argument15", InstanceVariable::Argument15),
    ("argument", InstanceVariable::Argument),
    ("argument_count", InstanceVariable::ArgumentCount),
    ("room", InstanceVariable::Room),
    ("room_first", InstanceVariable::RoomFirst),
    ("room_last", InstanceVariable::RoomLast),
    ("transition_kind", InstanceVariable::TransitionKind),
    ("transition_steps", InstanceVariable::TransitionSteps),
    ("score", InstanceVariable::Score),
    ("lives", InstanceVariable::Lives),
    ("health", InstanceVariable::Health),
    ("game_id", InstanceVariable::GameId),
    ("working_directory", InstanceVariable::WorkingDirectory),
    ("temp_directory", InstanceVariable::TempDirectory),
    ("program_directory", InstanceVariable::ProgramDirectory),
    ("instance_count", InstanceVariable::InstanceCount),
    ("instance_id", InstanceVariable::InstanceId),
    ("room_width", InstanceVariable::RoomWidth),
    ("room_height", InstanceVariable::RoomHeight),
    ("room_caption", InstanceVariable::RoomCaption),
    ("room_speed", InstanceVariable::RoomSpeed),
    ("room_persistent", InstanceVariable::RoomPersistent),
    ("background_color", InstanceVariable::BackgroundColor),
    ("background_showcolor", InstanceVariable::BackgroundShowcolor),
    ("background_visible", InstanceVariable::BackgroundVisible),
    ("background_foreground", InstanceVariable::BackgroundForeground),
    ("background_index", InstanceVariable::BackgroundIndex),
    ("background_x", InstanceVariable::BackgroundX),
    ("background_y", InstanceVariable::BackgroundY),
    ("background_width", InstanceVariable::BackgroundWidth),
    ("background_height", InstanceVariable::BackgroundHeight),
    ("background_htiled", InstanceVariable::BackgroundHtiled),
    ("background_vtiled", InstanceVariable::BackgroundVtiled),
    ("background_xscale", InstanceVariable::BackgroundXscale),
    ("background_yscale", InstanceVariable::BackgroundYscale),
    ("background_hspeed", InstanceVariable::BackgroundHspeed),
    ("background_vspeed", InstanceVariable::BackgroundVspeed),
    ("background_blend", InstanceVariable::BackgroundBlend),
    ("background_alpha", InstanceVariable::BackgroundAlpha),
    ("view_enabled", InstanceVariable::ViewEnabled),
    ("view_current", InstanceVariable::ViewCurrent),
    ("view_visible", InstanceVariable::ViewVisible),
    ("view_xview", InstanceVariable::ViewXview),
    ("view_yview", InstanceVariable::ViewYview),
    ("view_wview", InstanceVariable::ViewWview),
    ("view_hview", InstanceVariable::ViewHview),
    ("view_xport", InstanceVariable::ViewXport),
    ("view_yport", InstanceVariable::ViewYport),
    ("view_wport", InstanceVariable::ViewWport),
    ("view_hport", InstanceVariable::ViewHport),
    ("view_angle", InstanceVariable::ViewAngle),
    ("view_hborder", InstanceVariable::ViewHborder),
    ("view_vborder", InstanceVariable::ViewVborder),
    ("view_hspeed", InstanceVariable::ViewHspeed),
    ("view_vspeed", InstanceVariable::ViewVspeed),
    ("view_object", InstanceVariable::ViewObject),
    ("mouse_x", InstanceVariable::MouseX),
    ("mouse_y", InstanceVariable::MouseY),
    ("mouse_button", InstanceVariable::MouseButton),
    ("mouse_lastbutton", InstanceVariable::MouseLastbutton),
    ("keyboard_key", InstanceVariable::KeyboardKey),
    ("keyboard_lastkey", InstanceVariable::KeyboardLastkey),
    ("keyboard_lastchar", InstanceVariable::KeyboardLastchar),
    ("keyboard_string", InstanceVariable::KeyboardString),
    ("cursor_sprite", InstanceVariable::CursorSprite),
    ("show_score", InstanceVariable::ShowScore),
    ("show_lives", InstanceVariable::ShowLives),
    ("show_health", InstanceVariable::ShowHealth),
    ("caption_score", InstanceVariable::CaptionScore),
    ("caption_lives", InstanceVariable::CaptionLives),
    ("caption_health", InstanceVariable::CaptionHealth),
    ("fps", InstanceVariable::Fps),
    ("current_time", InstanceVariable::CurrentTime),
    ("current_year", InstanceVariable::CurrentYear),
    ("current_month", InstanceVariable::CurrentMonth),
    ("current_day", InstanceVariable::CurrentDay),
    ("current_weekday", InstanceVariable::CurrentWeekday),
    ("current_hour", InstanceVariable::CurrentHour),
    ("current_minute", InstanceVariable::CurrentMinute),
    ("current_second", InstanceVariable::CurrentSecond),
    ("event_type", InstanceVariable::EventType),
    ("event_number", InstanceVariable::EventNumber),
    ("event_object", InstanceVariable::EventObject),
    ("event_action", InstanceVariable::EventAction),
    ("secure_mode", InstanceVariable::SecureMode),
    ("debug_mode", InstanceVariable::DebugMode),
    ("error_occurred", InstanceVariable::ErrorOccurred),
    ("error_last", InstanceVariable::ErrorLast),
    ("gamemaker_registered", InstanceVariable::GamemakerRegistered),
    ("gamemaker_pro", InstanceVariable::GamemakerPro),
    ("gamemaker_version", InstanceVariable::GamemakerVersion),
    ("os_type", InstanceVariable::OsType),
    ("os_device", InstanceVariable::OsDevice),
    ("os_browser", InstanceVariable::OsBrowser),
    ("os_version", InstanceVariable::OsVersion),
    ("browser_width", InstanceVariable::BrowserWidth),
    ("browser_height", InstanceVariable::BrowserHeight),
    ("display_aa", InstanceVariable::DisplayAa),
    ("async_load", InstanceVariable::AsyncLoad),
];

/// Mappings of function names to fn pointers
/// The bool indicates whether the function is constant, ie. it doesn't read or write any internal state.
pub const FUNCTIONS: [(&str, fn(&mut Game, &mut Context, &[Value]) -> gml::Result<Value>, bool); 1281] = [
    ("display_get_width", Game::display_get_width, false),
    ("display_get_height", Game::display_get_height, false),
    ("display_get_colordepth", Game::display_get_colordepth, false),
    ("display_get_frequency", Game::display_get_frequency, false),
    ("display_set_size", Game::display_set_size, false),
    ("display_set_colordepth", Game::display_set_colordepth, false),
    ("display_set_frequency", Game::display_set_frequency, false),
    ("display_set_all", Game::display_set_all, false),
    ("display_test_all", Game::display_test_all, false),
    ("display_reset", Game::display_reset, false),
    ("display_mouse_get_x", Game::display_mouse_get_x, false),
    ("display_mouse_get_y", Game::display_mouse_get_y, false),
    ("display_mouse_set", Game::display_mouse_set, false),
    ("window_set_visible", Game::window_set_visible, false),
    ("window_get_visible", Game::window_get_visible, false),
    ("window_set_fullscreen", Game::window_set_fullscreen, false),
    ("window_get_fullscreen", Game::window_get_fullscreen, false),
    ("window_set_showborder", Game::window_set_showborder, false),
    ("window_get_showborder", Game::window_get_showborder, false),
    ("window_set_showicons", Game::window_set_showicons, false),
    ("window_get_showicons", Game::window_get_showicons, false),
    ("window_set_stayontop", Game::window_set_stayontop, false),
    ("window_get_stayontop", Game::window_get_stayontop, false),
    ("window_set_sizeable", Game::window_set_sizeable, false),
    ("window_get_sizeable", Game::window_get_sizeable, false),
    ("window_set_caption", Game::window_set_caption, false),
    ("window_get_caption", Game::window_get_caption, false),
    ("window_set_cursor", Game::window_set_cursor, false),
    ("window_get_cursor", Game::window_get_cursor, false),
    ("window_set_color", Game::window_set_color, false),
    ("window_get_color", Game::window_get_color, false),
    ("window_set_position", Game::window_set_position, false),
    ("window_set_size", Game::window_set_size, false),
    ("window_set_rectangle", Game::window_set_rectangle, false),
    ("window_center", Game::window_center, false),
    ("window_default", Game::window_default, false),
    ("window_get_x", Game::window_get_x, false),
    ("window_get_y", Game::window_get_y, false),
    ("window_get_width", Game::window_get_width, false),
    ("window_get_height", Game::window_get_height, false),
    ("window_set_region_size", Game::window_set_region_size, false),
    ("window_get_region_width", Game::window_get_region_width, false),
    ("window_get_region_height", Game::window_get_region_height, false),
    ("window_set_region_scale", Game::window_set_region_scale, false),
    ("window_get_region_scale", Game::window_get_region_scale, false),
    ("window_mouse_get_x", Game::window_mouse_get_x, false),
    ("window_mouse_get_y", Game::window_mouse_get_y, false),
    ("window_mouse_set", Game::window_mouse_set, false),
    ("window_view_mouse_get_x", Game::window_view_mouse_get_x, false),
    ("window_view_mouse_get_y", Game::window_view_mouse_get_y, false),
    ("window_view_mouse_set", Game::window_view_mouse_set, false),
    ("window_views_mouse_get_x", Game::window_views_mouse_get_x, false),
    ("window_views_mouse_get_y", Game::window_views_mouse_get_y, false),
    ("window_views_mouse_set", Game::window_views_mouse_set, false),
    ("set_synchronization", Game::set_synchronization, false),
    ("set_automatic_draw", Game::set_automatic_draw, false),
    ("screen_redraw", Game::screen_redraw, false),
    ("screen_refresh", Game::screen_refresh, false),
    ("screen_wait_vsync", Game::screen_wait_vsync, false),
    ("screen_save", Game::screen_save, false),
    ("screen_save_part", Game::screen_save_part, false),
    ("draw_getpixel", Game::draw_getpixel, false),
    ("draw_set_color", Game::draw_set_color, false),
    ("draw_set_alpha", Game::draw_set_alpha, false),
    ("draw_get_color", Game::draw_get_color, false),
    ("draw_get_alpha", Game::draw_get_alpha, false),
    ("make_color", Game::make_color, true),
    ("make_color_rgb", Game::make_color_rgb, true),
    ("make_color_hsv", Game::make_color_hsv, true),
    ("color_get_red", Game::color_get_red, true),
    ("color_get_green", Game::color_get_green, true),
    ("color_get_blue", Game::color_get_blue, true),
    ("color_get_hue", Game::color_get_hue, true),
    ("color_get_saturation", Game::color_get_saturation, true),
    ("color_get_value", Game::color_get_value, true),
    ("merge_color", Game::merge_color, true),
    ("draw_set_blend_mode", Game::draw_set_blend_mode, false),
    ("draw_set_blend_mode_ext", Game::draw_set_blend_mode_ext, false),
    ("draw_clear", Game::draw_clear, false),
    ("draw_clear_alpha", Game::draw_clear_alpha, false),
    ("draw_point", Game::draw_point, false),
    ("draw_line", Game::draw_line, false),
    ("draw_line_width", Game::draw_line_width, false),
    ("draw_rectangle", Game::draw_rectangle, false),
    ("draw_roundrect", Game::draw_roundrect, false),
    ("draw_triangle", Game::draw_triangle, false),
    ("draw_circle", Game::draw_circle, false),
    ("draw_ellipse", Game::draw_ellipse, false),
    ("draw_arrow", Game::draw_arrow, false),
    ("draw_button", Game::draw_button, false),
    ("draw_healthbar", Game::draw_healthbar, false),
    ("draw_path", Game::draw_path, false),
    ("draw_point_color", Game::draw_point_color, false),
    ("draw_line_color", Game::draw_line_color, false),
    ("draw_line_width_color", Game::draw_line_width_color, false),
    ("draw_rectangle_color", Game::draw_rectangle_color, false),
    ("draw_roundrect_color", Game::draw_roundrect_color, false),
    ("draw_triangle_color", Game::draw_triangle_color, false),
    ("draw_circle_color", Game::draw_circle_color, false),
    ("draw_ellipse_color", Game::draw_ellipse_color, false),
    ("draw_set_circle_precision", Game::draw_set_circle_precision, false),
    ("draw_primitive_begin", Game::draw_primitive_begin, false),
    ("draw_primitive_begin_texture", Game::draw_primitive_begin_texture, false),
    ("draw_primitive_end", Game::draw_primitive_end, false),
    ("draw_vertex", Game::draw_vertex, false),
    ("draw_vertex_color", Game::draw_vertex_color, false),
    ("draw_vertex_texture", Game::draw_vertex_texture, false),
    ("draw_vertex_texture_color", Game::draw_vertex_texture_color, false),
    ("sprite_get_texture", Game::sprite_get_texture, false),
    ("background_get_texture", Game::background_get_texture, false),
    ("texture_exists", Game::texture_exists, false),
    ("texture_set_interpolation", Game::texture_set_interpolation, false),
    ("texture_set_blending", Game::texture_set_blending, false),
    ("texture_set_repeat", Game::texture_set_repeat, false),
    ("texture_get_width", Game::texture_get_width, false),
    ("texture_get_height", Game::texture_get_height, false),
    ("texture_preload", Game::texture_preload, false),
    ("texture_set_priority", Game::texture_set_priority, false),
    ("draw_set_font", Game::draw_set_font, false),
    ("draw_set_halign", Game::draw_set_halign, false),
    ("draw_set_valign", Game::draw_set_valign, false),
    ("string_width", Game::string_width, true),
    ("string_height", Game::string_height, true),
    ("string_width_ext", Game::string_width_ext, true),
    ("string_height_ext", Game::string_height_ext, true),
    ("draw_text", Game::draw_text, false),
    ("draw_text_ext", Game::draw_text_ext, false),
    ("draw_text_transformed", Game::draw_text_transformed, false),
    ("draw_text_ext_transformed", Game::draw_text_ext_transformed, false),
    ("draw_text_color", Game::draw_text_color, false),
    ("draw_text_transformed_color", Game::draw_text_transformed_color, false),
    ("draw_text_ext_color", Game::draw_text_ext_color, false),
    ("draw_text_ext_transformed_color", Game::draw_text_ext_transformed_color, false),
    ("draw_self", Game::draw_self, false),
    ("draw_sprite", Game::draw_sprite, false),
    ("draw_sprite_pos", Game::draw_sprite_pos, false),
    ("draw_sprite_ext", Game::draw_sprite_ext, false),
    ("draw_sprite_stretched", Game::draw_sprite_stretched, false),
    ("draw_sprite_stretched_ext", Game::draw_sprite_stretched_ext, false),
    ("draw_sprite_part", Game::draw_sprite_part, false),
    ("draw_sprite_part_ext", Game::draw_sprite_part_ext, false),
    ("draw_sprite_general", Game::draw_sprite_general, false),
    ("draw_sprite_tiled", Game::draw_sprite_tiled, false),
    ("draw_sprite_tiled_ext", Game::draw_sprite_tiled_ext, false),
    ("draw_background", Game::draw_background, false),
    ("draw_background_ext", Game::draw_background_ext, false),
    ("draw_background_stretched", Game::draw_background_stretched, false),
    ("draw_background_stretched_ext", Game::draw_background_stretched_ext, false),
    ("draw_background_part", Game::draw_background_part, false),
    ("draw_background_part_ext", Game::draw_background_part_ext, false),
    ("draw_background_general", Game::draw_background_general, false),
    ("draw_background_tiled", Game::draw_background_tiled, false),
    ("draw_background_tiled_ext", Game::draw_background_tiled_ext, false),
    ("tile_get_x", Game::tile_get_x, false),
    ("tile_get_y", Game::tile_get_y, false),
    ("tile_get_left", Game::tile_get_left, false),
    ("tile_get_top", Game::tile_get_top, false),
    ("tile_get_width", Game::tile_get_width, false),
    ("tile_get_height", Game::tile_get_height, false),
    ("tile_get_depth", Game::tile_get_depth, false),
    ("tile_get_visible", Game::tile_get_visible, false),
    ("tile_get_xscale", Game::tile_get_xscale, false),
    ("tile_get_yscale", Game::tile_get_yscale, false),
    ("tile_get_blend", Game::tile_get_blend, false),
    ("tile_get_alpha", Game::tile_get_alpha, false),
    ("tile_get_background", Game::tile_get_background, false),
    ("tile_set_visible", Game::tile_set_visible, false),
    ("tile_set_background", Game::tile_set_background, false),
    ("tile_set_region", Game::tile_set_region, false),
    ("tile_set_position", Game::tile_set_position, false),
    ("tile_set_depth", Game::tile_set_depth, false),
    ("tile_set_scale", Game::tile_set_scale, false),
    ("tile_set_blend", Game::tile_set_blend, false),
    ("tile_set_alpha", Game::tile_set_alpha, false),
    ("tile_add", Game::tile_add, false),
    ("tile_find", Game::tile_find, false),
    ("tile_exists", Game::tile_exists, false),
    ("tile_delete", Game::tile_delete, false),
    ("tile_delete_at", Game::tile_delete_at, false),
    ("tile_layer_hide", Game::tile_layer_hide, false),
    ("tile_layer_show", Game::tile_layer_show, false),
    ("tile_layer_delete", Game::tile_layer_delete, false),
    ("tile_layer_shift", Game::tile_layer_shift, false),
    ("tile_layer_find", Game::tile_layer_find, false),
    ("tile_layer_delete_at", Game::tile_layer_delete_at, false),
    ("tile_layer_depth", Game::tile_layer_depth, false),
    ("surface_create", Game::surface_create, false),
    ("surface_create_ext", Game::surface_create_ext, false),
    ("surface_free", Game::surface_free, false),
    ("surface_exists", Game::surface_exists, false),
    ("surface_get_width", Game::surface_get_width, false),
    ("surface_get_height", Game::surface_get_height, false),
    ("surface_get_texture", Game::surface_get_texture, false),
    ("surface_set_target", Game::surface_set_target, false),
    ("surface_reset_target", Game::surface_reset_target, false),
    ("draw_surface", Game::draw_surface, false),
    ("draw_surface_ext", Game::draw_surface_ext, false),
    ("draw_surface_stretched", Game::draw_surface_stretched, false),
    ("draw_surface_stretched_ext", Game::draw_surface_stretched_ext, false),
    ("draw_surface_part", Game::draw_surface_part, false),
    ("draw_surface_part_ext", Game::draw_surface_part_ext, false),
    ("draw_surface_general", Game::draw_surface_general, false),
    ("draw_surface_tiled", Game::draw_surface_tiled, false),
    ("draw_surface_tiled_ext", Game::draw_surface_tiled_ext, false),
    ("surface_save", Game::surface_save, false),
    ("surface_save_part", Game::surface_save_part, false),
    ("surface_getpixel", Game::surface_getpixel, false),
    ("surface_copy", Game::surface_copy, false),
    ("surface_copy_part", Game::surface_copy_part, false),
    ("action_path_old", Game::action_path_old, false),
    ("action_set_sprite", Game::action_set_sprite, false),
    ("action_draw_font", Game::action_draw_font, false),
    ("action_draw_font_old", Game::action_draw_font_old, false),
    ("action_fill_color", Game::action_fill_color, false),
    ("action_line_color", Game::action_line_color, false),
    ("action_highscore", Game::action_highscore, false),
    ("action_move", Game::action_move, false),
    ("action_set_motion", Game::action_set_motion, false),
    ("action_set_hspeed", Game::action_set_hspeed, false),
    ("action_set_vspeed", Game::action_set_vspeed, false),
    ("action_set_gravity", Game::action_set_gravity, false),
    ("action_set_friction", Game::action_set_friction, false),
    ("action_move_point", Game::action_move_point, false),
    ("action_move_to", Game::action_move_to, false),
    ("action_move_start", Game::action_move_start, false),
    ("action_move_random", Game::action_move_random, false),
    ("action_snap", Game::action_snap, false),
    ("action_wrap", Game::action_wrap, false),
    ("action_reverse_xdir", Game::action_reverse_xdir, false),
    ("action_reverse_ydir", Game::action_reverse_ydir, false),
    ("action_move_contact", Game::action_move_contact, false),
    ("action_bounce", Game::action_bounce, false),
    ("action_path", Game::action_path, false),
    ("action_path_end", Game::action_path_end, false),
    ("action_path_position", Game::action_path_position, false),
    ("action_path_speed", Game::action_path_speed, false),
    ("action_linear_step", Game::action_linear_step, false),
    ("action_potential_step", Game::action_potential_step, false),
    ("action_kill_object", Game::action_kill_object, false),
    ("action_create_object", Game::action_create_object, false),
    ("action_create_object_motion", Game::action_create_object_motion, false),
    ("action_create_object_random", Game::action_create_object_random, false),
    ("action_change_object", Game::action_change_object, false),
    ("action_kill_position", Game::action_kill_position, false),
    ("action_sprite_set", Game::action_sprite_set, false),
    ("action_sprite_transform", Game::action_sprite_transform, false),
    ("action_sprite_color", Game::action_sprite_color, false),
    ("action_sound", Game::action_sound, false),
    ("action_end_sound", Game::action_end_sound, false),
    ("action_if_sound", Game::action_if_sound, false),
    ("action_another_room", Game::action_another_room, false),
    ("action_current_room", Game::action_current_room, false),
    ("action_previous_room", Game::action_previous_room, false),
    ("action_next_room", Game::action_next_room, false),
    ("action_if_previous_room", Game::action_if_previous_room, false),
    ("action_if_next_room", Game::action_if_next_room, false),
    ("action_set_alarm", Game::action_set_alarm, false),
    ("action_sleep", Game::action_sleep, false),
    ("action_set_timeline", Game::action_set_timeline, false),
    ("action_timeline_set", Game::action_timeline_set, false),
    ("action_timeline_start", Game::action_timeline_start, false),
    ("action_timeline_pause", Game::action_timeline_pause, false),
    ("action_timeline_stop", Game::action_timeline_stop, false),
    ("action_set_timeline_position", Game::action_set_timeline_position, false),
    ("action_set_timeline_speed", Game::action_set_timeline_speed, false),
    ("action_message", Game::action_message, false),
    ("action_show_info", Game::action_show_info, false),
    ("action_show_video", Game::action_show_video, false),
    ("action_splash_video", Game::action_splash_video, false),
    ("action_splash_text", Game::action_splash_text, false),
    ("action_splash_image", Game::action_splash_image, false),
    ("action_splash_web", Game::action_splash_web, false),
    ("action_splash_settings", Game::action_splash_settings, false),
    ("action_end_game", Game::action_end_game, false),
    ("action_restart_game", Game::action_restart_game, false),
    ("action_save_game", Game::action_save_game, false),
    ("action_load_game", Game::action_load_game, false),
    ("action_replace_sprite", Game::action_replace_sprite, false),
    ("action_replace_sound", Game::action_replace_sound, false),
    ("action_replace_background", Game::action_replace_background, false),
    ("action_if_empty", Game::action_if_empty, false),
    ("action_if_collision", Game::action_if_collision, false),
    ("action_if", Game::action_if, false),
    ("action_if_number", Game::action_if_number, false),
    ("action_if_object", Game::action_if_object, false),
    ("action_if_question", Game::action_if_question, false),
    ("action_if_dice", Game::action_if_dice, false),
    ("action_if_mouse", Game::action_if_mouse, false),
    ("action_if_aligned", Game::action_if_aligned, false),
    ("action_execute_script", Game::action_execute_script, false),
    ("action_inherited", Game::action_inherited, false),
    ("action_if_variable", Game::action_if_variable, false),
    ("action_draw_variable", Game::action_draw_variable, false),
    ("action_set_score", Game::action_set_score, false),
    ("action_if_score", Game::action_if_score, false),
    ("action_draw_score", Game::action_draw_score, false),
    ("action_highscore_show", Game::action_highscore_show, false),
    ("action_highscore_clear", Game::action_highscore_clear, false),
    ("action_set_life", Game::action_set_life, false),
    ("action_if_life", Game::action_if_life, false),
    ("action_draw_life", Game::action_draw_life, false),
    ("action_draw_life_images", Game::action_draw_life_images, false),
    ("action_set_health", Game::action_set_health, false),
    ("action_if_health", Game::action_if_health, false),
    ("action_draw_health", Game::action_draw_health, false),
    ("action_set_caption", Game::action_set_caption, false),
    ("action_partsyst_create", Game::action_partsyst_create, false),
    ("action_partsyst_destroy", Game::action_partsyst_destroy, false),
    ("action_partsyst_clear", Game::action_partsyst_clear, false),
    ("action_parttype_create_old", Game::action_parttype_create_old, false),
    ("action_parttype_create", Game::action_parttype_create, false),
    ("action_parttype_color", Game::action_parttype_color, false),
    ("action_parttype_life", Game::action_parttype_life, false),
    ("action_parttype_speed", Game::action_parttype_speed, false),
    ("action_parttype_gravity", Game::action_parttype_gravity, false),
    ("action_parttype_secondary", Game::action_parttype_secondary, false),
    ("action_partemit_create", Game::action_partemit_create, false),
    ("action_partemit_destroy", Game::action_partemit_destroy, false),
    ("action_partemit_burst", Game::action_partemit_burst, false),
    ("action_partemit_stream", Game::action_partemit_stream, false),
    ("action_cd_play", Game::action_cd_play, false),
    ("action_cd_stop", Game::action_cd_stop, false),
    ("action_cd_pause", Game::action_cd_pause, false),
    ("action_cd_resume", Game::action_cd_resume, false),
    ("action_cd_present", Game::action_cd_present, false),
    ("action_cd_playing", Game::action_cd_playing, false),
    ("action_set_cursor", Game::action_set_cursor, false),
    ("action_webpage", Game::action_webpage, false),
    ("action_draw_sprite", Game::action_draw_sprite, false),
    ("action_draw_background", Game::action_draw_background, false),
    ("action_draw_text", Game::action_draw_text, false),
    ("action_draw_text_transformed", Game::action_draw_text_transformed, false),
    ("action_draw_rectangle", Game::action_draw_rectangle, false),
    ("action_draw_gradient_hor", Game::action_draw_gradient_hor, false),
    ("action_draw_gradient_vert", Game::action_draw_gradient_vert, false),
    ("action_draw_ellipse", Game::action_draw_ellipse, false),
    ("action_draw_ellipse_gradient", Game::action_draw_ellipse_gradient, false),
    ("action_draw_line", Game::action_draw_line, false),
    ("action_draw_arrow", Game::action_draw_arrow, false),
    ("action_color", Game::action_color, false),
    ("action_font", Game::action_font, false),
    ("action_fullscreen", Game::action_fullscreen, false),
    ("action_snapshot", Game::action_snapshot, false),
    ("action_effect", Game::action_effect, false),
    ("is_real", Game::is_real, true),
    ("is_string", Game::is_string, true),
    ("random", Game::random, false),
    ("random_range", Game::random_range, false),
    ("irandom", Game::irandom, false),
    ("irandom_range", Game::irandom_range, false),
    ("random_set_seed", Game::random_set_seed, false),
    ("random_get_seed", Game::random_get_seed, false),
    ("randomize", Game::randomize, false),
    ("abs", Game::abs, true),
    ("round", Game::round, true),
    ("floor", Game::floor, true),
    ("ceil", Game::ceil, true),
    ("sign", Game::sign, true),
    ("frac", Game::frac, true),
    ("sqrt", Game::sqrt, true),
    ("sqr", Game::sqr, true),
    ("exp", Game::exp, true),
    ("ln", Game::ln, true),
    ("log2", Game::log2, true),
    ("log10", Game::log10, true),
    ("sin", Game::sin, true),
    ("cos", Game::cos, true),
    ("tan", Game::tan, true),
    ("arcsin", Game::arcsin, true),
    ("arccos", Game::arccos, true),
    ("arctan", Game::arctan, true),
    ("arctan2", Game::arctan2, true),
    ("degtorad", Game::degtorad, true),
    ("radtodeg", Game::radtodeg, true),
    ("power", Game::power, true),
    ("logn", Game::logn, true),
    ("min", Game::min, true),
    ("max", Game::max, true),
    ("min3", Game::min3, true),
    ("max3", Game::max3, true),
    ("mean", Game::mean, true),
    ("median", Game::median, true),
    ("choose", Game::choose, false),
    ("clamp", Game::clamp, true),
    ("lerp", Game::lerp, true),
    ("real", Game::real, true),
    ("string", Game::string, true),
    ("string_format", Game::string_format, true),
    ("chr", Game::chr, true),
    ("ansi_char", Game::ansi_char, true),
    ("ord", Game::ord, true),
    ("string_length", Game::string_length, true),
    ("string_byte_length", Game::string_byte_length, true),
    ("string_byte_at", Game::string_byte_at, true),
    ("string_pos", Game::string_pos, true),
    ("string_copy", Game::string_copy, true),
    ("string_char_at", Game::string_char_at, true),
    ("string_delete", Game::string_delete, true),
    ("string_insert", Game::string_insert, true),
    ("string_lower", Game::string_lower, true),
    ("string_upper", Game::string_upper, true),
    ("string_repeat", Game::string_repeat, true),
    ("string_letters", Game::string_letters, true),
    ("string_digits", Game::string_digits, true),
    ("string_lettersdigits", Game::string_lettersdigits, true),
    ("string_replace", Game::string_replace, true),
    ("string_replace_all", Game::string_replace_all, true),
    ("string_count", Game::string_count, true),
    ("dot_product", Game::dot_product, true),
    ("dot_product_3d", Game::dot_product_3d, true),
    ("point_distance_3d", Game::point_distance_3d, true),
    ("point_distance", Game::point_distance, true),
    ("point_direction", Game::point_direction, true),
    ("lengthdir_x", Game::lengthdir_x, true),
    ("lengthdir_y", Game::lengthdir_y, true),
    ("move_random", Game::move_random, false),
    ("place_free", Game::place_free, false),
    ("place_empty", Game::place_empty, false),
    ("place_meeting", Game::place_meeting, false),
    ("place_snapped", Game::place_snapped, false),
    ("move_snap", Game::move_snap, false),
    ("move_towards_point", Game::move_towards_point, false),
    ("move_contact", Game::move_contact, false),
    ("move_contact_solid", Game::move_contact_solid, false),
    ("move_contact_all", Game::move_contact_all, false),
    ("move_outside_solid", Game::move_outside_solid, false),
    ("move_outside_all", Game::move_outside_all, false),
    ("move_bounce", Game::move_bounce, false),
    ("move_bounce_solid", Game::move_bounce_solid, false),
    ("move_bounce_all", Game::move_bounce_all, false),
    ("move_wrap", Game::move_wrap, false),
    ("motion_set", Game::motion_set, false),
    ("motion_add", Game::motion_add, false),
    ("distance_to_point", Game::distance_to_point, false),
    ("distance_to_object", Game::distance_to_object, false),
    ("path_start", Game::path_start, false),
    ("path_end", Game::path_end, false),
    ("mp_linear_step", Game::mp_linear_step, false),
    ("mp_linear_path", Game::mp_linear_path, false),
    ("mp_linear_step_object", Game::mp_linear_step_object, false),
    ("mp_linear_path_object", Game::mp_linear_path_object, false),
    ("mp_potential_settings", Game::mp_potential_settings, false),
    ("mp_potential_step", Game::mp_potential_step, false),
    ("mp_potential_path", Game::mp_potential_path, false),
    ("mp_potential_step_object", Game::mp_potential_step_object, false),
    ("mp_potential_path_object", Game::mp_potential_path_object, false),
    ("mp_grid_create", Game::mp_grid_create, false),
    ("mp_grid_destroy", Game::mp_grid_destroy, false),
    ("mp_grid_clear_all", Game::mp_grid_clear_all, false),
    ("mp_grid_clear_cell", Game::mp_grid_clear_cell, false),
    ("mp_grid_clear_rectangle", Game::mp_grid_clear_rectangle, false),
    ("mp_grid_add_cell", Game::mp_grid_add_cell, false),
    ("mp_grid_add_rectangle", Game::mp_grid_add_rectangle, false),
    ("mp_grid_add_instances", Game::mp_grid_add_instances, false),
    ("mp_grid_path", Game::mp_grid_path, false),
    ("mp_grid_draw", Game::mp_grid_draw, false),
    ("collision_point", Game::collision_point, false),
    ("collision_rectangle", Game::collision_rectangle, false),
    ("collision_circle", Game::collision_circle, false),
    ("collision_ellipse", Game::collision_ellipse, false),
    ("collision_line", Game::collision_line, false),
    ("instance_find", Game::instance_find, false),
    ("instance_exists", Game::instance_exists, false),
    ("instance_number", Game::instance_number, false),
    ("instance_position", Game::instance_position, false),
    ("instance_nearest", Game::instance_nearest, false),
    ("instance_furthest", Game::instance_furthest, false),
    ("instance_place", Game::instance_place, false),
    ("instance_create", Game::instance_create, false),
    ("instance_copy", Game::instance_copy, false),
    ("instance_change", Game::instance_change, false),
    ("instance_destroy", Game::instance_destroy, false),
    ("instance_sprite", Game::instance_sprite, false),
    ("position_empty", Game::position_empty, false),
    ("position_meeting", Game::position_meeting, false),
    ("position_destroy", Game::position_destroy, false),
    ("position_change", Game::position_change, false),
    ("instance_deactivate_all", Game::instance_deactivate_all, false),
    ("instance_deactivate_object", Game::instance_deactivate_object, false),
    ("instance_deactivate_region", Game::instance_deactivate_region, false),
    ("instance_activate_all", Game::instance_activate_all, false),
    ("instance_activate_object", Game::instance_activate_object, false),
    ("instance_activate_region", Game::instance_activate_region, false),
    ("room_goto", Game::room_goto, false),
    ("room_goto_previous", Game::room_goto_previous, false),
    ("room_goto_next", Game::room_goto_next, false),
    ("room_previous", Game::room_previous, false),
    ("room_next", Game::room_next, false),
    ("room_restart", Game::room_restart, false),
    ("game_end", Game::game_end, false),
    ("game_restart", Game::game_restart, false),
    ("game_load", Game::game_load, false),
    ("game_save", Game::game_save, false),
    ("transition_define", Game::transition_define, false),
    ("transition_exists", Game::transition_exists, false),
    ("sleep", Game::sleep, false),
    ("YoYo_GetPlatform", Game::yoyo_getplatform, false),
    ("YoYo_GetDevice", Game::yoyo_getdevice, false),
    ("YoYo_OpenURL", Game::yoyo_openurl, false),
    ("YoYo_OpenURL_ext", Game::yoyo_openurl_ext, false),
    ("YoYo_OpenURL_full", Game::yoyo_openurl_full, false),
    ("YoYo_GetDomain", Game::yoyo_getdomain, false),
    ("YoYo_GetTimer", Game::yoyo_gettimer, false),
    ("YoYo_AddVirtualKey", Game::yoyo_addvirtualkey, false),
    ("YoYo_DeleteVirtualKey", Game::yoyo_deletevirtualkey, false),
    ("YoYo_ShowVirtualKey", Game::yoyo_showvirtualkey, false),
    ("YoYo_HideVirtualKey", Game::yoyo_hidevirtualkey, false),
    ("YoYo_EnableAlphaBlend", Game::yoyo_enablealphablend, false),
    ("file_bin_open", Game::file_bin_open, false),
    ("file_bin_rewrite", Game::file_bin_rewrite, false),
    ("file_bin_close", Game::file_bin_close, false),
    ("file_bin_position", Game::file_bin_position, false),
    ("file_bin_size", Game::file_bin_size, false),
    ("file_bin_seek", Game::file_bin_seek, false),
    ("file_bin_read_byte", Game::file_bin_read_byte, false),
    ("file_bin_write_byte", Game::file_bin_write_byte, false),
    ("file_text_open_read", Game::file_text_open_read, false),
    ("file_text_open_write", Game::file_text_open_write, false),
    ("file_text_open_append", Game::file_text_open_append, false),
    ("file_text_close", Game::file_text_close, false),
    ("file_text_read_string", Game::file_text_read_string, false),
    ("file_text_read_real", Game::file_text_read_real, false),
    ("file_text_readln", Game::file_text_readln, false),
    ("file_text_eof", Game::file_text_eof, false),
    ("file_text_eoln", Game::file_text_eoln, false),
    ("file_text_write_string", Game::file_text_write_string, false),
    ("file_text_write_real", Game::file_text_write_real, false),
    ("file_text_writeln", Game::file_text_writeln, false),
    ("file_open_read", Game::file_open_read, false),
    ("file_open_write", Game::file_open_write, false),
    ("file_open_append", Game::file_open_append, false),
    ("file_close", Game::file_close, false),
    ("file_read_string", Game::file_read_string, false),
    ("file_read_real", Game::file_read_real, false),
    ("file_readln", Game::file_readln, false),
    ("file_eof", Game::file_eof, false),
    ("file_eoln", Game::file_eoln, false),
    ("file_write_string", Game::file_write_string, false),
    ("file_write_real", Game::file_write_real, false),
    ("file_writeln", Game::file_writeln, false),
    ("file_exists", Game::file_exists, false),
    ("file_delete", Game::file_delete, false),
    ("file_rename", Game::file_rename, false),
    ("file_copy", Game::file_copy, false),
    ("directory_exists", Game::directory_exists, false),
    ("directory_create", Game::directory_create, false),
    ("file_find_first", Game::file_find_first, false),
    ("file_find_next", Game::file_find_next, false),
    ("file_find_close", Game::file_find_close, false),
    ("file_attributes", Game::file_attributes, false),
    ("filename_name", Game::filename_name, false),
    ("filename_path", Game::filename_path, false),
    ("filename_dir", Game::filename_dir, false),
    ("filename_drive", Game::filename_drive, false),
    ("filename_ext", Game::filename_ext, false),
    ("filename_change_ext", Game::filename_change_ext, false),
    ("export_include_file", Game::export_include_file, false),
    ("export_include_file_location", Game::export_include_file_location, false),
    ("discard_include_file", Game::discard_include_file, false),
    ("execute_program", Game::execute_program, false),
    ("execute_shell", Game::execute_shell, false),
    ("parameter_count", Game::parameter_count, false),
    ("parameter_string", Game::parameter_string, false),
    ("environment_get_variable", Game::environment_get_variable, false),
    ("registry_write_string", Game::registry_write_string, false),
    ("registry_write_real", Game::registry_write_real, false),
    ("registry_read_string", Game::registry_read_string, false),
    ("registry_read_real", Game::registry_read_real, false),
    ("registry_exists", Game::registry_exists, false),
    ("registry_write_string_ext", Game::registry_write_string_ext, false),
    ("registry_write_real_ext", Game::registry_write_real_ext, false),
    ("registry_read_string_ext", Game::registry_read_string_ext, false),
    ("registry_read_real_ext", Game::registry_read_real_ext, false),
    ("registry_exists_ext", Game::registry_exists_ext, false),
    ("registry_set_root", Game::registry_set_root, false),
    ("ini_open", Game::ini_open, false),
    ("ini_close", Game::ini_close, false),
    ("ini_read_string", Game::ini_read_string, false),
    ("ini_read_real", Game::ini_read_real, false),
    ("ini_write_string", Game::ini_write_string, false),
    ("ini_write_real", Game::ini_write_real, false),
    ("ini_key_exists", Game::ini_key_exists, false),
    ("ini_section_exists", Game::ini_section_exists, false),
    ("ini_key_delete", Game::ini_key_delete, false),
    ("ini_section_delete", Game::ini_section_delete, false),
    ("disk_free", Game::disk_free, false),
    ("disk_size", Game::disk_size, false),
    ("splash_set_caption", Game::splash_set_caption, false),
    ("splash_set_fullscreen", Game::splash_set_fullscreen, false),
    ("splash_set_border", Game::splash_set_border, false),
    ("splash_set_size", Game::splash_set_size, false),
    ("splash_set_position", Game::splash_set_position, false),
    ("splash_set_adapt", Game::splash_set_adapt, false),
    ("splash_set_top", Game::splash_set_top, false),
    ("splash_set_color", Game::splash_set_color, false),
    ("splash_set_main", Game::splash_set_main, false),
    ("splash_set_scale", Game::splash_set_scale, false),
    ("splash_set_cursor", Game::splash_set_cursor, false),
    ("splash_set_interrupt", Game::splash_set_interrupt, false),
    ("splash_set_stop_key", Game::splash_set_stop_key, false),
    ("splash_set_close_button", Game::splash_set_close_button, false),
    ("splash_set_stop_mouse", Game::splash_set_stop_mouse, false),
    ("splash_show_video", Game::splash_show_video, false),
    ("splash_show_image", Game::splash_show_image, false),
    ("splash_show_text", Game::splash_show_text, false),
    ("splash_show_web", Game::splash_show_web, false),
    ("show_image", Game::show_image, false),
    ("show_video", Game::show_video, false),
    ("show_text", Game::show_text, false),
    ("show_message", Game::show_message, false),
    ("show_question", Game::show_question, false),
    ("show_error", Game::show_error, false),
    ("show_info", Game::show_info, false),
    ("load_info", Game::load_info, false),
    ("highscore_show", Game::highscore_show, false),
    ("highscore_set_background", Game::highscore_set_background, false),
    ("highscore_set_border", Game::highscore_set_border, false),
    ("highscore_set_font", Game::highscore_set_font, false),
    ("highscore_set_strings", Game::highscore_set_strings, false),
    ("highscore_set_colors", Game::highscore_set_colors, false),
    ("highscore_show_ext", Game::highscore_show_ext, false),
    ("highscore_clear", Game::highscore_clear, false),
    ("highscore_add", Game::highscore_add, false),
    ("highscore_add_current", Game::highscore_add_current, false),
    ("highscore_value", Game::highscore_value, false),
    ("highscore_name", Game::highscore_name, false),
    ("draw_highscore", Game::draw_highscore, false),
    ("show_message_ext", Game::show_message_ext, false),
    ("message_background", Game::message_background, false),
    ("message_button", Game::message_button, false),
    ("message_alpha", Game::message_alpha, false),
    ("message_text_font", Game::message_text_font, false),
    ("message_button_font", Game::message_button_font, false),
    ("message_input_font", Game::message_input_font, false),
    ("message_text_charset", Game::message_text_charset, false),
    ("message_mouse_color", Game::message_mouse_color, false),
    ("message_input_color", Game::message_input_color, false),
    ("message_position", Game::message_position, false),
    ("message_size", Game::message_size, false),
    ("message_caption", Game::message_caption, false),
    ("show_menu", Game::show_menu, false),
    ("show_menu_pos", Game::show_menu_pos, false),
    ("get_integer", Game::get_integer, false),
    ("get_string", Game::get_string, false),
    ("get_color", Game::get_color, false),
    ("get_open_filename", Game::get_open_filename, false),
    ("get_save_filename", Game::get_save_filename, false),
    ("get_directory", Game::get_directory, false),
    ("get_directory_alt", Game::get_directory_alt, false),
    ("keyboard_get_numlock", Game::keyboard_get_numlock, false),
    ("keyboard_set_numlock", Game::keyboard_set_numlock, false),
    ("keyboard_key_press", Game::keyboard_key_press, false),
    ("keyboard_key_release", Game::keyboard_key_release, false),
    ("keyboard_set_map", Game::keyboard_set_map, false),
    ("keyboard_get_map", Game::keyboard_get_map, false),
    ("keyboard_unset_map", Game::keyboard_unset_map, false),
    ("keyboard_check", Game::keyboard_check, false),
    ("keyboard_check_pressed", Game::keyboard_check_pressed, false),
    ("keyboard_check_released", Game::keyboard_check_released, false),
    ("keyboard_check_direct", Game::keyboard_check_direct, false),
    ("mouse_check_button", Game::mouse_check_button, false),
    ("mouse_check_button_pressed", Game::mouse_check_button_pressed, false),
    ("mouse_check_button_released", Game::mouse_check_button_released, false),
    ("mouse_wheel_up", Game::mouse_wheel_up, false),
    ("mouse_wheel_down", Game::mouse_wheel_down, false),
    ("joystick_exists", Game::joystick_exists, false),
    ("joystick_direction", Game::joystick_direction, false),
    ("joystick_name", Game::joystick_name, false),
    ("joystick_axes", Game::joystick_axes, false),
    ("joystick_buttons", Game::joystick_buttons, false),
    ("joystick_has_pov", Game::joystick_has_pov, false),
    ("joystick_check_button", Game::joystick_check_button, false),
    ("joystick_xpos", Game::joystick_xpos, false),
    ("joystick_ypos", Game::joystick_ypos, false),
    ("joystick_zpos", Game::joystick_zpos, false),
    ("joystick_rpos", Game::joystick_rpos, false),
    ("joystick_upos", Game::joystick_upos, false),
    ("joystick_vpos", Game::joystick_vpos, false),
    ("joystick_pov", Game::joystick_pov, false),
    ("keyboard_clear", Game::keyboard_clear, false),
    ("mouse_clear", Game::mouse_clear, false),
    ("io_clear", Game::io_clear, false),
    ("io_handle", Game::io_handle, false),
    ("keyboard_wait", Game::keyboard_wait, false),
    ("mouse_wait", Game::mouse_wait, false),
    ("mplay_init_ipx", Game::mplay_init_ipx, false),
    ("mplay_init_tcpip", Game::mplay_init_tcpip, false),
    ("mplay_init_modem", Game::mplay_init_modem, false),
    ("mplay_init_serial", Game::mplay_init_serial, false),
    ("mplay_connect_status", Game::mplay_connect_status, false),
    ("mplay_end", Game::mplay_end, false),
    ("mplay_session_mode", Game::mplay_session_mode, false),
    ("mplay_session_create", Game::mplay_session_create, false),
    ("mplay_session_find", Game::mplay_session_find, false),
    ("mplay_session_name", Game::mplay_session_name, false),
    ("mplay_session_join", Game::mplay_session_join, false),
    ("mplay_session_status", Game::mplay_session_status, false),
    ("mplay_session_end", Game::mplay_session_end, false),
    ("mplay_player_find", Game::mplay_player_find, false),
    ("mplay_player_name", Game::mplay_player_name, false),
    ("mplay_player_id", Game::mplay_player_id, false),
    ("mplay_data_write", Game::mplay_data_write, false),
    ("mplay_data_read", Game::mplay_data_read, false),
    ("mplay_data_mode", Game::mplay_data_mode, false),
    ("mplay_message_send", Game::mplay_message_send, false),
    ("mplay_message_send_guaranteed", Game::mplay_message_send_guaranteed, false),
    ("mplay_message_receive", Game::mplay_message_receive, false),
    ("mplay_message_id", Game::mplay_message_id, false),
    ("mplay_message_value", Game::mplay_message_value, false),
    ("mplay_message_player", Game::mplay_message_player, false),
    ("mplay_message_name", Game::mplay_message_name, false),
    ("mplay_message_count", Game::mplay_message_count, false),
    ("mplay_message_clear", Game::mplay_message_clear, false),
    ("mplay_ipaddress", Game::mplay_ipaddress, false),
    ("event_inherited", Game::event_inherited, false),
    ("event_perform", Game::event_perform, false),
    ("event_user", Game::event_user, false),
    ("event_perform_object", Game::event_perform_object, false),
    ("external_define", Game::external_define, false),
    ("external_call", Game::external_call, false),
    ("external_free", Game::external_free, false),
    ("get_function_address", Game::get_function_address, true),
    ("external_define0", Game::external_define0, false),
    ("external_call0", Game::external_call0, false),
    ("external_define1", Game::external_define1, false),
    ("external_call1", Game::external_call1, false),
    ("external_define2", Game::external_define2, false),
    ("external_call2", Game::external_call2, false),
    ("external_define3", Game::external_define3, false),
    ("external_call3", Game::external_call3, false),
    ("external_define4", Game::external_define4, false),
    ("external_call4", Game::external_call4, false),
    ("external_define5", Game::external_define5, false),
    ("external_call5", Game::external_call5, false),
    ("external_define6", Game::external_define6, false),
    ("external_call6", Game::external_call6, false),
    ("external_define7", Game::external_define7, false),
    ("external_call7", Game::external_call7, false),
    ("external_define8", Game::external_define8, false),
    ("external_call8", Game::external_call8, false),
    ("execute_string", Game::execute_string, false),
    ("execute_file", Game::execute_file, false),
    ("window_handle", Game::window_handle, false),
    ("show_debug_message", Game::show_debug_message, false),
    ("set_program_priority", Game::set_program_priority, false),
    ("set_application_title", Game::set_application_title, false),
    ("variable_global_exists", Game::variable_global_exists, false),
    ("variable_global_get", Game::variable_global_get, false),
    ("variable_global_array_get", Game::variable_global_array_get, false),
    ("variable_global_array2_get", Game::variable_global_array2_get, false),
    ("variable_global_set", Game::variable_global_set, false),
    ("variable_global_array_set", Game::variable_global_array_set, false),
    ("variable_global_array2_set", Game::variable_global_array2_set, false),
    ("variable_local_exists", Game::variable_local_exists, false),
    ("variable_local_get", Game::variable_local_get, false),
    ("variable_local_array_get", Game::variable_local_array_get, false),
    ("variable_local_array2_get", Game::variable_local_array2_get, false),
    ("variable_local_set", Game::variable_local_set, false),
    ("variable_local_array_set", Game::variable_local_array_set, false),
    ("variable_local_array2_set", Game::variable_local_array2_set, false),
    ("clipboard_has_text", Game::clipboard_has_text, false),
    ("clipboard_set_text", Game::clipboard_set_text, false),
    ("clipboard_get_text", Game::clipboard_get_text, false),
    ("date_current_datetime", Game::date_current_datetime, false),
    ("date_current_date", Game::date_current_date, false),
    ("date_current_time", Game::date_current_time, false),
    ("date_create_datetime", Game::date_create_datetime, false),
    ("date_create_date", Game::date_create_date, false),
    ("date_create_time", Game::date_create_time, false),
    ("date_valid_datetime", Game::date_valid_datetime, false),
    ("date_valid_date", Game::date_valid_date, false),
    ("date_valid_time", Game::date_valid_time, false),
    ("date_inc_year", Game::date_inc_year, false),
    ("date_inc_month", Game::date_inc_month, false),
    ("date_inc_week", Game::date_inc_week, false),
    ("date_inc_day", Game::date_inc_day, false),
    ("date_inc_hour", Game::date_inc_hour, false),
    ("date_inc_minute", Game::date_inc_minute, false),
    ("date_inc_second", Game::date_inc_second, false),
    ("date_get_year", Game::date_get_year, false),
    ("date_get_month", Game::date_get_month, false),
    ("date_get_week", Game::date_get_week, false),
    ("date_get_day", Game::date_get_day, false),
    ("date_get_hour", Game::date_get_hour, false),
    ("date_get_minute", Game::date_get_minute, false),
    ("date_get_second", Game::date_get_second, false),
    ("date_get_weekday", Game::date_get_weekday, false),
    ("date_get_day_of_year", Game::date_get_day_of_year, false),
    ("date_get_hour_of_year", Game::date_get_hour_of_year, false),
    ("date_get_minute_of_year", Game::date_get_minute_of_year, false),
    ("date_get_second_of_year", Game::date_get_second_of_year, false),
    ("date_year_span", Game::date_year_span, false),
    ("date_month_span", Game::date_month_span, false),
    ("date_week_span", Game::date_week_span, false),
    ("date_day_span", Game::date_day_span, false),
    ("date_hour_span", Game::date_hour_span, false),
    ("date_minute_span", Game::date_minute_span, false),
    ("date_second_span", Game::date_second_span, false),
    ("date_compare_datetime", Game::date_compare_datetime, false),
    ("date_compare_date", Game::date_compare_date, false),
    ("date_compare_time", Game::date_compare_time, false),
    ("date_date_of", Game::date_date_of, false),
    ("date_time_of", Game::date_time_of, false),
    ("date_datetime_string", Game::date_datetime_string, false),
    ("date_date_string", Game::date_date_string, false),
    ("date_time_string", Game::date_time_string, false),
    ("date_days_in_month", Game::date_days_in_month, false),
    ("date_days_in_year", Game::date_days_in_year, false),
    ("date_leap_year", Game::date_leap_year, false),
    ("date_is_today", Game::date_is_today, false),
    ("sprite_name", Game::sprite_name, false),
    ("sprite_exists", Game::sprite_exists, false),
    ("sprite_get_name", Game::sprite_get_name, false),
    ("sprite_get_number", Game::sprite_get_number, false),
    ("sprite_get_width", Game::sprite_get_width, false),
    ("sprite_get_height", Game::sprite_get_height, false),
    ("sprite_get_xoffset", Game::sprite_get_xoffset, false),
    ("sprite_get_yoffset", Game::sprite_get_yoffset, false),
    ("sprite_get_bbox_left", Game::sprite_get_bbox_left, false),
    ("sprite_get_bbox_right", Game::sprite_get_bbox_right, false),
    ("sprite_get_bbox_top", Game::sprite_get_bbox_top, false),
    ("sprite_get_bbox_bottom", Game::sprite_get_bbox_bottom, false),
    ("sprite_set_offset", Game::sprite_set_offset, false),
    ("sprite_set_alpha_from_sprite", Game::sprite_set_alpha_from_sprite, false),
    ("sprite_create_from_screen", Game::sprite_create_from_screen, false),
    ("sprite_add_from_screen", Game::sprite_add_from_screen, false),
    ("sprite_create_from_surface", Game::sprite_create_from_surface, false),
    ("sprite_add_from_surface", Game::sprite_add_from_surface, false),
    ("sprite_add", Game::sprite_add, false),
    ("sprite_replace", Game::sprite_replace, false),
    ("sprite_add_sprite", Game::sprite_add_sprite, false),
    ("sprite_replace_sprite", Game::sprite_replace_sprite, false),
    ("sprite_delete", Game::sprite_delete, false),
    ("sprite_duplicate", Game::sprite_duplicate, false),
    ("sprite_assign", Game::sprite_assign, false),
    ("sprite_merge", Game::sprite_merge, false),
    ("sprite_save", Game::sprite_save, false),
    ("sprite_save_strip", Game::sprite_save_strip, false),
    ("sprite_collision_mask", Game::sprite_collision_mask, false),
    ("sprite_set_cache_size", Game::sprite_set_cache_size, false),
    ("sprite_set_cache_size_ext", Game::sprite_set_cache_size_ext, false),
    ("background_name", Game::background_name, false),
    ("background_exists", Game::background_exists, false),
    ("background_get_name", Game::background_get_name, false),
    ("background_get_width", Game::background_get_width, false),
    ("background_get_height", Game::background_get_height, false),
    ("background_set_alpha_from_background", Game::background_set_alpha_from_background, false),
    ("background_create_from_screen", Game::background_create_from_screen, false),
    ("background_create_from_surface", Game::background_create_from_surface, false),
    ("background_create_color", Game::background_create_color, false),
    ("background_create_gradient", Game::background_create_gradient, false),
    ("background_add", Game::background_add, false),
    ("background_replace", Game::background_replace, false),
    ("background_add_background", Game::background_add_background, false),
    ("background_replace_background", Game::background_replace_background, false),
    ("background_delete", Game::background_delete, false),
    ("background_duplicate", Game::background_duplicate, false),
    ("background_assign", Game::background_assign, false),
    ("background_save", Game::background_save, false),
    ("sound_name", Game::sound_name, false),
    ("sound_exists", Game::sound_exists, false),
    ("sound_get_name", Game::sound_get_name, false),
    ("sound_get_kind", Game::sound_get_kind, false),
    ("sound_get_preload", Game::sound_get_preload, false),
    ("sound_discard", Game::sound_discard, false),
    ("sound_restore", Game::sound_restore, false),
    ("sound_add", Game::sound_add, false),
    ("sound_replace", Game::sound_replace, false),
    ("sound_delete", Game::sound_delete, false),
    ("font_name", Game::font_name, false),
    ("font_exists", Game::font_exists, false),
    ("font_get_name", Game::font_get_name, false),
    ("font_get_fontname", Game::font_get_fontname, false),
    ("font_get_size", Game::font_get_size, false),
    ("font_get_bold", Game::font_get_bold, false),
    ("font_get_italic", Game::font_get_italic, false),
    ("font_get_first", Game::font_get_first, false),
    ("font_get_last", Game::font_get_last, false),
    ("font_add", Game::font_add, false),
    ("font_replace", Game::font_replace, false),
    ("font_add_sprite", Game::font_add_sprite, false),
    ("font_replace_sprite", Game::font_replace_sprite, false),
    ("font_delete", Game::font_delete, false),
    ("script_name", Game::script_name, false),
    ("script_exists", Game::script_exists, false),
    ("script_get_name", Game::script_get_name, false),
    ("script_get_text", Game::script_get_text, false),
    ("script_execute", Game::script_execute, false),
    ("path_name", Game::path_name, false),
    ("path_exists", Game::path_exists, false),
    ("path_get_name", Game::path_get_name, false),
    ("path_get_length", Game::path_get_length, false),
    ("path_get_kind", Game::path_get_kind, false),
    ("path_get_closed", Game::path_get_closed, false),
    ("path_get_precision", Game::path_get_precision, false),
    ("path_get_number", Game::path_get_number, false),
    ("path_get_point_x", Game::path_get_point_x, false),
    ("path_get_point_y", Game::path_get_point_y, false),
    ("path_get_point_speed", Game::path_get_point_speed, false),
    ("path_get_x", Game::path_get_x, false),
    ("path_get_y", Game::path_get_y, false),
    ("path_get_speed", Game::path_get_speed, false),
    ("path_set_kind", Game::path_set_kind, false),
    ("path_set_closed", Game::path_set_closed, false),
    ("path_set_precision", Game::path_set_precision, false),
    ("path_add", Game::path_add, false),
    ("path_duplicate", Game::path_duplicate, false),
    ("path_assign", Game::path_assign, false),
    ("path_append", Game::path_append, false),
    ("path_delete", Game::path_delete, false),
    ("path_add_point", Game::path_add_point, false),
    ("path_insert_point", Game::path_insert_point, false),
    ("path_change_point", Game::path_change_point, false),
    ("path_delete_point", Game::path_delete_point, false),
    ("path_clear_points", Game::path_clear_points, false),
    ("path_reverse", Game::path_reverse, false),
    ("path_mirror", Game::path_mirror, false),
    ("path_flip", Game::path_flip, false),
    ("path_rotate", Game::path_rotate, false),
    ("path_scale", Game::path_scale, false),
    ("path_shift", Game::path_shift, false),
    ("timeline_name", Game::timeline_name, false),
    ("timeline_exists", Game::timeline_exists, false),
    ("timeline_get_name", Game::timeline_get_name, false),
    ("timeline_add", Game::timeline_add, false),
    ("timeline_delete", Game::timeline_delete, false),
    ("timeline_clear", Game::timeline_clear, false),
    ("timeline_moment_clear", Game::timeline_moment_clear, false),
    ("timeline_moment_add", Game::timeline_moment_add, false),
    ("object_name", Game::object_name, false),
    ("object_exists", Game::object_exists, false),
    ("object_get_name", Game::object_get_name, false),
    ("object_get_sprite", Game::object_get_sprite, false),
    ("object_get_solid", Game::object_get_solid, false),
    ("object_get_visible", Game::object_get_visible, false),
    ("object_get_depth", Game::object_get_depth, false),
    ("object_get_persistent", Game::object_get_persistent, false),
    ("object_get_mask", Game::object_get_mask, false),
    ("object_get_parent", Game::object_get_parent, false),
    ("object_is_ancestor", Game::object_is_ancestor, false),
    ("object_set_sprite", Game::object_set_sprite, false),
    ("object_set_solid", Game::object_set_solid, false),
    ("object_set_visible", Game::object_set_visible, false),
    ("object_set_depth", Game::object_set_depth, false),
    ("object_set_persistent", Game::object_set_persistent, false),
    ("object_set_mask", Game::object_set_mask, false),
    ("object_set_parent", Game::object_set_parent, false),
    ("object_add", Game::object_add, false),
    ("object_delete", Game::object_delete, false),
    ("object_event_clear", Game::object_event_clear, false),
    ("object_event_add", Game::object_event_add, false),
    ("room_name", Game::room_name, false),
    ("room_exists", Game::room_exists, false),
    ("room_get_name", Game::room_get_name, false),
    ("room_set_width", Game::room_set_width, false),
    ("room_set_height", Game::room_set_height, false),
    ("room_set_caption", Game::room_set_caption, false),
    ("room_set_persistent", Game::room_set_persistent, false),
    ("room_set_code", Game::room_set_code, false),
    ("room_set_background_color", Game::room_set_background_color, false),
    ("room_set_background", Game::room_set_background, false),
    ("room_set_view", Game::room_set_view, false),
    ("room_set_view_enabled", Game::room_set_view_enabled, false),
    ("room_add", Game::room_add, false),
    ("room_duplicate", Game::room_duplicate, false),
    ("room_assign", Game::room_assign, false),
    ("room_instance_add", Game::room_instance_add, false),
    ("room_instance_clear", Game::room_instance_clear, false),
    ("room_tile_add", Game::room_tile_add, false),
    ("room_tile_add_ext", Game::room_tile_add_ext, false),
    ("room_tile_clear", Game::room_tile_clear, false),
    ("part_type_create", Game::part_type_create, false),
    ("part_type_destroy", Game::part_type_destroy, false),
    ("part_type_exists", Game::part_type_exists, false),
    ("part_type_clear", Game::part_type_clear, false),
    ("part_type_shape", Game::part_type_shape, false),
    ("part_type_sprite", Game::part_type_sprite, false),
    ("part_type_size", Game::part_type_size, false),
    ("part_type_scale", Game::part_type_scale, false),
    ("part_type_life", Game::part_type_life, false),
    ("part_type_step", Game::part_type_step, false),
    ("part_type_death", Game::part_type_death, false),
    ("part_type_speed", Game::part_type_speed, false),
    ("part_type_direction", Game::part_type_direction, false),
    ("part_type_orientation", Game::part_type_orientation, false),
    ("part_type_gravity", Game::part_type_gravity, false),
    ("part_type_color_mix", Game::part_type_color_mix, false),
    ("part_type_color_rgb", Game::part_type_color_rgb, false),
    ("part_type_color_hsv", Game::part_type_color_hsv, false),
    ("part_type_color1", Game::part_type_color1, false),
    ("part_type_color2", Game::part_type_color2, false),
    ("part_type_color3", Game::part_type_color3, false),
    ("part_type_color", Game::part_type_color, false),
    ("part_type_alpha1", Game::part_type_alpha1, false),
    ("part_type_alpha2", Game::part_type_alpha2, false),
    ("part_type_alpha3", Game::part_type_alpha3, false),
    ("part_type_alpha", Game::part_type_alpha, false),
    ("part_type_blend", Game::part_type_blend, false),
    ("part_system_create", Game::part_system_create, false),
    ("part_system_destroy", Game::part_system_destroy, false),
    ("part_system_exists", Game::part_system_exists, false),
    ("part_system_clear", Game::part_system_clear, false),
    ("part_system_draw_order", Game::part_system_draw_order, false),
    ("part_system_depth", Game::part_system_depth, false),
    ("part_system_position", Game::part_system_position, false),
    ("part_system_automatic_update", Game::part_system_automatic_update, false),
    ("part_system_automatic_draw", Game::part_system_automatic_draw, false),
    ("part_system_update", Game::part_system_update, false),
    ("part_system_drawit", Game::part_system_drawit, false),
    ("part_particles_create", Game::part_particles_create, false),
    ("part_particles_create_color", Game::part_particles_create_color, false),
    ("part_particles_clear", Game::part_particles_clear, false),
    ("part_particles_count", Game::part_particles_count, false),
    ("part_emitter_create", Game::part_emitter_create, false),
    ("part_emitter_destroy", Game::part_emitter_destroy, false),
    ("part_emitter_destroy_all", Game::part_emitter_destroy_all, false),
    ("part_emitter_exists", Game::part_emitter_exists, false),
    ("part_emitter_clear", Game::part_emitter_clear, false),
    ("part_emitter_region", Game::part_emitter_region, false),
    ("part_emitter_burst", Game::part_emitter_burst, false),
    ("part_emitter_stream", Game::part_emitter_stream, false),
    ("part_attractor_create", Game::part_attractor_create, false),
    ("part_attractor_destroy", Game::part_attractor_destroy, false),
    ("part_attractor_destroy_all", Game::part_attractor_destroy_all, false),
    ("part_attractor_exists", Game::part_attractor_exists, false),
    ("part_attractor_clear", Game::part_attractor_clear, false),
    ("part_attractor_position", Game::part_attractor_position, false),
    ("part_attractor_force", Game::part_attractor_force, false),
    ("part_destroyer_create", Game::part_destroyer_create, false),
    ("part_destroyer_destroy", Game::part_destroyer_destroy, false),
    ("part_destroyer_destroy_all", Game::part_destroyer_destroy_all, false),
    ("part_destroyer_exists", Game::part_destroyer_exists, false),
    ("part_destroyer_clear", Game::part_destroyer_clear, false),
    ("part_destroyer_region", Game::part_destroyer_region, false),
    ("part_deflector_create", Game::part_deflector_create, false),
    ("part_deflector_destroy", Game::part_deflector_destroy, false),
    ("part_deflector_destroy_all", Game::part_deflector_destroy_all, false),
    ("part_deflector_exists", Game::part_deflector_exists, false),
    ("part_deflector_clear", Game::part_deflector_clear, false),
    ("part_deflector_region", Game::part_deflector_region, false),
    ("part_deflector_kind", Game::part_deflector_kind, false),
    ("part_deflector_friction", Game::part_deflector_friction, false),
    ("part_changer_create", Game::part_changer_create, false),
    ("part_changer_destroy", Game::part_changer_destroy, false),
    ("part_changer_destroy_all", Game::part_changer_destroy_all, false),
    ("part_changer_exists", Game::part_changer_exists, false),
    ("part_changer_clear", Game::part_changer_clear, false),
    ("part_changer_region", Game::part_changer_region, false),
    ("part_changer_kind", Game::part_changer_kind, false),
    ("part_changer_types", Game::part_changer_types, false),
    ("effect_create_below", Game::effect_create_below, false),
    ("effect_create_above", Game::effect_create_above, false),
    ("effect_clear", Game::effect_clear, false),
    ("ds_set_precision", Game::ds_set_precision, false),
    ("ds_stack_create", Game::ds_stack_create, false),
    ("ds_stack_destroy", Game::ds_stack_destroy, false),
    ("ds_stack_clear", Game::ds_stack_clear, false),
    ("ds_stack_copy", Game::ds_stack_copy, false),
    ("ds_stack_size", Game::ds_stack_size, false),
    ("ds_stack_empty", Game::ds_stack_empty, false),
    ("ds_stack_push", Game::ds_stack_push, false),
    ("ds_stack_pop", Game::ds_stack_pop, false),
    ("ds_stack_top", Game::ds_stack_top, false),
    ("ds_stack_write", Game::ds_stack_write, false),
    ("ds_stack_read", Game::ds_stack_read, false),
    ("ds_queue_create", Game::ds_queue_create, false),
    ("ds_queue_destroy", Game::ds_queue_destroy, false),
    ("ds_queue_clear", Game::ds_queue_clear, false),
    ("ds_queue_copy", Game::ds_queue_copy, false),
    ("ds_queue_size", Game::ds_queue_size, false),
    ("ds_queue_empty", Game::ds_queue_empty, false),
    ("ds_queue_enqueue", Game::ds_queue_enqueue, false),
    ("ds_queue_dequeue", Game::ds_queue_dequeue, false),
    ("ds_queue_head", Game::ds_queue_head, false),
    ("ds_queue_tail", Game::ds_queue_tail, false),
    ("ds_queue_write", Game::ds_queue_write, false),
    ("ds_queue_read", Game::ds_queue_read, false),
    ("ds_list_create", Game::ds_list_create, false),
    ("ds_list_destroy", Game::ds_list_destroy, false),
    ("ds_list_clear", Game::ds_list_clear, false),
    ("ds_list_copy", Game::ds_list_copy, false),
    ("ds_list_size", Game::ds_list_size, false),
    ("ds_list_empty", Game::ds_list_empty, false),
    ("ds_list_add", Game::ds_list_add, false),
    ("ds_list_insert", Game::ds_list_insert, false),
    ("ds_list_replace", Game::ds_list_replace, false),
    ("ds_list_delete", Game::ds_list_delete, false),
    ("ds_list_find_index", Game::ds_list_find_index, false),
    ("ds_list_find_value", Game::ds_list_find_value, false),
    ("ds_list_sort", Game::ds_list_sort, false),
    ("ds_list_shuffle", Game::ds_list_shuffle, false),
    ("ds_list_write", Game::ds_list_write, false),
    ("ds_list_read", Game::ds_list_read, false),
    ("ds_map_create", Game::ds_map_create, false),
    ("ds_map_destroy", Game::ds_map_destroy, false),
    ("ds_map_clear", Game::ds_map_clear, false),
    ("ds_map_copy", Game::ds_map_copy, false),
    ("ds_map_size", Game::ds_map_size, false),
    ("ds_map_empty", Game::ds_map_empty, false),
    ("ds_map_add", Game::ds_map_add, false),
    ("ds_map_replace", Game::ds_map_replace, false),
    ("ds_map_delete", Game::ds_map_delete, false),
    ("ds_map_exists", Game::ds_map_exists, false),
    ("ds_map_find_value", Game::ds_map_find_value, false),
    ("ds_map_find_previous", Game::ds_map_find_previous, false),
    ("ds_map_find_next", Game::ds_map_find_next, false),
    ("ds_map_find_first", Game::ds_map_find_first, false),
    ("ds_map_find_last", Game::ds_map_find_last, false),
    ("ds_map_write", Game::ds_map_write, false),
    ("ds_map_read", Game::ds_map_read, false),
    ("ds_priority_create", Game::ds_priority_create, false),
    ("ds_priority_destroy", Game::ds_priority_destroy, false),
    ("ds_priority_clear", Game::ds_priority_clear, false),
    ("ds_priority_copy", Game::ds_priority_copy, false),
    ("ds_priority_size", Game::ds_priority_size, false),
    ("ds_priority_empty", Game::ds_priority_empty, false),
    ("ds_priority_add", Game::ds_priority_add, false),
    ("ds_priority_change_priority", Game::ds_priority_change_priority, false),
    ("ds_priority_find_priority", Game::ds_priority_find_priority, false),
    ("ds_priority_delete_value", Game::ds_priority_delete_value, false),
    ("ds_priority_delete_min", Game::ds_priority_delete_min, false),
    ("ds_priority_find_min", Game::ds_priority_find_min, false),
    ("ds_priority_delete_max", Game::ds_priority_delete_max, false),
    ("ds_priority_find_max", Game::ds_priority_find_max, false),
    ("ds_priority_write", Game::ds_priority_write, false),
    ("ds_priority_read", Game::ds_priority_read, false),
    ("ds_grid_create", Game::ds_grid_create, false),
    ("ds_grid_destroy", Game::ds_grid_destroy, false),
    ("ds_grid_copy", Game::ds_grid_copy, false),
    ("ds_grid_resize", Game::ds_grid_resize, false),
    ("ds_grid_width", Game::ds_grid_width, false),
    ("ds_grid_height", Game::ds_grid_height, false),
    ("ds_grid_clear", Game::ds_grid_clear, false),
    ("ds_grid_set", Game::ds_grid_set, false),
    ("ds_grid_add", Game::ds_grid_add, false),
    ("ds_grid_multiply", Game::ds_grid_multiply, false),
    ("ds_grid_set_region", Game::ds_grid_set_region, false),
    ("ds_grid_add_region", Game::ds_grid_add_region, false),
    ("ds_grid_multiply_region", Game::ds_grid_multiply_region, false),
    ("ds_grid_set_disk", Game::ds_grid_set_disk, false),
    ("ds_grid_add_disk", Game::ds_grid_add_disk, false),
    ("ds_grid_multiply_disk", Game::ds_grid_multiply_disk, false),
    ("ds_grid_set_grid_region", Game::ds_grid_set_grid_region, false),
    ("ds_grid_add_grid_region", Game::ds_grid_add_grid_region, false),
    ("ds_grid_multiply_grid_region", Game::ds_grid_multiply_grid_region, false),
    ("ds_grid_get", Game::ds_grid_get, false),
    ("ds_grid_get_sum", Game::ds_grid_get_sum, false),
    ("ds_grid_get_max", Game::ds_grid_get_max, false),
    ("ds_grid_get_min", Game::ds_grid_get_min, false),
    ("ds_grid_get_mean", Game::ds_grid_get_mean, false),
    ("ds_grid_get_disk_sum", Game::ds_grid_get_disk_sum, false),
    ("ds_grid_get_disk_max", Game::ds_grid_get_disk_max, false),
    ("ds_grid_get_disk_min", Game::ds_grid_get_disk_min, false),
    ("ds_grid_get_disk_mean", Game::ds_grid_get_disk_mean, false),
    ("ds_grid_value_exists", Game::ds_grid_value_exists, false),
    ("ds_grid_value_x", Game::ds_grid_value_x, false),
    ("ds_grid_value_y", Game::ds_grid_value_y, false),
    ("ds_grid_value_disk_exists", Game::ds_grid_value_disk_exists, false),
    ("ds_grid_value_disk_x", Game::ds_grid_value_disk_x, false),
    ("ds_grid_value_disk_y", Game::ds_grid_value_disk_y, false),
    ("ds_grid_shuffle", Game::ds_grid_shuffle, false),
    ("ds_grid_write", Game::ds_grid_write, false),
    ("ds_grid_read", Game::ds_grid_read, false),
    ("sound_play", Game::sound_play, false),
    ("sound_loop", Game::sound_loop, false),
    ("sound_stop", Game::sound_stop, false),
    ("sound_stop_all", Game::sound_stop_all, false),
    ("sound_isplaying", Game::sound_isplaying, false),
    ("sound_volume", Game::sound_volume, false),
    ("sound_fade", Game::sound_fade, false),
    ("sound_pan", Game::sound_pan, false),
    ("sound_background_tempo", Game::sound_background_tempo, false),
    ("sound_global_volume", Game::sound_global_volume, false),
    ("sound_set_search_directory", Game::sound_set_search_directory, false),
    ("sound_effect_set", Game::sound_effect_set, false),
    ("sound_effect_chorus", Game::sound_effect_chorus, false),
    ("sound_effect_compressor", Game::sound_effect_compressor, false),
    ("sound_effect_echo", Game::sound_effect_echo, false),
    ("sound_effect_flanger", Game::sound_effect_flanger, false),
    ("sound_effect_gargle", Game::sound_effect_gargle, false),
    ("sound_effect_equalizer", Game::sound_effect_equalizer, false),
    ("sound_effect_reverb", Game::sound_effect_reverb, false),
    ("sound_3d_set_sound_position", Game::sound_3d_set_sound_position, false),
    ("sound_3d_set_sound_velocity", Game::sound_3d_set_sound_velocity, false),
    ("sound_3d_set_sound_distance", Game::sound_3d_set_sound_distance, false),
    ("sound_3d_set_sound_cone", Game::sound_3d_set_sound_cone, false),
    ("cd_init", Game::cd_init, false),
    ("cd_present", Game::cd_present, false),
    ("cd_number", Game::cd_number, false),
    ("cd_playing", Game::cd_playing, false),
    ("cd_paused", Game::cd_paused, false),
    ("cd_track", Game::cd_track, false),
    ("cd_length", Game::cd_length, false),
    ("cd_track_length", Game::cd_track_length, false),
    ("cd_position", Game::cd_position, false),
    ("cd_track_position", Game::cd_track_position, false),
    ("cd_play", Game::cd_play, false),
    ("cd_stop", Game::cd_stop, false),
    ("cd_pause", Game::cd_pause, false),
    ("cd_resume", Game::cd_resume, false),
    ("cd_set_position", Game::cd_set_position, false),
    ("cd_set_track_position", Game::cd_set_track_position, false),
    ("cd_open_door", Game::cd_open_door, false),
    ("cd_close_door", Game::cd_close_door, false),
    ("MCI_command", Game::mci_command, false),
    ("d3d_start", Game::d3d_start, false),
    ("d3d_end", Game::d3d_end, false),
    ("d3d_set_perspective", Game::d3d_set_perspective, false),
    ("d3d_set_hidden", Game::d3d_set_hidden, false),
    ("d3d_set_depth", Game::d3d_set_depth, false),
    ("d3d_set_zwriteenable", Game::d3d_set_zwriteenable, false),
    ("d3d_set_lighting", Game::d3d_set_lighting, false),
    ("d3d_set_shading", Game::d3d_set_shading, false),
    ("d3d_set_fog", Game::d3d_set_fog, false),
    ("d3d_set_culling", Game::d3d_set_culling, false),
    ("d3d_primitive_begin", Game::d3d_primitive_begin, false),
    ("d3d_primitive_begin_texture", Game::d3d_primitive_begin_texture, false),
    ("d3d_primitive_end", Game::d3d_primitive_end, false),
    ("d3d_vertex", Game::d3d_vertex, false),
    ("d3d_vertex_color", Game::d3d_vertex_color, false),
    ("d3d_vertex_texture", Game::d3d_vertex_texture, false),
    ("d3d_vertex_texture_color", Game::d3d_vertex_texture_color, false),
    ("d3d_vertex_normal", Game::d3d_vertex_normal, false),
    ("d3d_vertex_normal_color", Game::d3d_vertex_normal_color, false),
    ("d3d_vertex_normal_texture", Game::d3d_vertex_normal_texture, false),
    ("d3d_vertex_normal_texture_color", Game::d3d_vertex_normal_texture_color, false),
    ("d3d_draw_block", Game::d3d_draw_block, false),
    ("d3d_draw_cylinder", Game::d3d_draw_cylinder, false),
    ("d3d_draw_cone", Game::d3d_draw_cone, false),
    ("d3d_draw_ellipsoid", Game::d3d_draw_ellipsoid, false),
    ("d3d_draw_wall", Game::d3d_draw_wall, false),
    ("d3d_draw_floor", Game::d3d_draw_floor, false),
    ("d3d_set_projection", Game::d3d_set_projection, false),
    ("d3d_set_projection_ext", Game::d3d_set_projection_ext, false),
    ("d3d_set_projection_ortho", Game::d3d_set_projection_ortho, false),
    ("d3d_set_projection_perspective", Game::d3d_set_projection_perspective, false),
    ("d3d_transform_set_identity", Game::d3d_transform_set_identity, false),
    ("d3d_transform_set_translation", Game::d3d_transform_set_translation, false),
    ("d3d_transform_set_scaling", Game::d3d_transform_set_scaling, false),
    ("d3d_transform_set_rotation_x", Game::d3d_transform_set_rotation_x, false),
    ("d3d_transform_set_rotation_y", Game::d3d_transform_set_rotation_y, false),
    ("d3d_transform_set_rotation_z", Game::d3d_transform_set_rotation_z, false),
    ("d3d_transform_set_rotation_axis", Game::d3d_transform_set_rotation_axis, false),
    ("d3d_transform_add_translation", Game::d3d_transform_add_translation, false),
    ("d3d_transform_add_scaling", Game::d3d_transform_add_scaling, false),
    ("d3d_transform_add_rotation_x", Game::d3d_transform_add_rotation_x, false),
    ("d3d_transform_add_rotation_y", Game::d3d_transform_add_rotation_y, false),
    ("d3d_transform_add_rotation_z", Game::d3d_transform_add_rotation_z, false),
    ("d3d_transform_add_rotation_axis", Game::d3d_transform_add_rotation_axis, false),
    ("d3d_transform_stack_clear", Game::d3d_transform_stack_clear, false),
    ("d3d_transform_stack_empty", Game::d3d_transform_stack_empty, false),
    ("d3d_transform_stack_push", Game::d3d_transform_stack_push, false),
    ("d3d_transform_stack_pop", Game::d3d_transform_stack_pop, false),
    ("d3d_transform_stack_top", Game::d3d_transform_stack_top, false),
    ("d3d_transform_stack_discard", Game::d3d_transform_stack_discard, false),
    ("d3d_light_define_ambient", Game::d3d_light_define_ambient, false),
    ("d3d_light_define_direction", Game::d3d_light_define_direction, false),
    ("d3d_light_define_point", Game::d3d_light_define_point, false),
    ("d3d_light_enable", Game::d3d_light_enable, false),
    ("d3d_model_create", Game::d3d_model_create, false),
    ("d3d_model_destroy", Game::d3d_model_destroy, false),
    ("d3d_model_clear", Game::d3d_model_clear, false),
    ("d3d_model_load", Game::d3d_model_load, false),
    ("d3d_model_save", Game::d3d_model_save, false),
    ("d3d_model_draw", Game::d3d_model_draw, false),
    ("d3d_model_primitive_begin", Game::d3d_model_primitive_begin, false),
    ("d3d_model_primitive_end", Game::d3d_model_primitive_end, false),
    ("d3d_model_vertex", Game::d3d_model_vertex, false),
    ("d3d_model_vertex_color", Game::d3d_model_vertex_color, false),
    ("d3d_model_vertex_texture", Game::d3d_model_vertex_texture, false),
    ("d3d_model_vertex_texture_color", Game::d3d_model_vertex_texture_color, false),
    ("d3d_model_vertex_normal", Game::d3d_model_vertex_normal, false),
    ("d3d_model_vertex_normal_color", Game::d3d_model_vertex_normal_color, false),
    ("d3d_model_vertex_normal_texture", Game::d3d_model_vertex_normal_texture, false),
    ("d3d_model_vertex_normal_texture_color", Game::d3d_model_vertex_normal_texture_color, false),
    ("d3d_model_block", Game::d3d_model_block, false),
    ("d3d_model_cylinder", Game::d3d_model_cylinder, false),
    ("d3d_model_cone", Game::d3d_model_cone, false),
    ("d3d_model_ellipsoid", Game::d3d_model_ellipsoid, false),
    ("d3d_model_wall", Game::d3d_model_wall, false),
    ("d3d_model_floor", Game::d3d_model_floor, false),
];
